# -*- mode: python -*-

import utils
from build import build_app
Import('env')

target = 'execFlowFunctionObjects'

sources = Split("""
execFlowFunctionObjects.cpp
""")

caelus_inc = [
'transportModels',
'transportModels/incompressible/lnInclude',
'turbulenceModels',
'turbulenceModels/incompressible/turbulenceModel/lnInclude',
'turbulenceModels/incompressible/RAS/lnInclude',
'turbulenceModels/incompressible/LES/lnInclude',
'turbulenceModels/compressible/turbulenceModel/lnInclude',
'turbulenceModels/compressible/RAS/lnInclude',
'turbulenceModels/compressible/LES/lnInclude',
'turbulenceModels/LES/LESdeltas/lnInclude',
'thermophysicalModels/basic/lnInclude',
'fvOptions/lnInclude',
'sampling/lnInclude',
'waves/waves/lnInclude',
'waves/waves/include',
]

caelus_libs = [
'core',
'incompressibleTransportModels',
'incompressibleTurbulenceModel',
'compressibleTurbulenceModel',
'incompressibleRASModels',
'incompressibleLESModels',
'fluidThermophysicalModels',
'specie',
'compressibleRASModels',
'compressibleLESModels',
'fvOptions',
'sampling',
'waves',
'wavesSampling',
'pgsl',
]

ostype = utils.ostype()
prepend_args = {}
if ostype == 'windows':
   prepend_args = {'LINKFLAGS' :
         '-u genericPatchFieldsLoad -u incompressibleRASModelsLoad -u incompressibleLESModelsLoad -u compressibleRASModelsLoad -u compressibleLESModelsLoad -u turbulenceDerivedFvPatchFieldsLoad'
}

build_app(env,
          target=target,
          sources=sources,
          caelus_inc=caelus_inc,
          caelus_libs=caelus_libs,
          prepend_args=prepend_args)
