#Copyright (C) 2014 Applied CCM
import subprocess
Import('globalEnv')

# Clone the global environment so changes made he are not pass onto subsequent 
# libraries
execFlowFOEnv = globalEnv.Clone()

# Path to source
src = execFlowFOEnv['LIB_SRC']

#===============================================================================
# Additions to compiler flags for this executable
#===============================================================================
execFlowFOEnv.Append(CCFLAGS = '')

#===============================================================================
# Additions to include directories for this executable
#===============================================================================
lib_inc = [src + '/transportModels',
src + '/transportModels/incompressible/lnInclude',
src + '/turbulenceModels',
src + '/turbulenceModels/incompressible/turbulenceModel/lnInclude',  
src + '/turbulenceModels/incompressible/RAS/lnInclude',  
src + '/turbulenceModels/incompressible/LES/lnInclude',
src + '/turbulenceModels/compressible/turbulenceModel/lnInclude',  
src + '/turbulenceModels/compressible/RAS/lnInclude', 
src + '/turbulenceModels/compressible/LES/lnInclude',     
src + '/turbulenceModels/LES/LESdeltas/lnInclude',
src + '/thermophysicalModels/basic/lnInclude',
src + '/fvOptions/lnInclude',
src + '/sampling/lnInclude'
]    
execFlowFOEnv.Prepend(CPPPATH = lib_inc)

#===============================================================================
# Additions to link library paths for this executable
#===============================================================================
lib_link_path = []
execFlowFOEnv.Prepend(LIBPATH = lib_link_path)

#===============================================================================
# Additions to link libraries for this executable
#===============================================================================
if execFlowFOEnv['WHICH_OS'] == "windows":
  execFlowFOEnv.Prepend(LINKFLAGS = ' -u genericPatchFieldsLoad -u incompressibleRASModelsLoad -u incompressibleLESModelsLoad -u compressibleRASModelsLoad -u genericPatchFieldsLoad')

lib_link = ['core','incompressibleTransportModels',
'incompressibleTurbulenceModel','compressibleTurbulenceModel',
'incompressibleRASModels','incompressibleLESModels',
'basicThermophysicalModels','specie','compressibleRASModels',
'compressibleLESModels','genericPatchFields','fvOptions','sampling']
execFlowFOEnv.Append(LIBS = lib_link)

#===============================================================================
# Sources for this executable
#===============================================================================
src_files_exec = Split("""
  execFlowFunctionObjects.cpp
  """)

src_files = src_files_exec
#===============================================================================
# Build this executable
#===============================================================================
binexecFlowFO = execFlowFOEnv.Program(target = 'execFlowFunctionObjects',
source = src_files)

#===============================================================================
# Install this executable
#===============================================================================
install_dir = execFlowFOEnv['BIN_PLATFORM_INSTALL']
execFlowFOEnv.Alias('install', install_dir)
execFlowFOEnv.Install(install_dir, binexecFlowFO)
