#Copyright (C) 2014 Applied CCM
import subprocess
Import('globalEnv')

# Clone the global environment so changes made he are not pass onto subsequent 
# libraries
uprimeEnv = globalEnv.Clone()

# Path to source
src = uprimeEnv['LIB_SRC']

#===============================================================================
# Additions to compiler flags for this executable
#===============================================================================
uprimeEnv.Append(CCFLAGS = '')

#===============================================================================
# Additions to include directories for this executable
#===============================================================================
lib_inc = [src + '/postProcessing/postCalc']        
uprimeEnv.Prepend(CPPPATH = lib_inc)

#===============================================================================
# Additions to link library paths for this executable
#===============================================================================
lib_link_path = []
uprimeEnv.Prepend(LIBPATH = lib_link_path)

#===============================================================================
# Additions to link libraries for this executable
#===============================================================================
if uprimeEnv['WHICH_OS'] == "windows":
  uprimeEnv.Prepend(LINKFLAGS = ' -u genericPatchFieldsLoad')
  lib_link = ['libcore','libgenericPatchFields']
else:
  lib_link = ['core','genericPatchFields']
    
uprimeEnv.Append(LIBS = lib_link)

#===============================================================================
# Sources for this executable
#===============================================================================
src_files_postCalc = [uprimeEnv['LIB_PLATFORM_INSTALL'] + '/postCalc.o']

src_files_exec = Split("""  
  uprime.cpp
  """)

src_files = src_files_postCalc + src_files_exec
#===============================================================================
# Build this executable
#===============================================================================
binuprime = uprimeEnv.Program(target = 'uprime',
source = src_files)

#===============================================================================
# Install this executable
#===============================================================================
install_dir = uprimeEnv['BIN_PLATFORM_INSTALL']
uprimeEnv.Alias('install', install_dir)
uprimeEnv.Install(install_dir, binuprime)
