# -*- mode: python -*-

from build import build_lib
Import('env')

target = 'dynamicMesh'

sources = Split("""
attachDetach/attachDetach.cpp
attachDetach/attachInterface.cpp
attachDetach/detachInterface.cpp
attachDetach/attachDetachPointMatchMap.cpp
layerAdditionRemoval/layerAdditionRemoval.cpp
layerAdditionRemoval/setLayerPairing.cpp
layerAdditionRemoval/addCellLayer.cpp
layerAdditionRemoval/removeCellLayer.cpp
slidingInterface/enrichedPatch/enrichedPatch.cpp
slidingInterface/enrichedPatch/enrichedPatchPointMap.cpp
slidingInterface/enrichedPatch/enrichedPatchFaces.cpp
slidingInterface/enrichedPatch/enrichedPatchPointPoints.cpp
slidingInterface/enrichedPatch/enrichedPatchCutFaces.cpp
slidingInterface/enrichedPatch/enrichedPatchMasterPoints.cpp
polyTopoChange/polyMeshModifier/polyMeshModifier.cpp
polyTopoChange/polyMeshModifier/polyMeshModifierNew.cpp
polyTopoChange/polyTopoChange/topoAction/topoActions.cpp
polyTopoChange/polyTopoChanger/polyTopoChanger.cpp
polyTopoChange/polyTopoChange/polyTopoChange.cpp
polyTopoChange/polyTopoChange/addPatchCellLayer.cpp
polyTopoChange/polyTopoChange/pointEdgeCollapse/pointEdgeCollapse.cpp
polyTopoChange/polyTopoChange/edgeCollapser.cpp
polyTopoChange/polyTopoChange/faceCollapser.cpp
polyTopoChange/polyTopoChange/hexRef8/hexRef8.cpp
polyTopoChange/polyTopoChange/hexRef8/hexRef8Data.cpp
polyTopoChange/polyTopoChange/removeCells.cpp
polyTopoChange/polyTopoChange/removeFaces.cpp
polyTopoChange/polyTopoChange/refinementData.cpp
polyTopoChange/polyTopoChange/refinementDistanceData.cpp
polyTopoChange/polyTopoChange/hexRef8/refinementHistory.cpp
polyTopoChange/polyTopoChange/removePoints.cpp
polyTopoChange/polyTopoChange/combineFaces.cpp
polyTopoChange/polyTopoChange/localPointRegion.cpp
polyTopoChange/polyTopoChange/duplicatePoints.cpp
slidingInterface/slidingInterface.cpp
slidingInterface/slidingInterfaceProjectPoints.cpp
slidingInterface/coupleSlidingInterface.cpp
slidingInterface/slidingInterfaceAttachedAddressing.cpp
slidingInterface/slidingInterfaceClearCouple.cpp
slidingInterface/decoupleSlidingInterface.cpp
perfectInterface/perfectInterface.cpp
boundaryMesh/boundaryMesh.cpp
boundaryPatch/boundaryPatch.cpp
setUpdater/setUpdater.cpp
meshCut/meshModifiers/boundaryCutter/boundaryCutter.cpp
meshCut/meshModifiers/meshCutter/meshCutter.cpp
meshCut/meshModifiers/meshCutAndRemove/meshCutAndRemove.cpp
meshCut/meshModifiers/undoableMeshCutter/undoableMeshCutter.cpp
meshCut/meshModifiers/refinementIterator/refinementIterator.cpp
meshCut/meshModifiers/multiDirRefinement/multiDirRefinement.cpp
meshCut/cellLooper/cellLooper.cpp
meshCut/cellLooper/topoCellLooper.cpp
meshCut/cellLooper/geomCellLooper.cpp
meshCut/cellLooper/hexCellLooper.cpp
meshCut/directions/directions.cpp
meshCut/directions/directionInfo/directionInfo.cpp
meshCut/edgeVertex/edgeVertex.cpp
meshCut/cellCuts/cellCuts.cpp
meshCut/splitCell/splitCell.cpp
meshCut/refineCell/refineCell.cpp
meshCut/wallLayerCells/wallLayerCells.cpp
meshCut/wallLayerCells/wallNormalInfo/wallNormalInfo.cpp
polyTopoChange/attachPolyTopoChanger/attachPolyTopoChanger.cpp
polyTopoChange/repatchPolyTopoChanger/repatchPolyTopoChanger.cpp
fvMeshAdder/fvMeshAdder.cpp
fvMeshDistribute/fvMeshDistribute.cpp
fvMeshDistribute/IOmapDistributePolyMesh.cpp
fvMeshSubset/fvMeshSubset.cpp
polyMeshAdder/faceCoupleInfo.cpp
polyMeshAdder/polyMeshAdder.cpp
fvMeshTools/fvMeshTools.cpp
motionSmoother/motionSmoother.cpp
motionSmoother/motionSmootherCheck.cpp
motionSmoother/polyMeshGeometry/polyMeshGeometry.cpp
motionSolver/motionSolver/motionSolver.cpp
motionSolver/displacement/displacementMotionSolver.cpp
motionSolver/componentDisplacement/componentDisplacementMotionSolver.cpp
motionSolver/velocity/velocityMotionSolver.cpp
motionSolver/componentVelocity/componentVelocityMotionSolver.cpp
pointPatchDist/externalPointEdgePoint.cpp
pointPatchDist/pointPatchDist.cpp
createShellMesh/createShellMesh.cpp
extrudePatchMesh/extrudePatchMesh.cpp
""")

caelus_inc = [
'mesh/extrudeModel/lnInclude'
]

caelus_libs = [
'core',
'extrudeModel'
]

build_lib(env,
          target=target,
          sources=sources,
          caelus_inc=caelus_inc,
          caelus_libs=caelus_libs)
