#Copyright (C) 2014 Applied CCM
import subprocess
Import('globalEnv')

# Clone the global environment so changes made he are not pass onto subsequent 
# libraries
patchSummaryEnv = globalEnv.Clone()

# Path to source
src = patchSummaryEnv['LIB_SRC']

#===============================================================================
# Additions to compiler flags for this executable
#===============================================================================
patchSummaryEnv.Append(CCFLAGS = '')

#===============================================================================
# Additions to include directories for this executable
#===============================================================================
lib_inc = []
patchSummaryEnv.Prepend(CPPPATH = lib_inc)

#===============================================================================
# Additions to link library paths for this executable
#===============================================================================
lib_link_path = []
patchSummaryEnv.Prepend(LIBPATH = lib_link_path)

#===============================================================================
# Additions to link libraries for this executable
#===============================================================================
if patchSummaryEnv['WHICH_OS'] == "windows":
  patchSummaryEnv.Prepend(LINKFLAGS = ' -u genericPatchFieldsLoad')

lib_link = ['genericPatchFields']
     

patchSummaryEnv.Append(LIBS = lib_link)

#===============================================================================
# Sources for this executable
#===============================================================================
src_files = Split("""
  patchSummary.cpp
  """)

#===============================================================================
# Build this executable
#===============================================================================
binpatchSummary = patchSummaryEnv.Program(target = 'patchSummary', 
source = src_files)

#===============================================================================
# Install this executable
#===============================================================================
install_dir = patchSummaryEnv['BIN_PLATFORM_INSTALL']
patchSummaryEnv.Alias('install', install_dir)
patchSummaryEnv.Install(install_dir, binpatchSummary)
