# -*- mode: python -*-

import utils
from build import build_app
Import('env')

target = 'redistributePar'

sources = Split("""
passivePositionParticleCloud.cpp
redistributePar.cpp
parLagrangianRedistributor.cpp
parFvFieldReconstructor.cpp
loadOrCreateMesh.cpp
""")

caelus_inc = [
'dynamicMesh/dynamicMesh/lnInclude',
'parallel/decompose/decompositionMethods/lnInclude',
'lagrangian/basic/lnInclude' 
]

caelus_libs = [
'core',
'decompositionMethods',
'dynamicMesh',
'lagrangian',
'scotchDecomp',
'ptscotchDecomp'
]

ostype = utils.ostype()
prepend_args = {}
if ostype == 'windows':
   prepend_args = {'LINKFLAGS' :
         '-u genericPatchFieldsLoad'
}

build_app(env,
          target=target,
          sources=sources,
          caelus_inc=caelus_inc,
          caelus_libs=caelus_libs,
          prepend_args=prepend_args)
