#Copyright (C) 2014 Applied CCM
import subprocess
Import('globalEnv')

# Clone the global environment so changes made he are not pass onto subsequent 
# libraries
redistributeParEnv = globalEnv.Clone()

# Path to source
src = redistributeParEnv['LIB_SRC']

#===============================================================================
# Additions to compiler flags for this executable
#===============================================================================
redistributeParEnv.Append(CCFLAGS = '')

#===============================================================================
# Additions to include directories for this executable
#===============================================================================
lib_inc = [src + '/dynamicMesh/lnInclude', src + '/parallel/decompose' + 
'/decompositionMethods/lnInclude'
]
redistributeParEnv.Prepend(CPPPATH = lib_inc)

#===============================================================================
# Additions to link library paths for this executable
#===============================================================================
lib_link_path = []
redistributeParEnv.Prepend(LIBPATH = lib_link_path)

#===============================================================================
# Additions to link libraries for this executable
#===============================================================================
if redistributeParEnv['WHICH_OS'] == "windows":
  redistributeParEnv.Prepend(LINKFLAGS = ' -u genericPatchFieldsLoad')
  lib_link = ['libgenericPatchFields','libdecompositionMethods','libdynamicMesh']
else:
  lib_link = ['genericPatchFields','decompositionMethods','dynamicMesh']
  
redistributeParEnv.Append(LIBS = lib_link)

#===============================================================================
# Sources for this executable
#===============================================================================
src_files = Split("""
  redistributePar.cpp
  """)

#===============================================================================
# Build this executable
#===============================================================================
binredistributePar = redistributeParEnv.Program(target = 'redistributePar', source = src_files)

#===============================================================================
# Install this executable
#===============================================================================
install_dir = redistributeParEnv['BIN_PLATFORM_INSTALL']
redistributeParEnv.Alias('install', install_dir)
redistributeParEnv.Install(install_dir, binredistributePar)
