# -*- mode: python -*-

from build import build_lib
Import('env')

target = 'pyrolysisModels'

sources = Split("""
pyrolysisModel/pyrolysisModel.cpp
pyrolysisModel/pyrolysisModelNew.cpp
reactingOneDim/reactingOneDim.cpp
noPyrolysis/noPyrolysis.cpp
 pyrolysisModel/pyrolysisModelCollection.cpp
""")

caelus_inc = [
'thermophysicalModels/chemistryModel/lnInclude',
'thermophysicalModels/specie/lnInclude',
'thermophysicalModels/basic/lnInclude',
'thermophysicalModels/solidThermo/lnInclude',
'thermophysicalModels/solidChemistryModel/lnInclude',
'thermophysicalModels/reactionThermo/lnInclude',
'thermophysicalModels/radiation/lnInclude',
'turbulenceModels',
'turbulenceModels/compressible/turbulenceModel/lnInclude',
'turbulenceModels/compressible/LES/lnInclude',
'turbulenceModels/compressible/RAS/lnInclude',
'turbulenceModels/LES/LESdeltas/lnInclude',
'regionModels/regionModel/lnInclude'
]

caelus_libs = [
'core',
'chemistryModel',
'specie',
'fluidThermophysicalModels',
'solidChemistryModel',
'solidThermo',
'compressibleTurbulenceModel',
'compressibleRASModels',
'compressibleLESModels',
'LESdeltas',
'regionModels',
'radiationModels',
'reactionThermophysicalModels'
]

build_lib(env,
          target=target,
          sources=sources,
          caelus_inc=caelus_inc,
          caelus_libs=caelus_libs)
