#Copyright (C) 2014 Applied CCM
import subprocess
Import('globalEnv')

# Clone the global environment so changes made he are not pass onto subsequent 
# libraries
singleCellMeshEnv = globalEnv.Clone()

# Path to source
src = singleCellMeshEnv ['LIB_SRC']

singleCellMeshEnv.Append(CXXFLAGS = '')
#===============================================================================
# Additions to compiler flags for this executable
#===============================================================================
singleCellMeshEnv.Append(CCFLAGS = '')

#===============================================================================
# Additions to include directories for this executable
#===============================================================================
lib_inc = []

singleCellMeshEnv.Prepend(CPPPATH = lib_inc)

#===============================================================================
# Additions to link library paths for this executable
#===============================================================================
lib_link_path = []
singleCellMeshEnv.Prepend(LIBPATH = lib_link_path)

#===============================================================================
# Additions to link libraries for this executable
#===============================================================================
lib_link = []
  
singleCellMeshEnv.Append(LIBS = lib_link)

#===============================================================================
# Sources for this executable
#===============================================================================
src_files = Split("""
  singleCellMesh.cpp
  """)

#===============================================================================
# Build this executable
#===============================================================================
binsingleCellMesh = singleCellMeshEnv.Program(target = 
'singleCellMesh', source = src_files)

#===============================================================================
# Install this executable
#===============================================================================
install_dir = singleCellMeshEnv['BIN_PLATFORM_INSTALL']
singleCellMeshEnv.Alias('install', install_dir)
singleCellMeshEnv.Install(install_dir, binsingleCellMesh)
