# -*- mode: python -*-

from build import build_app
Import('env')

target = 'checkMesh'

sources = Split("""
checkMesh.cpp
checkGeometry.cpp
checkTopology.cpp
printMeshStats.cpp
""")

caelus_inc = [
]

caelus_libs = [
'core'
]

build_app(env,
          target=target,
          sources=sources,
          caelus_inc=caelus_inc,
          caelus_libs=caelus_libs)
