# -*- mode: python -*-

from build import build_app
Import('env')

target = 'checkMesh'

sources = Split("""
checkMesh.cpp
checkMeshQuality.cpp
checkGeometry.cpp
checkTopology.cpp
checkTools.cpp
writeFields.cpp
""")

caelus_inc = [
'dynamicMesh/dynamicMesh/lnInclude',
'surfMesh/lnInclude',
'sampling/lnInclude'
]

caelus_libs = [
'core',
'dynamicMesh',
'sampling'
]

build_app(env,
          target=target,
          sources=sources,
          caelus_inc=caelus_inc,
          caelus_libs=caelus_libs)
