#Copyright (C) 2014 Applied CCM
import subprocess
Import('globalEnv')

# Clone the global environment so changes made he are not pass onto subsequent 
# libraries
checkMeshEnv = globalEnv.Clone()

# Path to source
src = checkMeshEnv['LIB_SRC']

#===============================================================================
# Additions to compiler flags for this executable
#===============================================================================
checkMeshEnv.Append(CCFLAGS = '')

#===============================================================================
# Additions to include directories for this executable
#===============================================================================
lib_inc = []

checkMeshEnv.Prepend(CPPPATH = lib_inc)

#===============================================================================
# Additions to link library paths for this executable
#===============================================================================
lib_link_path = []
checkMeshEnv.Prepend(LIBPATH = lib_link_path)

#===============================================================================
# Additions to link libraries for this executable
#===============================================================================
if checkMeshEnv['WHICH_OS'] == "windows":
  lib_link = []
else:
  lib_link = []
  
checkMeshEnv.Append(LIBS = lib_link)

#===============================================================================
# Sources for this executable
#===============================================================================
src_files = Split("""
  checkMesh.cpp
  checkGeometry.cpp
  checkTopology.cpp
  printMeshStats.cpp
  """)

#===============================================================================
# Build this executable
#===============================================================================
bincheckMesh = checkMeshEnv.Program(target = 'checkMesh', source = src_files)

#===============================================================================
# Install this executable
#===============================================================================
install_dir = checkMeshEnv['BIN_PLATFORM_INSTALL']
checkMeshEnv.Alias('install', install_dir)
checkMeshEnv.Install(install_dir, bincheckMesh)
