# -*- mode: python -*-

from build import build_lib
Import('env')

target = 'solid'

sources = Split("""
rhoType/const/constRho.cpp
reaction/Reactions_/solidReaction/solidReaction.cpp
reaction/reactions/makeSolidReactionThermoReactions.cpp
""")

caelus_inc = [
'thermophysicalModels/specie/lnInclude'
]

caelus_libs = [
'core'
]

build_lib(env,
          target=target,
          sources=sources,
          caelus_inc=caelus_inc,
          caelus_libs=caelus_libs)
