#Copyright (C) 2014 Applied CCM
import subprocess
Import('globalEnv')

# Clone the global environment so changes made he are not pass onto subsequent 
# libraries
autoRefineMeshEnv = globalEnv.Clone()

# Path to source
src = autoRefineMeshEnv['LIB_SRC']

#===============================================================================
# Additions to compiler flags for this executable
#===============================================================================
autoRefineMeshEnv.Append(CCFLAGS = '')

#===============================================================================
# Additions to include directories for this executable
#===============================================================================
lib_inc = [src + '/dynamicMesh/lnInclude', src + '/lagrangian/basic/lnInclude']
autoRefineMeshEnv.Prepend(CPPPATH = lib_inc)

#===============================================================================
# Additions to link library paths for this executable
#===============================================================================
lib_link_path = []
autoRefineMeshEnv.Prepend(LIBPATH = lib_link_path)

#===============================================================================
# Additions to link libraries for this executable
#===============================================================================
if autoRefineMeshEnv['WHICH_OS'] == "windows":
  lib_link = ['libdynamicMesh','liblagrangian']
else:
  lib_link = ['dynamicMesh','lagrangian']
     

autoRefineMeshEnv.Append(LIBS = lib_link)

#===============================================================================
# Sources for this executable
#===============================================================================
src_files = Split("""
  autoRefineMesh.cpp
  """)

#===============================================================================
# Build this executable
#===============================================================================
binautoRefineMesh = autoRefineMeshEnv.Program(target = 'autoRefineMesh', 
source = src_files)

#===============================================================================
# Install this executable
#===============================================================================
install_dir = autoRefineMeshEnv['BIN_PLATFORM_INSTALL']
autoRefineMeshEnv.Alias('install', install_dir)
autoRefineMeshEnv.Install(install_dir, binautoRefineMesh)
