# -*- mode: python -*-

from build import build_lib
Import('env')

target = 'edgeMesh'

sources = Split("""
edgeMesh.cpp
edgeMeshIO.cpp
edgeMeshNew.cpp
edgeFormats/edgeFormatsCore.cpp
edgeFormats/emesh/EMESHedgeFormat.cpp
edgeFormats/emesh/EMESHedgeFormatRunTime.cpp
edgeFormats/nas/NASedgeFormat.cpp
edgeFormats/nas/NASedgeFormatRunTime.cpp
edgeFormats/obj/OBJedgeFormat.cpp
edgeFormats/obj/OBJedgeFormatRunTime.cpp
edgeFormats/starcd/STARCDedgeFormat.cpp
edgeFormats/starcd/STARCDedgeFormatRunTime.cpp
edgeFormats/vtk/VTKedgeFormat.cpp
edgeFormats/vtk/VTKedgeFormatRunTime.cpp
extendedFeatureEdgeMesh/extendedFeatureEdgeMesh.cpp
featureEdgeMesh/featureEdgeMesh.cpp
""")

caelus_inc = []

caelus_libs = [
'core'
]

build_lib(env,
          target=target,
          sources=sources,
          caelus_inc=caelus_inc,
          caelus_libs=caelus_libs)
