#Copyright (C) 2014 Applied CCM
import subprocess
Import('globalEnv')

# Clone the global environment so changes made he are not pass onto subsequent 
# libraries
edgeMeshEnv = globalEnv.Clone()

# Path to source
src = edgeMeshEnv['LIB_SRC']

#===============================================================================
# Additions to compiler flags for this library
#===============================================================================
edgeMeshEnv.Append(CXXFLAGS = '')

#===============================================================================
# Additions to include directories for this library
#===============================================================================
lib_inc = ['lnInclude']
edgeMeshEnv.Prepend(CPPPATH = lib_inc)

#===============================================================================
# Additions to link library paths for this library
#===============================================================================
lib_link_path = []
edgeMeshEnv.Prepend(LIBPATH = lib_link_path)

#===============================================================================
# Additions to link libraries for this library
#===============================================================================
lib_link = ['core']
edgeMeshEnv.Append(LIBS = lib_link)

#===============================================================================
# Sources for this library
#===============================================================================
src_files = Split("""
  edgeMesh.cpp
  edgeMeshIO.cpp
  edgeMeshNew.cpp
  edgeFormats/edgeFormatsCore.cpp
  edgeFormats/emesh/EMESHedgeFormat.cpp
  edgeFormats/emesh/EMESHedgeFormatRunTime.cpp
  edgeFormats/nas/NASedgeFormat.cpp
  edgeFormats/nas/NASedgeFormatRunTime.cpp
  edgeFormats/obj/OBJedgeFormat.cpp
  edgeFormats/obj/OBJedgeFormatRunTime.cpp
  edgeFormats/starcd/STARCDedgeFormat.cpp
  edgeFormats/starcd/STARCDedgeFormatRunTime.cpp
  edgeFormats/vtk/VTKedgeFormat.cpp
  edgeFormats/vtk/VTKedgeFormatRunTime.cpp
  extendedFeatureEdgeMesh/extendedFeatureEdgeMesh.cpp
  featureEdgeMesh/featureEdgeMesh.cpp
  """)

#===============================================================================
# Build this library
#===============================================================================
libedgeMesh = edgeMeshEnv.SharedLibrary(target = 'edgeMesh', 
  source = src_files)

#===============================================================================
# Install this library
#===============================================================================
install_dir = edgeMeshEnv['LIB_PLATFORM_INSTALL']
edgeMeshEnv.Alias('install', install_dir)
edgeMeshEnv.Install(install_dir, libedgeMesh)

if (edgeMeshEnv['WHICH_OS'] == "darwin"):

  edgeMeshEnv.Append(SHLINKFLAGS ='-install_name @executable_path/../lib/libedgeMesh.dylib')
