# -*- mode: python -*-

from build import build_lib
Import('env')

target = 'solidMixtureProperties'

sources = Split("""
solidMixtureProperties/solidMixtureProperties.cpp
""")

caelus_inc = [
'thermophysicalModels/specie/lnInclude',
'thermophysicalModels/properties/solidProperties/lnInclude'
]

caelus_libs = [
'core',
'solidProperties'
]

build_lib(env,
          target=target,
          sources=sources,
          caelus_inc=caelus_inc,
          caelus_libs=caelus_libs)
