#Copyright (C) 2014 Applied CCM
import subprocess
Import('globalEnv')

# Clone the global environment so changes made he are not pass onto subsequent 
# libraries
caelusFormatConvertEnv = globalEnv.Clone()

sl = caelusFormatConvertEnv['SLASH']

caelusFormatConvertEnv.Append(CXXFLAGS = '-Dutil_EXPORTS')
#===============================================================================
# Additions to compiler flags for this executable
#===============================================================================
caelusFormatConvertEnv.Append(CCFLAGS = '')

#===============================================================================
# Additions to include directories for this executable
#===============================================================================
lib_inc = [caelusFormatConvertEnv['LIB_SRC'] + sl + 'lagrangian' + sl +'lnInclude'
]
caelusFormatConvertEnv.Prepend(CPPPATH = lib_inc)

#===============================================================================
# Additions to link library paths for this executable
#===============================================================================
lib_link_path = []
caelusFormatConvertEnv.Prepend(LIBPATH = lib_link_path)

#===============================================================================
# Additions to link libraries for this executable
#===============================================================================
if caelusFormatConvertEnv['WHICH_OS'] == "windows":
  caelusFormatConvertEnv.Prepend(LINKFLAGS = ' -u genericPatchFieldsLoad')
  lib_link = ['libgenericPatchFields','liblagrangian']
else:
  lib_link = ['genericPatchFields','lagrangian']
     

caelusFormatConvertEnv.Append(LIBS = lib_link)

#===============================================================================
# Sources for this executable
#===============================================================================
src_files = Split("""
  caelusFormatConvert.cpp
  """)

#===============================================================================
# Build this executable
#===============================================================================
bincaelusFormatConvert = caelusFormatConvertEnv.Program(target =
'caelusFormatConvert', source = src_files)

#===============================================================================
# Install this executable
#===============================================================================
install_dir = caelusFormatConvertEnv['BIN_PLATFORM_INSTALL']
caelusFormatConvertEnv.Alias('install', install_dir)
caelusFormatConvertEnv.Install(install_dir, bincaelusFormatConvert)
