# -*- mode: python -*-

import os
import utils
from build import process_lninclude
Import('env')

subdirs = Split("""
    core
    edgeMesh
    surfMesh
    lagrangian/basic
    lagrangian/distributionModels
    parallel/decompose/decompose
    parallel/decompose/decompositionMethods
    parallel/decompose/scotchDecomp
    parallel/decompose/ptscotchDecomp
    parallel/decompose/metisDecomp
    parallel/reconstruct/reconstruct
    parallel/distributed
    conversion
    sampling
    dynamicMesh/dynamicMesh
    dynamicMesh/dynamicFvMesh
    dynamicMesh/topoChangerFvMesh
    dynamicMesh/meshMotion/fvMotionSolver
    dynamicMesh/meshMotion/RBFMotionSolver
    dynamicMesh/meshMotion/solidBodyMotion/solidBodyMotionFunctions
    ODE
    randomProcesses
    thermophysicalModels/specie
    thermophysicalModels/solid
    thermophysicalModels/thermophysicalFunctions
    thermophysicalModels/properties/liquidProperties
    thermophysicalModels/properties/liquidMixtureProperties
    thermophysicalModels/properties/solidProperties
    thermophysicalModels/properties/solidMixtureProperties
    thermophysicalModels/basic
    thermophysicalModels/reactionThermo
    thermophysicalModels/laminarFlameSpeed
    thermophysicalModels/chemistryModel
    thermophysicalModels/barotropicCompressibilityModel
    thermophysicalModels/SLGThermo
    thermophysicalModels/basicSolidThermo
    thermophysicalModels/solidChemistryModel
    thermophysicalModels/radiationModels
    thermophysicalModels/numericFluxes/DBNS/numericFlux
    transportModels/incompressible
    transportModels/interfaceProperties
    transportModels/twoPhaseInterfaceProperties
    turbulenceModels/LES/LESfilters
    turbulenceModels/LES/LESdeltas
    turbulenceModels/incompressible/turbulenceModel
    turbulenceModels/incompressible/RAS
    turbulenceModels/incompressible/LES
    turbulenceModels/incompressible/VLES
    turbulenceModels/compressible/turbulenceModel
    turbulenceModels/compressible/RAS
    turbulenceModels/compressible/LES
    turbulenceModels/compressible/VLES
    turbulenceModels/derivedFvPatchFields
    combustionModels
    regionModels/regionModel
    regionModels/pyrolysisModels
    regionModels/surfaceFilmModels
    regionModels/thermoBaffleModels
    regionModels/regionCoupling
    lagrangian/solidParticle
    lagrangian/intermediate
    lagrangian/spray
    lagrangian/coalCombustion
    postProcessing/postCalc
    postProcessing/CAELUSCalcFunctions
    postProcessing/functionObjects/cloud
    postProcessing/functionObjects/field
    postProcessing/functionObjects/forces
    postProcessing/functionObjects/fvTools
    postProcessing/functionObjects/IO
    postProcessing/functionObjects/utilities
    postProcessing/functionObjects/jobControl
    postProcessing/functionObjects/systemCall
    mesh/autoMesh
    mesh/blockMesh
    fvAgglomerationMethods/pairPatchAgglomeration
    dynamicMesh/meshMotion/rigidBodyDynamics
    dynamicMesh/meshMotion/rigidBodyMeshMotion
    dynamicMesh/meshMotion/rigidBodyMeshMotionSolver
    fvOptions
    waves/waves
    waves/wavesPorosity
    waves/wavesProcessing
    waves/wavesSampling
""")

for d in subdirs:
    lninclude = list(process_lninclude(env, d))
    SConscript(os.path.join(d,'SConscript'),
               exports=['env','lninclude'])
