# -*- mode: python -*-

from build import build_lib
Import('env')

target = 'thermophysicalFunctions'

sources = Split("""
thermophysicalFunction/thermophysicalFunction.cpp
NSRDSfunctions/NSRDSfunc0/NSRDSfunc0.cpp
NSRDSfunctions/NSRDSfunc1/NSRDSfunc1.cpp
NSRDSfunctions/NSRDSfunc2/NSRDSfunc2.cpp
NSRDSfunctions/NSRDSfunc3/NSRDSfunc3.cpp
NSRDSfunctions/NSRDSfunc4/NSRDSfunc4.cpp
NSRDSfunctions/NSRDSfunc5/NSRDSfunc5.cpp
NSRDSfunctions/NSRDSfunc6/NSRDSfunc6.cpp
NSRDSfunctions/NSRDSfunc7/NSRDSfunc7.cpp
NSRDSfunctions/NSRDSfunc14/NSRDSfunc14.cpp
APIfunctions/APIdiffCoefFunc/APIdiffCoefFunc.cpp
""")

caelus_inc = []

caelus_libs = [
'core'
]

build_lib(env,
          target=target,
          sources=sources,
          caelus_inc=caelus_inc,
          caelus_libs=caelus_libs)
