# -*- mode: python -*-

from build import build_lib
Import('env')

target = 'surfaceFilmModels'

sources = Split("""
surfaceFilmModel/surfaceFilmModel.cpp
surfaceFilmModel/surfaceFilmModelNew.cpp
noFilm/noFilm.cpp
kinematicSingleLayer/kinematicSingleLayer.cpp
thermoSingleLayer/thermoSingleLayer.cpp
submodels/filmSubModelBase.cpp
submodels/kinematic/force/force/force.cpp
submodels/kinematic/force/force/forceNew.cpp
submodels/kinematic/force/forceList/forceList.cpp
submodels/kinematic/force/contactAngleForce/contactAngleForce.cpp
submodels/kinematic/force/surfaceShearForce/surfaceShearForce.cpp
submodels/kinematic/force/thermocapillaryForce/thermocapillaryForce.cpp
submodels/kinematic/injectionModel/injectionModel/injectionModel.cpp
submodels/kinematic/injectionModel/injectionModel/injectionModelNew.cpp
submodels/kinematic/injectionModel/injectionModelList/injectionModelList.cpp
submodels/kinematic/injectionModel/drippingInjection/drippingInjection.cpp
submodels/kinematic/injectionModel/removeInjection/removeInjection.cpp
submodels/kinematic/injectionModel/curvatureSeparation/curvatureSeparation.cpp
submodels/thermo/phaseChangeModel/phaseChangeModel/phaseChangeModel.cpp
submodels/thermo/phaseChangeModel/phaseChangeModel/phaseChangeModelNew.cpp
submodels/thermo/phaseChangeModel/noPhaseChange/noPhaseChange.cpp
submodels/thermo/phaseChangeModel/standardPhaseChange/standardPhaseChange.cpp
submodels/thermo/heatTransferModel/heatTransferModel/heatTransferModel.cpp
submodels/thermo/heatTransferModel/heatTransferModel/heatTransferModelNew.cpp
submodels/thermo/heatTransferModel/constantHeatTransfer/constantHeatTransfer.cpp
submodels/thermo/heatTransferModel/mappedConvectiveHeatTransfer/mappedConvectiveHeatTransfer.cpp
submodels/thermo/filmRadiationModel/filmRadiationModel/filmRadiationModel.cpp
submodels/thermo/filmRadiationModel/filmRadiationModel/filmRadiationModelNew.cpp
submodels/thermo/filmRadiationModel/noRadiation/noRadiation.cpp
submodels/thermo/filmRadiationModel/standardRadiation/standardRadiation.cpp
derivedFvPatchFields/filmHeightInletVelocity/filmHeightInletVelocityFvPatchVectorField.cpp
derivedFvPatchFields/wallFunctions/alphatFilmWF/alphatFilmWFFvPatchScalarField.cpp
derivedFvPatchFields/wallFunctions/mutkFilmWF/mutkFilmWFFvPatchScalarField.cpp
""")

caelus_inc = [
'turbulenceModels',
'thermophysicalModels/basic/lnInclude',
'thermophysicalModels/specie/lnInclude',
'thermophysicalModels/reactionThermo/lnInclude',
'thermophysicalModels/SLGThermo/lnInclude',
'thermophysicalModels/properties/liquidProperties/lnInclude',
'thermophysicalModels/properties/liquidMixtureProperties/lnInclude',
'thermophysicalModels/properties/solidProperties/lnInclude',
'thermophysicalModels/properties/solidMixtureProperties/lnInclude',
'turbulenceModels/compressible/turbulenceModel/lnInclude',
'turbulenceModels/compressible/LES/lnInclude',
'turbulenceModels/compressible/RAS/lnInclude',
'regionModels/regionModel/lnInclude',
'lagrangian/distributionModels/lnInclude'
]

caelus_libs = [
'core',
'basicThermophysicalModels',
'specie',
'liquidProperties',
'liquidMixtureProperties',
'solidProperties',
'solidMixtureProperties',
'reactionThermophysicalModels',
'SLGThermo',
'distributionModels',
'compressibleTurbulenceModel',
'compressibleRASModels',
'compressibleLESModels',
'regionModels'
]

build_lib(env,
          target=target,
          sources=sources,
          caelus_inc=caelus_inc,
          caelus_libs=caelus_libs)
