#Copyright (C) 2014 Applied CCM
import subprocess
Import('globalEnv')

# Clone the global environment so changes made he are not pass onto subsequent 
# libraries
refineMeshEnv = globalEnv.Clone()

# Path to source
src = refineMeshEnv['LIB_SRC']

refineMeshEnv.Append(CXXFLAGS = '')
#===============================================================================
# Additions to compiler flags for this executable
#===============================================================================
refineMeshEnv.Append(CCFLAGS = '')

#===============================================================================
# Additions to include directories for this executable
#===============================================================================
lib_inc = [src + '/dynamicMesh/lnInclude']
refineMeshEnv.Prepend(CPPPATH = lib_inc)

#===============================================================================
# Additions to link library paths for this executable
#===============================================================================
lib_link_path = []
refineMeshEnv.Prepend(LIBPATH = lib_link_path)

#===============================================================================
# Additions to link libraries for this executable
#===============================================================================
if refineMeshEnv['WHICH_OS'] == "windows":
  lib_link = ['libdynamicMesh']
else:
  lib_link = ['dynamicMesh']
  
refineMeshEnv.Append(LIBS = lib_link)

#===============================================================================
# Sources for this executable
#===============================================================================
src_files = Split("""
  refineMesh.cpp
  """)

#===============================================================================
# Build this executable
#===============================================================================
binrefineMesh = refineMeshEnv.Program(target = 
'refineMesh', source = src_files)

#===============================================================================
# Install this executable
#===============================================================================
install_dir = refineMeshEnv['BIN_PLATFORM_INSTALL']
refineMeshEnv.Alias('install', install_dir)
refineMeshEnv.Install(install_dir, binrefineMesh)
