# -*- mode: python -*-

import os
from build import build_app
Import('env')

target = 'extrudeToRegionMesh'

sources = Split("""
extrudeToRegionMesh.cpp
""")

caelus_inc = [
'dynamicMesh/dynamicMesh/lnInclude',
'mesh/extrudeModel/lnInclude'
]

caelus_libs = [
'core',
'extrudeModel',
'dynamicMesh'
]

local_dir = env.Dir(".").srcnode().abspath
model_dir = os.path.join(local_dir, '../extrudeModel/lnInclude')

append_args = {}
append_args = { 'CPPPATH' : [os.path.normpath(model_dir)] }

build_app(env,
          target=target,
          sources=sources,
          caelus_inc=caelus_inc,
          caelus_libs=caelus_libs,
          append_args=append_args)
