#Copyright (C) 2014 Applied CCM
import subprocess
Import('globalEnv')

# Clone the global environment so changes made he are not pass onto subsequent 
# libraries
thermoSolMixPropEnv = globalEnv.Clone()

# Path to source
src = thermoSolMixPropEnv['LIB_SRC']

#===============================================================================
# Additions to compiler flags for this library
#===============================================================================
thermoSolMixPropEnv.Append(CCFLAGS = '')

#===============================================================================
# Additions to include directories for this library
#===============================================================================
lib_inc = ['lnInclude',
src + '/thermophysicalModels/specie/lnInclude',
src + '/thermophysicalModels/properties/solidProperties/lnInclude'
]
thermoSolMixPropEnv.Prepend(CPPPATH = lib_inc)

#===============================================================================
# Additions to link library paths for this library
#===============================================================================
lib_link_path = []
thermoSolMixPropEnv.Prepend(LIBPATH = lib_link_path)

#===============================================================================
# Additions to link libraries for this library
#===============================================================================
lib_link = ['core','solidProperties']
thermoSolMixPropEnv.Append(LIBS = lib_link)

#===============================================================================
# Sources for this library
#===============================================================================
src_files = Split("""
  solidMixtureProperties/solidMixtureProperties.cpp
  """)

#===============================================================================
# Build this library
#===============================================================================
libsolidMixtureProperties = thermoSolMixPropEnv.SharedLibrary(target = 
'solidMixtureProperties', source = src_files)

#===============================================================================
# Install this library
#===============================================================================
install_dir = thermoSolMixPropEnv['LIB_PLATFORM_INSTALL']
thermoSolMixPropEnv.Alias('install', install_dir)
thermoSolMixPropEnv.Install(install_dir, libsolidMixtureProperties)

if (thermoSolMixPropEnv['WHICH_OS'] == "darwin"):

  thermoSolMixPropEnv.Append(SHLINKFLAGS ='-install_name @executable_path/../lib/libsolidMixtureProperties.dylib')
