#Copyright (C) 2014 Applied CCM
import subprocess
Import('globalEnv')

# Clone the global environment so changes made he are not pass onto subsequent 
# libraries
metisDecompEnv = globalEnv.Clone()

metisDecompEnv.Append(CXXFLAGS = '')
#===============================================================================
# Additions to compiler flags for this library
#===============================================================================
metisDecompEnv.Append(CXXFLAGS = '')

#===============================================================================
# Additions to include directories for this library
#===============================================================================
lib_inc = ['lnInclude', '../decompositionMethods/lnInclude',
metisDecompEnv['METIS_PATH'] + '/include']
metisDecompEnv.Prepend(CPPPATH = lib_inc)

#===============================================================================
# Additions to link library paths for this library
#===============================================================================
lib_link_path = [metisDecompEnv['METIS_PATH']  + '/lib']
metisDecompEnv.Prepend(LIBPATH = lib_link_path)

#===============================================================================
# Additions to link libraries for this library
#===============================================================================
lib_link = ['core','decompositionMethods','metis']
metisDecompEnv.Append(LIBS = lib_link)

#===============================================================================
# Sources for this library
#===============================================================================
src_files = Split("""
  metisDecomp.cpp
  """)

#===============================================================================
# Build this library
#===============================================================================
libmetisDecomp = metisDecompEnv.SharedLibrary(target = 'metisDecomp', 
source = src_files)

#===============================================================================
# Install this library
#===============================================================================
install_dir =metisDecompEnv['LIB_PLATFORM_INSTALL']
metisDecompEnv.Alias('install', install_dir)
metisDecompEnv.Install(install_dir, libmetisDecomp)

if (metisDecompEnv['WHICH_OS'] == "darwin"):

  metisDecompEnv.Append(SHLINKFLAGS ='-install_name @executable_path/../lib/libmetisDecomp.dylib')
