# -*- mode: python -*-

from build import build_lib
Import('env')

target = 'metisDecomp'

sources = Split("""
metisDecomp.cpp
""")

caelus_inc = [
'parallel/decompose/decompositionMethods/lnInclude',
env['METIS_INC_PATH'],
]

caelus_libs = [
'core',
'decompositionMethods',
'metis'
]

append_args = dict(
    LIBPATH=[env[
        'METIS_LIB_PATH']
    ]
)

build_lib(env,
          target=target,
          sources=sources,
          caelus_inc=caelus_inc,
          caelus_libs=caelus_libs,
          append_args=append_args)
