#Copyright (C) 2014 Applied CCM
import subprocess
Import('globalEnv')

# Clone the global environment so changes made he are not pass onto subsequent 
# libraries
insideCellsEnv = globalEnv.Clone()

# Path to source
src = insideCellsEnv['LIB_SRC']

insideCellsEnv.Append(CXXFLAGS = '')
#===============================================================================
# Additions to compiler flags for this executable
#===============================================================================
insideCellsEnv.Append(CCFLAGS = '')

#===============================================================================
# Additions to include directories for this executable
#===============================================================================
lib_inc = []

insideCellsEnv.Prepend(CPPPATH = lib_inc)

#===============================================================================
# Additions to link library paths for this executable
#===============================================================================
lib_link_path = []
insideCellsEnv.Prepend(LIBPATH = lib_link_path)

#===============================================================================
# Additions to link libraries for this executable
#===============================================================================
lib_link = []
  
insideCellsEnv.Append(LIBS = lib_link)

#===============================================================================
# Sources for this executable
#===============================================================================
src_files = Split("""
  insideCells.cpp
  """)

#===============================================================================
# Build this executable
#===============================================================================
bininsideCells = insideCellsEnv.Program(target = 
'insideCells', source = src_files)

#===============================================================================
# Install this executable
#===============================================================================
install_dir = insideCellsEnv['BIN_PLATFORM_INSTALL']
insideCellsEnv.Alias('install', install_dir)
insideCellsEnv.Install(install_dir, bininsideCells)
