#Copyright (C) 2014 Applied CCM
import subprocess
Import('globalEnv')

# Clone the global environment so changes made he are not pass onto subsequent 
# libraries
randProcEnv = globalEnv.Clone()

# Path to source
src = randProcEnv['LIB_SRC']

#===============================================================================
# Additions to compiler flags for this library
#===============================================================================
randProcEnv.Append(CCFLAGS = '')

#===============================================================================
# Additions to include directories for this library
#===============================================================================
lib_inc = ['lnInclude', src + '/sampling/lnInclude']
randProcEnv.Prepend(CPPPATH = lib_inc)

#===============================================================================
# Additions to link library paths for this library
#===============================================================================
lib_link_path = [] 
randProcEnv.Prepend(LIBPATH = lib_link_path)

#===============================================================================
# Additions to link libraries for this library
#===============================================================================
lib_link = ['core', 'sampling'] 
randProcEnv.Append(LIBS = lib_link)

#===============================================================================
# Sources for this library
#===============================================================================
src_files = Split("""
  Kmesh/Kmesh.cpp
  fft/fft.cpp
  fft/fftRenumber.cpp
  fft/calcEk.cpp
  fft/kShellIntegration.cpp
  processes/UOprocess/UOprocess.cpp
  turbulence/turbGen.cpp
  noise/noiseFFT.cpp
  """)

#===============================================================================
# Build this library
#===============================================================================
librandomProcesses = randProcEnv.SharedLibrary(target = 'randomProcesses', 
source = src_files)

#===============================================================================
# Install this library
#===============================================================================
install_dir = randProcEnv['LIB_PLATFORM_INSTALL']
randProcEnv.Alias('install', install_dir)
randProcEnv.Install(install_dir, librandomProcesses)

if (randProcEnv['WHICH_OS'] == "darwin"):

  randProcEnv.Append(SHLINKFLAGS ='-install_name @executable_path/../lib/librandomProcesses.dylib')
