# -*- mode: python -*-

from build import build_lib
Import('env')

target = 'randomProcesses'

sources = Split("""
Kmesh/Kmesh.cpp
fft/fft.cpp
fft/fftRenumber.cpp
fft/calcEk.cpp
fft/kShellIntegration.cpp
processes/UOprocess/UOprocess.cpp
turbulence/turbGen.cpp
noise/noiseFFT.cpp
""")

caelus_inc = []

caelus_libs = [
'core'
]

build_lib(env,
          target=target,
          sources=sources,
          caelus_inc=caelus_inc,
          caelus_libs=caelus_libs)
