#Copyright (C) 2014 Applied CCM
import subprocess
Import('globalEnv')

# Clone the global environment so changes made he are not pass onto subsequent 
# libraries
objToVTKEnv = globalEnv.Clone()

# Path to source
src = objToVTKEnv['LIB_SRC']

objToVTKEnv.Append(CXXFLAGS = '')
#===============================================================================
# Additions to compiler flags for this executable
#===============================================================================
objToVTKEnv.Append(CCFLAGS = '')

#===============================================================================
# Additions to include directories for this executable
#===============================================================================
lib_inc = []

objToVTKEnv.Prepend(CPPPATH = lib_inc)

#===============================================================================
# Additions to link library paths for this executable
#===============================================================================
lib_link_path = []
objToVTKEnv.Prepend(LIBPATH = lib_link_path)

#===============================================================================
# Additions to link libraries for this executable
#===============================================================================
if objToVTKEnv['WHICH_OS'] == "windows":
  lib_link = []
else:
  lib_link = []
  
objToVTKEnv.Append(LIBS = lib_link)

#===============================================================================
# Sources for this executable
#===============================================================================
src_files = Split("""
  objToVTK.cpp
  """)

#===============================================================================
# Build this executable
#===============================================================================
binobjToVTK = objToVTKEnv.Program(target = 
'objToVTK', source = src_files)

#===============================================================================
# Install this executable
#===============================================================================
install_dir = objToVTKEnv['BIN_PLATFORM_INSTALL']
objToVTKEnv.Alias('install', install_dir)
objToVTKEnv.Install(install_dir, binobjToVTK)
