#Copyright (C) 2014 Applied CCM
import subprocess
Import('globalEnv')

# Clone the global environment so changes made he are not pass onto subsequent 
# libraries
funcObjUtilEnv = globalEnv.Clone()

sl = funcObjUtilEnv['SLASH']

#===============================================================================
# Additions to compiler flags for this library
#===============================================================================
funcObjUtilEnv.Append(CCFLAGS = '')

#===============================================================================
# Additions to include directories for this library
#===============================================================================
lib_inc = ['lnInclude',
funcObjUtilEnv['LIB_SRC'] + '/sampling/lnInclude',
funcObjUtilEnv['LIB_SRC'] + '/lagrangian/basic/lnInclude',
funcObjUtilEnv['LIB_SRC'] + '/lagrangian/dsmc/lnInclude'
]
funcObjUtilEnv.Prepend(CPPPATH = lib_inc)

#===============================================================================
# Additions to link library paths for this library
#===============================================================================
lib_link_path = []
funcObjUtilEnv.Prepend(LIBPATH = lib_link_path)

#===============================================================================
# Additions to link libraries for this library
#===============================================================================
lib_link = ['core','sampling','lagrangian']
funcObjUtilEnv.Append(LIBS = lib_link)
   
#===============================================================================
# Sources for this library
#===============================================================================
src_files = Split("""
  staticPressure/staticPressure.cpp
  staticPressure/staticPressureFunctionObject.cpp
  timeActivatedFileUpdate/timeActivatedFileUpdate.cpp
  timeActivatedFileUpdate/timeActivatedFileUpdateFunctionObject.cpp
  """)

#===============================================================================
# Build this library
#===============================================================================
libutilityFunctionObjects = funcObjUtilEnv.SharedLibrary(target = 
'utilityFunctionObjects', source = src_files)

#============================================================================================
# Install this library
#============================================================================================
install_dir = funcObjUtilEnv['LIB_PLATFORM_INSTALL']
funcObjUtilEnv.Alias('install', install_dir)
funcObjUtilEnv.Install(install_dir, libutilityFunctionObjects)
