# -*- mode: python -*-

from build import build_lib
Import('env')

target = 'utilityFunctionObjects'

sources = Split("""
CourantNo/CourantNo_fo.cpp
CourantNo/CourantNoFunctionObject.cpp
Lambda2/Lambda2.cpp
Lambda2/Lambda2FunctionObject.cpp
Peclet/Peclet.cpp
Peclet/PecletFunctionObject.cpp
Q/Q.cpp
Q/QFunctionObject.cpp
pressureTools/pressureTools.cpp
pressureTools/pressureToolsFunctionObject.cpp
residuals/residuals.cpp
residuals/residualsFunctionObject.cpp
scalarTransport/scalarTransport.cpp
scalarTransport/scalarTransportFunctionObject.cpp
timeActivatedFileUpdate/timeActivatedFileUpdate.cpp
timeActivatedFileUpdate/timeActivatedFileUpdateFunctionObject.cpp
turbulenceFields/turbulenceFields.cpp
turbulenceFields/turbulenceFieldsFunctionObject.cpp
vorticity/vorticity.cpp
vorticity/vorticityFunctionObject.cpp
wallShearStress/wallShearStress.cpp
wallShearStress/wallShearStressFunctionObject.cpp
yPlusLES/yPlusLES.cpp
yPlusLES/yPlusLESFunctionObject.cpp
yPlusRAS/yPlusRAS.cpp
yPlusRAS/yPlusRASFunctionObject.cpp
setTimeStep/setTimeStepFunctionObject.cpp
""")

caelus_inc = [
'sampling/lnInclude',
'fvOptions/lnInclude',
'lagrangian/basic/lnInclude',
'lagrangian/dsmc/lnInclude',
'transportModels/lnInclude',
'transportModels/',
'turbulenceModels/',
'turbulenceModels/lnInclude',
'turbulenceModels/incompressible/turbulenceModel/derivedFvPatchFields/wallFunctions/nutWFs',
'turbulenceModels/compressible/turbulenceModel/derivedFvPatchFields/wallFunctions/mutWFs',
'turbulenceModels/LES/LESdeltas/lnInclude',
'thermophysicalModels/basic/lnInclude'
]

caelus_libs = [
'core',
'sampling',
'fvOptions',
'lagrangian',
'incompressibleTransportModels',
'incompressibleRASModels',
'incompressibleVLESModels',
'incompressibleLESModels',
'compressibleRASModels',
'compressibleVLESModels',
'compressibleLESModels',
'fluidThermophysicalModels',
'incompressibleTurbulenceModel',
'compressibleTurbulenceModel'
]

build_lib(env,
          target=target,
          sources=sources,
          caelus_inc=caelus_inc,
          caelus_libs=caelus_libs)
