# -*- mode: python -*-

from build import build_lib
Import('env')

target = 'cloudFunctionObjects'

sources = Split("""
cloudInfo/cloudInfo.cpp
cloudInfo/cloudInfoFunctionObject.cpp
""")

caelus_inc = [
'lagrangian/lnInclude',
'lagrangian/intermediate/lnInclude'
]

caelus_libs = [
'core',
'lagrangian',
'lagrangianIntermediate'
]

build_lib(env,
          target=target,
          sources=sources,
          caelus_inc=caelus_inc,
          caelus_libs=caelus_libs)

