# -*- mode: python -*-

from build import build_lib
Import('env')

target = 'incompressibleLESModels'

sources = Split("""
incompressibleLESdelta/incompressibleLESdelta.cpp
vanDriestDelta/vanDriestDelta.cpp
LESModel/LESModel.cpp
GenEddyVisc/GenEddyVisc.cpp
GenSGSStress/GenSGSStress.cpp
laminar/LESLaminar.cpp
kOmegaSSTDES/kOmegaSSTDES.cpp
kOmegaSSTDDES/kOmegaSSTDDES.cpp
kOmegaSSTIDDES/kOmegaSSTIDDES.cpp
SpalartAllmarasDES/SpalartAllmarasDES.cpp
SpalartAllmarasDDES/SpalartAllmarasDDES.cpp
SpalartAllmarasIDDES/SpalartAllmarasIDDES.cpp
dynOneEqEddy/dynOneEqEddy.cpp
Smagorinsky/Smagorinsky.cpp
WALE/WALE.cpp
oneEqEddy/oneEqEddy.cpp
coherentStructureModel/coherentStructureModel.cpp
""")

caelus_inc = [
'transportModels',
'turbulenceModels',
'turbulenceModels/LES/LESdeltas/lnInclude',
'turbulenceModels/LES/LESfilters/lnInclude'
]

caelus_libs = [
'core',
'incompressibleTurbulenceModel',
'LESdeltas',
'LESfilters'
]

build_lib(env,
          target=target,
          sources=sources,
          caelus_inc=caelus_inc,
          caelus_libs=caelus_libs)
