#Copyright (C) 2014 Applied CCM
import subprocess
Import('globalEnv')

# Clone the global environment so changes made he are not pass onto subsequent 
# libraries
turbInLESEnv = globalEnv.Clone()

# Path to source
src = turbInLESEnv['LIB_SRC']

#===============================================================================
# Additions to compiler flags for this library
#===============================================================================
turbInLESEnv.Append(CCFLAGS = '')

#===============================================================================
# Additions to include directories for this library
#===============================================================================
lib_inc = ['lnInclude', src + '/transportModels', src + '/turbulenceModels',
src + '/turbulenceModels/LES/LESdeltas/lnInclude',
src + '/turbulenceModels/LES/LESfilters/lnInclude'
] 
turbInLESEnv.Prepend(CPPPATH = lib_inc)
    
#===============================================================================
# Additions to link library paths for this library
#===============================================================================
lib_link_path = [] 
turbInLESEnv.Prepend(LIBPATH = lib_link_path)

#===============================================================================
# Additions to link libraries for this library
#===============================================================================
lib_link = ['core','incompressibleTurbulenceModel',
'LESdeltas','LESfilters']
turbInLESEnv.Append(LIBS = lib_link)
  
#===============================================================================
# Sources for this library
#===============================================================================
src_files = Split("""
  incompressibleLESdelta/incompressibleLESdelta.cpp
  vanDriestDelta/vanDriestDelta.cpp
  LESModel/LESModel.cpp
  GenEddyVisc/GenEddyVisc.cpp
  GenSGSStress/GenSGSStress.cpp
  laminar/laminar.cpp
  kOmegaSSTDES/kOmegaSSTDES.cpp
  kOmegaSSTDDES/kOmegaSSTDDES.cpp
  SpalartAllmarasDES/SpalartAllmarasDES.cpp
  SpalartAllmarasDDES/SpalartAllmarasDDES.cpp
  SpalartAllmarasIDDES/SpalartAllmarasIDDES.cpp
  dynOneEqEddy/dynOneEqEddy.cpp
  Smagorinsky/Smagorinsky.cpp
  oneEqEddy/oneEqEddy.cpp
  coherentStructureModel/coherentStructureModel.cpp
  """)

#===============================================================================
# Build this library
#===============================================================================
libincompressibleLESModels = turbInLESEnv.SharedLibrary(target = 
'incompressibleLESModels', source = src_files)

#===============================================================================
# Install this library
#===============================================================================
install_dir = turbInLESEnv['LIB_PLATFORM_INSTALL']
turbInLESEnv.Alias('install', install_dir)
turbInLESEnv.Install(install_dir, libincompressibleLESModels)

if (turbInLESEnv['WHICH_OS'] == "darwin"):

  turbInLESEnv.Append(SHLINKFLAGS ='-install_name @executable_path/../lib/libincompressibleLESModels.dylib')
