# -*- mode: python -*-

import os
import utils
from build import build_app
Import('env')

target = 'Pe'

sources = Split("""
Pe_app.cpp
""")

caelus_inc = [
'postProcessing/postCalc',
'turbulenceModels',
'turbulenceModels/incompressible/turbulenceModel/lnInclude',
'turbulenceModels/incompressible/RAS/lnInclude',  
'turbulenceModels/incompressible/LES/lnInclude',  
'turbulenceModels/compressible/turbulenceModel/lnInclude',
'turbulenceModels/compressible/RAS/lnInclude',  
'turbulenceModels/compressible/LES/lnInclude',
'turbulenceModels/LES/LESdeltas/lnInclude',
'transportModels',
'transportModels/incompressible/lnInclude',
'thermophysicalModels/basic/lnInclude',  
'sampling/lnInclude'
]

caelus_libs = [
'core',
'incompressibleTurbulenceModel',
'incompressibleRASModels',
'incompressibleLESModels',
'compressibleTurbulenceModel',
'compressibleRASModels',
'compressibleLESModels',
'specie',
'fluidThermophysicalModels',
'incompressibleTransportModels'
]

post_calc = [os.path.join(env['LIB_PLATFORM_INSTALL'],'postCalc.o')]
sources += post_calc

ostype = utils.ostype()
prepend_args = {}
if ostype == 'windows':
   prepend_args = {'LINKFLAGS' :
         '-u genericPatchFieldsLoad -u incompressibleRASModelsLoad -u incompressibleLESModelsLoad -u compressibleRASModelsLoad -u compressibleLESModelsLoad -u turbulenceDerivedFvPatchFieldsLoad'
}

build_app(env,
          target=target,
          sources=sources,
          caelus_inc=caelus_inc,
          caelus_libs=caelus_libs,
          prepend_args=prepend_args)
