# -*- mode: python -*-

from build import build_lib
Import('env')

target = 'ODE'

sources = Split("""
ODESolvers/ODESolver/ODESolver.cpp
ODESolvers/ODESolver/ODESolverNew.cpp
ODESolvers/RK/RK.cpp
ODESolvers/KRR4/KRR4.cpp
ODESolvers/SIBS/SIBS.cpp
ODESolvers/SIBS/SIMPR.cpp
ODESolvers/SIBS/polyExtrapolate.cpp
""")

caelus_inc = []

caelus_libs = [
'core'
]

build_lib(env,
          target=target,
          sources=sources,
          caelus_inc=caelus_inc,
          caelus_libs=caelus_libs)
