#Copyright (C) 2014 Applied CCM
import subprocess
Import('globalEnv')

# Clone the global environment so changes made he are not pass onto subsequent 
# libraries
splitMeshEnv = globalEnv.Clone()

# Path to source
src = splitMeshEnv['LIB_SRC']

splitMeshEnv.Append(CXXFLAGS = '')
#===============================================================================
# Additions to compiler flags for this executable
#===============================================================================
splitMeshEnv.Append(CCFLAGS = '')

#===============================================================================
# Additions to include directories for this executable
#===============================================================================
lib_inc = [src + '/dynamicMesh/lnInclude']
splitMeshEnv.Prepend(CPPPATH = lib_inc)

#===============================================================================
# Additions to link library paths for this executable
#===============================================================================
lib_link_path = []
splitMeshEnv.Prepend(LIBPATH = lib_link_path)

#===============================================================================
# Additions to link libraries for this executable
#===============================================================================
lib_link = ['dynamicMesh']
  
splitMeshEnv.Append(LIBS = lib_link)

#===============================================================================
# Sources for this executable
#===============================================================================
src_files = Split("""
  regionSide.cpp
  splitMesh.cpp
  """)

#===============================================================================
# Build this executable
#===============================================================================
binsplitMesh = splitMeshEnv.Program(target = 
'splitMesh', source = src_files)

#===============================================================================
# Install this executable
#===============================================================================
install_dir = splitMeshEnv['BIN_PLATFORM_INSTALL']
splitMeshEnv.Alias('install', install_dir)
splitMeshEnv.Install(install_dir, binsplitMesh)
