#Copyright (C) 2014 Applied CCM
import subprocess
Import('globalEnv')

# Clone the global environment so changes made he are not pass onto subsequent 
# libraries
patchAverageEnv = globalEnv.Clone()

# Path to source
src = patchAverageEnv['LIB_SRC']

#===============================================================================
# Additions to compiler flags for this executable
#===============================================================================
patchAverageEnv.Append(CCFLAGS = '')

#===============================================================================
# Additions to include directories for this executable
#===============================================================================
lib_inc = []

patchAverageEnv.Prepend(CPPPATH = lib_inc)

#===============================================================================
# Additions to link library paths for this executable
#===============================================================================
lib_link_path = []
patchAverageEnv.Prepend(LIBPATH = lib_link_path)

#===============================================================================
# Additions to link libraries for this executable
#===============================================================================
if patchAverageEnv['WHICH_OS'] == "windows":
  patchAverageEnv.Prepend(LINKFLAGS = ' -u genericPatchFieldsLoad')

lib_link = ['genericPatchFields']
     
patchAverageEnv.Append(LIBS = lib_link)

#===============================================================================
# Sources for this executable
#===============================================================================
src_files = Split("""
  patchAverage.cpp
  """)

#===============================================================================
# Build this executable
#===============================================================================
binpatchAverage = patchAverageEnv.Program(target = 'patchAverage', 
source = src_files)

#===============================================================================
# Install this executable
#===============================================================================
install_dir = patchAverageEnv['BIN_PLATFORM_INSTALL']
patchAverageEnv.Alias('install', install_dir)
patchAverageEnv.Install(install_dir, binpatchAverage)
