# -*- mode: python -*-

from build import build_lib
Import('env')

target = 'liquidMixtureProperties'

sources = Split("""
liquidMixtureProperties/liquidMixtureProperties.cpp
""")

caelus_inc = [
'thermophysicalModels/thermophysicalFunctions/lnInclude',
'thermophysicalModels/basic/lnInclude',
'thermophysicalModels/specie/lnInclude',
'thermophysicalModels/properties/liquidProperties/lnInclude'
]

caelus_libs = [
'core',
'specie',
'liquidProperties',
'thermophysicalFunctions'
]

build_lib(env,
          target=target,
          sources=sources,
          caelus_inc=caelus_inc,
          caelus_libs=caelus_libs)
