#Copyright (C) 2014 Applied CCM
import subprocess
Import('globalEnv')

# Clone the global environment so changes made he are not pass onto subsequent 
# libraries
thermoLiqMixPropEnv = globalEnv.Clone()

# Path to source
src = thermoLiqMixPropEnv['LIB_SRC']

#===============================================================================
# Additions to compiler flags for this library
#===============================================================================
thermoLiqMixPropEnv.Append(CCFLAGS = '')

#===============================================================================
# Additions to include directories for this library
#===============================================================================
lib_inc = ['lnInclude',
src + '/thermophysicalModels/thermophysicalFunctions/lnInclude',
src + '/thermophysicalModels/basic/lnInclude',
src + '/thermophysicalModels/specie/lnInclude',
src + '/thermophysicalModels/combustion/lnInclude',
src + '/thermophysicalModels/properties/liquidProperties/lnInclude'
]
thermoLiqMixPropEnv.Prepend(CPPPATH = lib_inc)

#===============================================================================
# Additions to link library paths for this library
#===============================================================================
lib_link_path = []
thermoLiqMixPropEnv.Prepend(LIBPATH = lib_link_path)

#===============================================================================
# Additions to link libraries for this library
#===============================================================================
lib_link = ['core','specie','liquidProperties', 'thermophysicalFunctions']
thermoLiqMixPropEnv.Append(LIBS = lib_link)

#===============================================================================
# Sources for this library
#===============================================================================
src_files = Split("""
  liquidMixtureProperties/liquidMixtureProperties.cpp
  """)

#===============================================================================
# Build this library
#===============================================================================
libliquidMixtureProperties = thermoLiqMixPropEnv.SharedLibrary(target = 
'liquidMixtureProperties', source = src_files)

#===============================================================================
# Install this library
#===============================================================================
install_dir = thermoLiqMixPropEnv['LIB_PLATFORM_INSTALL']
thermoLiqMixPropEnv.Alias('install', install_dir)
thermoLiqMixPropEnv.Install(install_dir, libliquidMixtureProperties)

if (thermoLiqMixPropEnv['WHICH_OS'] == "darwin"):

  thermoLiqMixPropEnv.Append(SHLINKFLAGS ='-install_name @' + thermoLiqMixPropEnv['LIB_PLATFORM_INSTALL'] + '/libliquidMixtureProperties.dylib')
