#Copyright (C) 2014 Applied CCM
import subprocess
Import('globalEnv')

# Clone the global environment so changes made he are not pass onto subsequent 
# libraries
lagSprayEnv = globalEnv.Clone()

# Path to source
src = lagSprayEnv['LIB_SRC']

#===============================================================================
# Additions to compiler flags for this library
#===============================================================================
lagSprayEnv.Append(CCFLAGS = '')

#===============================================================================
# Additions to include directories for this library
#===============================================================================
lib_inc = ['lnInclude',
src + '/sampling/lnInclude',
src + '/dynamicFvMesh/lnInclude',
src + '/lagrangian/basic/lnInclude',
src + '/lagrangian/distributionModels/lnInclude',
src + '/lagrangian/intermediate/lnInclude',
src + '/turbulenceModels',
src + '/transportModels',
src + '/regionModels/regionModel/lnInclude',
src + '/regionModels/surfaceFilmModels/lnInclude',
src + '/thermophysicalModels/specie/lnInclude',
src + '/thermophysicalModels/basic/lnInclude',
src + '/thermophysicalModels/reactionThermo/lnInclude',
src + '/thermophysicalModels/SLGThermo/lnInclude',
src + '/thermophysicalModels/radiationModels/lnInclude',
src + '/thermophysicalModels/properties/liquidProperties/lnInclude',
src + '/thermophysicalModels/properties/liquidMixtureProperties/lnInclude',
src + '/thermophysicalModels/properties/solidProperties/lnInclude',
src + '/thermophysicalModels/properties/solidMixtureProperties/lnInclude'
]
lagSprayEnv.Prepend(CPPPATH = lib_inc)
    
#===============================================================================
# Additions to link library paths for this library
#===============================================================================
lib_link_path = []
lagSprayEnv.Prepend(LIBPATH = lib_link_path)

#===============================================================================
# Additions to link libraries for this library
#===============================================================================
lib_link = ['core','lagrangian','distributionModels','specie',
'basicThermophysicalModels','liquidProperties','liquidMixtureProperties',
'solidProperties','solidMixtureProperties','reactionThermophysicalModels',
'SLGThermo','radiationModels','compressibleTurbulenceModel',
'incompressibleTurbulenceModel',
'compressibleRASModels','compressibleLESModels','LESdeltas',
'incompressibleTransportModels','regionModels','surfaceFilmModels',
'dynamicFvMesh','sampling','lagrangianIntermediate'
]
lagSprayEnv.Append(LIBS = lib_link)
             
#===============================================================================
# Sources for this library
#===============================================================================
src_files = Split("""
  clouds/baseClasses/sprayCloud/sprayCloud.cpp
  parcels/derived/basicSprayParcel/defineBasicSprayParcel.cpp
  parcels/derived/basicSprayParcel/makeBasicSprayParcelSubmodels.cpp
  """) 

#===============================================================================
# Build this library
#===============================================================================
liblagrangianSpray = lagSprayEnv.SharedLibrary(target = 'lagrangianSpray', 
source = src_files)

#===============================================================================
# Install this library
#===============================================================================
install_dir = lagSprayEnv['LIB_PLATFORM_INSTALL']
lagSprayEnv.Alias('install', install_dir)
lagSprayEnv.Install(install_dir, liblagrangianSpray)

if (lagSprayEnv['WHICH_OS'] == "darwin"):

  lagSprayEnv.Append(SHLINKFLAGS ='-install_name @executable_path/../lib/liblagrangianSpray.dylib')
