# -*- mode: python -*-

import utils
from build import build_app
Import('env')

target = 'createTurbulenceFields'

sources = Split("""
createTurbulenceFields.cpp
""")

caelus_inc = [
'turbulenceModels',
'turbulenceModels/incompressible/turbulenceModel/lnInclude',
'turbulenceModels/incompressible/RAS/lnInclude',  
'turbulenceModels/incompressible/RAS/RASModel',
'transportModels',
'transportModels/incompressible/lnInclude',  
]

caelus_libs = [
'core',
'genericPatchFields',
'incompressibleRASModels',
'incompressibleTurbulenceModel',
'incompressibleTransportModels'
]

ostype = utils.ostype()
prepend_args = {}
if ostype == 'windows':
   prepend_args = {'LINKFLAGS' :
         '-u genericPatchFieldsLoad -u incompressibleRASModelsLoad -u turbulenceDerivedFvPatchFieldsLoad'
}

build_app(env,
          target=target,
          sources=sources,
          caelus_inc=caelus_inc,
          caelus_libs=caelus_libs,
          prepend_args=prepend_args)
