# -*- mode: python -*-

from build import build_lib
Import('env')

target = 'incompressibleVLESModels'

sources = Split("""
VLESModel/VLESModel.cpp
laminar/VLESLaminar.cpp
realizableKE/VLESRealizableKE.cpp
kOmegaSST/VLESkOmegaSST.cpp
kOmegaSSTCSModel/VLESkOmegaSSTCSModel.cpp
SpalartAllmaras/VLESSpalartAllmaras.cpp
""")

caelus_inc = [
'transportModels',
'turbulenceModels'
]

caelus_libs = [
'core',
'incompressibleTurbulenceModel'
]

build_lib(env,
          target=target,
          sources=sources,
          caelus_inc=caelus_inc,
          caelus_libs=caelus_libs)
