# -*- mode: python -*-

from build import build_lib
Import('env')

target = 'numericFlux'

sources = Split("""
roeFDSFlux/roeFDSFlux.cpp
llfFlux/llfFlux.cpp
hllcFlux/hllcFlux.cpp
ktpFlux/ktpFlux.cpp
dwFlux/dwFlux.cpp
""")

caelus_inc = [
'thermophysicalModels/specie/lnInclude'
]

caelus_libs = [
'core',
'specie'
]

build_lib(env,
          target=target,
          sources=sources,
          caelus_inc=caelus_inc,
          caelus_libs=caelus_libs)
