#Copyright (C) 2014 Applied CCM
import subprocess
Import('globalEnv')

# Clone the global environment so changes made he are not pass onto subsequent 
# libraries
SRFPimpleSolEnv = globalEnv.Clone()

# Path to source
src = SRFPimpleSolEnv['LIB_SRC']

#===============================================================================
# Additions to include directories for this executable
#===============================================================================
lib_inc = [src + '/turbulenceModels/incompressible/turbulenceModel',
src + '/turbulenceModels/incompressible/turbulenceModel/lnInclude', 
src + '/transportModels',
src + '/transportModels/incompressible/singlePhaseTransportModel',
src + '/transportModels/incompressible/lnInclude',
src + '/fvOptions/lnInclude',
src + '/sampling/lnInclude'
]
SRFPimpleSolEnv.Prepend(CPPPATH = lib_inc)

#===============================================================================
# Additions to link libraries for this executable
#===============================================================================
if SRFPimpleSolEnv['WHICH_OS'] == "windows":
  SRFPimpleSolEnv.Prepend(LINKFLAGS = ' -u incompressibleRASModelsLoad  -u incompressibleLESModelsLoad')

lib_link = ['libincompressibleTurbulenceModel', 'libincompressibleRASModels',
'libincompressibleLESModels','libincompressibleTransportModels','fvOptions', 'sampling']

SRFPimpleSolEnv.Append(LIBS = lib_link)

#===============================================================================
# Sources for this executable
#===============================================================================
src_files = Split("""
  SRFPimpleSolver.cpp
  """)

#===============================================================================
# Build this executable
#===============================================================================
binSRFPimpleSol = SRFPimpleSolEnv.Program(target = 'SRFPimpleSolver',
source = src_files)

#===============================================================================
# Install this executable
#===============================================================================
install_dir = SRFPimpleSolEnv['BIN_PLATFORM_INSTALL']
SRFPimpleSolEnv.Alias('install', install_dir)
SRFPimpleSolEnv.Install(install_dir, binSRFPimpleSol)
