# -*- mode: python -*-

from build import build_lib
Import('env')

target = 'LESdeltas'

sources = Split("""
LESdelta/LESdelta.cpp
cubeRootVolDelta/cubeRootVolDelta.cpp
PrandtlDelta/PrandtlDelta.cpp
smoothDelta/smoothDelta.cpp
maxDeltaxyz/maxDeltaxyz.cpp
IDDESDelta/IDDESDelta.cpp
""")

caelus_inc = [
'transportModels/incompressible/lnInclude',
'LESmodels/isoLESmodels/lnInclude',
]

caelus_libs = [
'core'
]

build_lib(env,
          target=target,
          sources=sources,
          caelus_inc=caelus_inc,
          caelus_libs=caelus_libs)
