#Copyright (C) 2015 Applied CCM
import subprocess
Import('globalEnv')

# Clone the global environment so changes made he are not pass onto subsequent 
# libraries
vofSolEnv = globalEnv.Clone()

# Path to source
src = vofSolEnv['LIB_SRC']

#===============================================================================
# Additions to include directories for this executable
#===============================================================================
lib_inc = [src + '/turbulenceModels/incompressible/turbulenceModel',
src + '/turbulenceModels/incompressible/turbulenceModel/lnInclude', 
src + '/transportModels',
src + '/transportModels/incompressible/singlePhaseTransportModel',
src + '/transportModels/incompressible/lnInclude',
src + '/transportModels/interfaceProperties/lnInclude',
src + '/fvOptions/lnInclude',
src + '/sampling/lnInclude'
]
vofSolEnv.Prepend(CPPPATH = lib_inc)

#===============================================================================
# Additions to link libraries for this executable
#===============================================================================
if vofSolEnv['WHICH_OS'] == "windows":
  vofSolEnv.Prepend(LINKFLAGS = ' -u incompressibleRASModelsLoad  -u incompressibleLESModelsLoad -u incompressibleVLESModelsLoad')

lib_link = ['incompressibleTurbulenceModel', 'incompressibleRASModels',
'incompressibleLESModels','incompressibleTransportModels','twoPhaseInterfaceProperties',
'fvOptions','interfaceProperties','incompressibleVLESModels']
vofSolEnv.Append(LIBS = lib_link)

#===============================================================================
# Sources for this executable
#===============================================================================
src_files = Split("""
  vofSolver.cpp
  """)

#===============================================================================
# Build this executable
#===============================================================================
binvofSol = vofSolEnv.Program(target = 'vofSolver',
source = src_files)

#===============================================================================
# Install this executable
#===============================================================================
install_dir = vofSolEnv['BIN_PLATFORM_INSTALL']
vofSolEnv.Alias('install', install_dir)
vofSolEnv.Install(install_dir, binvofSol)
