#Copyright (C) 2014 Applied CCM
import subprocess
Import('globalEnv')

# Clone the global environment so changes made he are not pass onto subsequent 
# libraries
refineWallLayerEnv = globalEnv.Clone()

# Path to source
src = refineWallLayerEnv['LIB_SRC']

#===============================================================================
# Additions to compiler flags for this executable
#===============================================================================
refineWallLayerEnv.Append(CCFLAGS = '')

#===============================================================================
# Additions to include directories for this executable
#===============================================================================
lib_inc = [src + '/dynamicMesh/lnInclude']
refineWallLayerEnv.Prepend(CPPPATH = lib_inc)

#===============================================================================
# Additions to link library paths for this executable
#===============================================================================
lib_link_path = []
refineWallLayerEnv.Prepend(LIBPATH = lib_link_path)

#===============================================================================
# Additions to link libraries for this executable
#===============================================================================
if refineWallLayerEnv['WHICH_OS'] == "windows":
  lib_link = ['libdynamicMesh']
else:
  lib_link = ['dynamicMesh']
     

refineWallLayerEnv.Append(LIBS = lib_link)

#===============================================================================
# Sources for this executable
#===============================================================================
src_files = Split("""
  refineWallLayer.cpp
  """)

#===============================================================================
# Build this executable
#===============================================================================
binrefineWallLayer = refineWallLayerEnv.Program(target = 'refineWallLayer', 
source = src_files)

#===============================================================================
# Install this executable
#===============================================================================
install_dir = refineWallLayerEnv['BIN_PLATFORM_INSTALL']
refineWallLayerEnv.Alias('install', install_dir)
refineWallLayerEnv.Install(install_dir, binrefineWallLayer)
