# -*- mode: python -*-

import utils
from build import build_app
Import('env')

target = "reactingSolver"

sources = Split("""
reactingSolver.cpp
""")

caelus_inc = [
'turbulenceModels/',
'turbulenceModels/compressible/turbulenceModel/lnInclude',
'transportModels',
'thermophysicalModels',
'thermophysicalModels/specie/lnInclude',
'thermophysicalModels/reactionThermo/lnInclude',
'thermophysicalModels/basic/lnInclude',
'thermophysicalModels/chemistryModel/lnInclude',
'combustionModels/lnInclude',
'transportModels/basic/lnInclude',
'fvOptions/lnInclude',
'sampling/lnInclude',
'thermophysicalModels/numericFluxes/DBNS/numericFlux/lnInclude',
]

caelus_libs = [
'core',
'compressibleTurbulenceModel',
'compressibleRASModels',
'compressibleLESModels',
'compressibleVLESModels',
'basicThermophysicalModels',
'turbulenceDerivedFvPatchFields',
'fvOptions',
'sampling',
'numericFlux',
'reactionThermophysicalModels',
'chemistryModel',
'specie',
'combustionModels'
]

ostype = utils.ostype()
prepend_args = {}
if ostype == 'windows':
   prepend_args = {'LINKFLAGS' :
            '-u compressibleRASModelsLoad -u compressibleLESModelsLoad -u compressibleVLESModelsLoad -u turbulenceDerivedFvPatchFieldsLoad'
}

build_app(env,
          target=target,
          sources=sources,
          caelus_inc=caelus_inc,
          caelus_libs=caelus_libs,
          prepend_args=prepend_args)
