# -*- mode: python -*-

from build import build_lib
Import('env')

target = 'compressibleTurbulenceModel'

sources = Split("""
turbulenceModel.cpp
laminar/laminar.cpp
derivedFvPatchFields/wallFunctions/alphatWFs/alphatWF/alphatWFFvPatchScalarField.cpp
derivedFvPatchFields/wallFunctions/alphatWFs/alphatJayaWF/alphatJayaWFFvPatchScalarField.cpp
derivedFvPatchFields/wallFunctions/mutWFs/mutkRghWF/mutkRghWFFvPatchScalarField.cpp
derivedFvPatchFields/wallFunctions/mutWFs/mutkWF/mutkWFFvPatchScalarField.cpp
derivedFvPatchFields/wallFunctions/mutWFs/mutURghWF/mutURghWFFvPatchScalarField.cpp
derivedFvPatchFields/wallFunctions/mutWFs/mutUSpaldingWF/mutUSpaldingWFFvPatchScalarField.cpp
derivedFvPatchFields/wallFunctions/mutWFs/mutUWF/mutUWFFvPatchScalarField.cpp
derivedFvPatchFields/wallFunctions/mutWFs/mutLowReWF/mutLowReWFFvPatchScalarField.cpp
derivedFvPatchFields/wallFunctions/epsilonWFs/epsilonWF/epsilonWFFvPatchScalarField.cpp
derivedFvPatchFields/wallFunctions/omegaWFs/omegaWF/omegaWFFvPatchScalarField.cpp
derivedFvPatchFields/convectiveHeatTransfer/convectiveHeatTransferFvPatchScalarField.cpp
derivedFvPatchFields/turbulentMixingLengthDsiptRateInlet/turbulentMixingLengthDsiptRateInletFvPatchScalarField.cpp
derivedFvPatchFields/turbulentMixingLengthFreqInlet/turbulentMixingLengthFreqInletFvPatchScalarField.cpp
derivedFvPatchFields/turbulentHeatFluxTemperature/turbulentHeatFluxTemperatureFvPatchScalarField.cpp
derivedFvPatchFields/temperatureCoupledBase/temperatureCoupledBase.cpp
derivedFvPatchFields/turbulentTemperatureCoupledBaffleMixed/turbulentTemperatureCoupledBaffleMixedFvPatchScalarField.cpp
derivedFvPatchFields/temperatureThermoBaffle1D/temperatureThermoBaffle1DFvPatchScalarFields.cpp
derivedFvPatchFields/totalFlowRateAdvectiveDiffusive/totalFlowRateAdvectiveDiffusiveFvPatchScalarField.cpp
derivedFvPatchFields/turbulentTemperatureRadCoupledMixed/turbulentTemperatureRadCoupledMixedFvPatchScalarField.cpp
derivedFvPatchFields/externalWallHeatFluxTemperature/externalWallHeatFluxTemperatureFvPatchScalarField.cpp
""")

caelus_inc = [
'turbulenceModels',
'thermophysicalModels/basic/lnInclude',
'thermophysicalModels/specie/lnInclude',
'thermophysicalModels/basicSolidThermo/lnInclude',
'thermophysicalModels/solid/lnInclude'
]

caelus_libs = [
'core',
'solid',
'specie',
'radiationModels',
'basicThermophysicalModels',
'basicSolidThermo'
]

build_lib(env,
          target=target,
          sources=sources,
          caelus_inc=caelus_inc,
          caelus_libs=caelus_libs)
