# -*- mode: python -*-

from build import build_lib
Import('env')

target = 'solidParticle'

sources = Split("""
solidParticle.cpp
solidParticleIO.cpp
solidParticleCloud.cpp
""")

caelus_inc = [
'lagrangian/basic/lnInclude'
]

caelus_libs = [
'core',
'lagrangian'
]

build_lib(env,
          target=target,
          sources=sources,
          caelus_inc=caelus_inc,
          caelus_libs=caelus_libs)
