#Copyright (C) 2014 Applied CCM
import subprocess
Import('globalEnv')

# Clone the global environment so changes made he are not pass onto subsequent 
# libraries
regModelsEnv = globalEnv.Clone()

#===============================================================================
# Additions to compiler flags for this library
#===============================================================================
regModelsEnv.Append(CCFLAGS = '')

#===============================================================================
# Additions to include directories for this library
#===============================================================================
lib_inc = ['lnInclude']
regModelsEnv.Prepend(CPPPATH = lib_inc)
    
#===============================================================================
# Additions to link library paths for this library
#===============================================================================
lib_link_path = []
regModelsEnv.Prepend(LIBPATH = lib_link_path)

#===============================================================================
# Additions to link libraries for this library
#===============================================================================
lib_link = ['core']
regModelsEnv.Append(LIBS = lib_link)
       
#===============================================================================
# Sources for this library
#===============================================================================
src_files = Split("""
  regionModel/regionModel.cpp
  singleLayerRegion/singleLayerRegion.cpp
  regionModel1D/regionModel1D.cpp
  derivedFvPatches/mappedVariableThicknessWall/mappedVariableThicknessWallFvPatch.cpp
  """)

#===============================================================================
# Build this library
#===============================================================================
libregionModels = regModelsEnv.SharedLibrary(target = 'regionModels', 
source = src_files)

#===============================================================================
# Install this library
#===============================================================================
install_dir = regModelsEnv['LIB_PLATFORM_INSTALL']
regModelsEnv.Alias('install', install_dir)
regModelsEnv.Install(install_dir, libregionModels)

if (regModelsEnv['WHICH_OS'] == "darwin"):

  regModelsEnv.Append(SHLINKFLAGS ='-install_name @' + regModelsEnv['LIB_PLATFORM_INSTALL'] + '/libregionModels.dylib')
