# -*- mode: python -*-

from build import build_lib
Import('env')

target = 'regionModels'

sources = Split("""
regionModel/regionModel.cpp
singleLayerRegion/singleLayerRegion.cpp
regionModel1D/regionModel1D.cpp
regionProperties/regionProperties.cpp
derivedFvPatches/mappedVariableThicknessWall/mappedVariableThicknessWallFvPatch.cpp
""")

caelus_inc = []

caelus_libs = [
'core'
]

build_lib(env,
          target=target,
          sources=sources,
          caelus_inc=caelus_inc,
          caelus_libs=caelus_libs)
