#Copyright (C) 2014 Applied CCM
import subprocess
Import('globalEnv')

# Clone the global environment so changes made he are not pass onto subsequent 
# libraries
topoChangerEnv = globalEnv.Clone()

# Path to source
src = topoChangerEnv['LIB_SRC']

#===============================================================================
# Additions to compiler flags for this library
#===============================================================================
topoChangerEnv.Append(CCFLAGS = '')

#===============================================================================
# Additions to include directories for this library
#===============================================================================
lib_inc = ['lnInclude',
src + '/dynamicFvMesh/lnInclude',
src + '/dynamicMesh/lnInclude'
]
topoChangerEnv.Prepend(CPPPATH = lib_inc)

#===============================================================================
# Additions to link library paths for this library
#===============================================================================
lib_link_path = []
topoChangerEnv.Prepend(LIBPATH = lib_link_path)

#===============================================================================
# Additions to link libraries for this library
#===============================================================================
lib_link = ['core', 'dynamicFvMesh', 'dynamicMesh']
topoChangerEnv.Append(LIBS = lib_link)

#===============================================================================
# Sources for this library
#===============================================================================
src_files = Split("""
  topoChangerFvMesh/topoChangerFvMesh.cpp
  rawTopoChangerFvMesh/rawTopoChangerFvMesh.cpp
  movingConeTopoFvMesh/movingConeTopoFvMesh.cpp
  """)

#===============================================================================
# Build this library
#===============================================================================
libtopoChangerFvMesh = topoChangerEnv.SharedLibrary(target = 
'topoChangerFvMesh', source = src_files)

#===============================================================================
# Install this library
#===============================================================================
install_dir = topoChangerEnv['LIB_PLATFORM_INSTALL']
topoChangerEnv.Alias('install', install_dir)
topoChangerEnv.Install(install_dir, libtopoChangerFvMesh)

if (topoChangerEnv['WHICH_OS'] == "darwin"):

  topoChangerEnv.Append(SHLINKFLAGS ='-install_name @' + topoChangerEnv['LIB_PLATFORM_INSTALL'] + '/libtopoChangerFvMesh.dylib')

