#Copyright (C) 2014 Applied CCM
import subprocess
Import('globalEnv')

# Clone the global environment so changes made he are not pass onto subsequent 
# libraries
subsetMeshEnv = globalEnv.Clone()

# Path to source
src = subsetMeshEnv['LIB_SRC']

subsetMeshEnv.Append(CXXFLAGS = '')
#===============================================================================
# Additions to compiler flags for this executable
#===============================================================================
subsetMeshEnv.Append(CCFLAGS = '')

#===============================================================================
# Additions to include directories for this executable
#===============================================================================
lib_inc = []

subsetMeshEnv.Prepend(CPPPATH = lib_inc)

#===============================================================================
# Additions to link library paths for this executable
#===============================================================================
lib_link_path = []
subsetMeshEnv.Prepend(LIBPATH = lib_link_path)

#===============================================================================
# Additions to link libraries for this executable
#===============================================================================
if subsetMeshEnv['WHICH_OS'] == "windows":
  subsetMeshEnv.Prepend(LINKFLAGS = ' -u genericPatchFieldsLoad')
  lib_link = ['libgenericPatchFields']
else:
  lib_link = ['genericPatchFields']
  
subsetMeshEnv.Append(LIBS = lib_link)

#===============================================================================
# Sources for this executable
#===============================================================================
src_files = Split("""
  subsetMesh.cpp
  """)

#===============================================================================
# Build this executable
#===============================================================================
binsubsetMesh = subsetMeshEnv.Program(target = 
'subsetMesh', source = src_files)

#===============================================================================
# Install this executable
#===============================================================================
install_dir = subsetMeshEnv['BIN_PLATFORM_INSTALL']
subsetMeshEnv.Alias('install', install_dir)
subsetMeshEnv.Install(install_dir, binsubsetMesh)
