# -*- mode: python -*-

from build import build_lib
Import('env')

target = 'SLGThermo'

sources = Split("""
SLGThermo/SLGThermo.cpp
""")

caelus_inc = [
'thermophysicalModels/basic/lnInclude',
'thermophysicalModels/specie/lnInclude',
'thermophysicalModels/reactionThermo/lnInclude',
'thermophysicalModels/thermophysicalProperties/lnInclude'
]

caelus_libs = [
'core',
'thermophysicalProperties'
]

build_lib(env,
          target=target,
          sources=sources,
          caelus_inc=caelus_inc,
          caelus_libs=caelus_libs)
