# -*- mode: python -*-

from build import build_lib
Import('env')

target = 'SLGThermo'

sources = Split("""
SLGThermo/SLGThermo.cpp
""")

caelus_inc = [
'thermophysicalModels/basic/lnInclude',
'thermophysicalModels/specie/lnInclude',
'thermophysicalModels/reactionThermo/lnInclude',
'thermophysicalModels/properties/liquidProperties/lnInclude',
'thermophysicalModels/properties/liquidMixtureProperties/lnInclude',
'thermophysicalModels/properties/solidProperties/lnInclude',
'thermophysicalModels/properties/solidMixtureProperties/lnInclude'
]

caelus_libs = [
'core',
'basicThermophysicalModels',
'liquidMixtureProperties',
'solidMixtureProperties'
]

build_lib(env,
          target=target,
          sources=sources,
          caelus_inc=caelus_inc,
          caelus_libs=caelus_libs)
