#Copyright (C) 2014 Applied CCM
import subprocess
Import('globalEnv')

# Clone the global environment so changes made he are not pass onto subsequent 
# libraries
streamFunctionEnv = globalEnv.Clone()

# Path to source
src = streamFunctionEnv['LIB_SRC']

#===============================================================================
# Additions to compiler flags for this executable
#===============================================================================
streamFunctionEnv.Append(CCFLAGS = '')

#===============================================================================
# Additions to include directories for this executable
#===============================================================================
lib_inc = []        

streamFunctionEnv.Prepend(CPPPATH = lib_inc)

#===============================================================================
# Additions to link library paths for this executable
#===============================================================================
lib_link_path = []
streamFunctionEnv.Prepend(LIBPATH = lib_link_path)

#===============================================================================
# Additions to link libraries for this executable
#===============================================================================
if streamFunctionEnv['WHICH_OS'] == "windows":
  streamFunctionEnv.Prepend(LINKFLAGS = ' -u genericPatchFieldsLoad')
  lib_link = ['libcore','libgenericPatchFields']
else:
  lib_link = ['core','genericPatchFields']
    
streamFunctionEnv.Append(LIBS = lib_link)

#===============================================================================
# Sources for this executable
#===============================================================================
src_files= Split("""  
  streamFunction.cpp
  """)
#===============================================================================
# Build this executable
#===============================================================================
binstreamFunction = streamFunctionEnv.Program(target = 'streamFunction',
source = src_files)

#===============================================================================
# Install this executable
#===============================================================================
install_dir = streamFunctionEnv['BIN_PLATFORM_INSTALL']
streamFunctionEnv.Alias('install', install_dir)
streamFunctionEnv.Install(install_dir, binstreamFunction)
