# -*- mode: python -*-

from build import build_lib
Import('env')

target = 'fieldFunctionObjects'

sources = Split("""
fieldAverage/fieldAverage/fieldAverage.cpp
fieldAverage/fieldAverageItem/fieldAverageItem.cpp
fieldAverage/fieldAverageItem/fieldAverageItemIO.cpp
fieldAverage/fieldAverageFunctionObject/fieldAverageFunctionObject.cpp
fieldCoordinateSystemTransform/fieldCoordinateSystemTransform.cpp
fieldCoordinateSystemTransform/fieldCoordinateSystemTransformFunctionObject.cpp
fieldMinMax/fieldMinMax.cpp
fieldMinMax/fieldMinMaxFunctionObject.cpp
fieldValues/fieldValue/fieldValue.cpp
fieldValues/fieldValue/fieldValueNew.cpp
fieldValues/fieldValueDelta/fieldValueDelta.cpp
fieldValues/fieldValueDelta/fieldValueDeltaFunctionObject.cpp
fieldValues/faceSource/faceSource.cpp
fieldValues/faceSource/faceSourceFunctionObject.cpp
fieldValues/cellSource/cellSource.cpp
fieldValues/cellSource/cellSourceFunctionObject.cpp
nearWallFields/nearWallFields.cpp
nearWallFields/nearWallFieldsFunctionObject.cpp
nearWallFields/findCellParticle.cpp
nearWallFields/findCellParticleCloud.cpp
processorField/processorField.cpp
processorField/processorFieldFunctionObject.cpp
readFields/readFields.cpp
readFields/readFieldsFunctionObject.cpp
streamLine/streamLine.cpp
streamLine/streamLineParticle.cpp
streamLine/streamLineParticleCloud.cpp
streamLine/streamLineFunctionObject.cpp
surfaceInterpolateFields/surfaceInterpolateFields.cpp
surfaceInterpolateFields/surfaceInterpolateFieldsFunctionObject.cpp
regionSizeDistribution/regionSizeDistribution.cpp
regionSizeDistribution/regionSizeDistributionFunctionObject.cpp
""")

caelus_inc = [
'sampling/lnInclude',
'lagrangian/basic/lnInclude'
]

caelus_libs = [
'core',
'lagrangian',
'sampling'
]

build_lib(env,
          target=target,
          sources=sources,
          caelus_inc=caelus_inc,
          caelus_libs=caelus_libs)
