# -*- mode: python -*-

from build import build_app
Import('env')

target = 'changeDictionary'

sources = Split("""
changeDictionary.cpp
""")

caelus_inc = [
'dynamicMesh/dynamicMesh/lnInclude'
]

caelus_libs = [
'core',
'dynamicMesh'
]

prepend_args = { 'CXXFLAGS' : ['-Dutil_EXPORTS'] }

build_app(env,
          target=target,
          sources=sources,
          caelus_inc=caelus_inc,
          caelus_libs=caelus_libs,
          prepend_args=prepend_args)
