#Copyright (C) 2014 Applied CCM
import subprocess
Import('globalEnv')

# Clone the global environment so changes made he are not pass onto subsequent 
# libraries
particleTracksEnv = globalEnv.Clone()

# Path to source
src = particleTracksEnv['LIB_SRC']

#===============================================================================
# Additions to compiler flags for this executable
#===============================================================================
particleTracksEnv.Append(CCFLAGS = '')

#===============================================================================
# Additions to include directories for this executable
#===============================================================================
lib_inc = [src + '/lagrangian/basic/lnInclude']
particleTracksEnv.Prepend(CPPPATH = lib_inc)

#===============================================================================
# Additions to link library paths for this executable
#===============================================================================
lib_link_path = []
particleTracksEnv.Prepend(LIBPATH = lib_link_path)

#===============================================================================
# Additions to link libraries for this executable
#===============================================================================
if particleTracksEnv['WHICH_OS'] == "windows":
  particleTracksEnv.Prepend(LINKFLAGS = ' -u genericPatchFieldsLoad')
  lib_link = ['libgenericPatchFields','liblagrangian']
else:
  lib_link = ['genericPatchFields','lagrangian']
     
particleTracksEnv.Append(LIBS = lib_link)

#===============================================================================
# Sources for this executable
#===============================================================================
src_files = Split("""
  particleTracks.cpp
  """)

#===============================================================================
# Build this executable
#===============================================================================
binparticleTracks = particleTracksEnv.Program(target = 'particleTracks', 
source = src_files)

#===============================================================================
# Install this executable
#===============================================================================
install_dir = particleTracksEnv['BIN_PLATFORM_INSTALL']
particleTracksEnv.Alias('install', install_dir)
particleTracksEnv.Install(install_dir, binparticleTracks)
