#Copyright (C) 2014 Applied CCM
import subprocess
Import('globalEnv')

# Clone the global environment so changes made he are not pass onto subsequent 
# libraries
mergeMeshesEnv = globalEnv.Clone()

# Path to source
src = mergeMeshesEnv['LIB_SRC']

mergeMeshesEnv.Append(CXXFLAGS = '')
#===============================================================================
# Additions to compiler flags for this executable
#===============================================================================
mergeMeshesEnv.Append(CCFLAGS = '')

#===============================================================================
# Additions to include directories for this executable
#===============================================================================
lib_inc = [src + '/dynamicMesh/lnInclude'
]

mergeMeshesEnv.Prepend(CPPPATH = lib_inc)

#===============================================================================
# Additions to link library paths for this executable
#===============================================================================
lib_link_path = []
mergeMeshesEnv.Prepend(LIBPATH = lib_link_path)

#===============================================================================
# Additions to link libraries for this executable
#===============================================================================
lib_link = ['dynamicMesh']
  
mergeMeshesEnv.Append(LIBS = lib_link)

#===============================================================================
# Sources for this executable
#===============================================================================
src_files = Split("""
  mergeMeshes.cpp
  mergePolyMesh.cpp
  """)

#===============================================================================
# Build this executable
#===============================================================================
binmergeMeshes = mergeMeshesEnv.Program(target = 
'mergeMeshes', source = src_files)

#===============================================================================
# Install this executable
#===============================================================================
install_dir = mergeMeshesEnv['BIN_PLATFORM_INSTALL']
mergeMeshesEnv.Alias('install', install_dir)
mergeMeshesEnv.Install(install_dir, binmergeMeshes)
