# -*- mode: python -*-

from build import build_app
Import('env')

target = 'steadyParticleTracks'

sources = Split("""
steadyParticleTracks.cpp
""")

caelus_inc = [
'lagrangian/basic/lnInclude'
]

caelus_libs = [
'core',
'lagrangian'
]

build_app(env,
          target=target,
          sources=sources,
          caelus_inc=caelus_inc,
          caelus_libs=caelus_libs)
