#Copyright (C) 2014 Applied CCM
import subprocess
Import('globalEnv')

# Clone the global environment so changes made he are not pass onto subsequent 
# libraries
steadyParticleTracksEnv = globalEnv.Clone()

# Path to source
src = steadyParticleTracksEnv['LIB_SRC']

#===============================================================================
# Additions to compiler flags for this executable
#===============================================================================
steadyParticleTracksEnv.Append(CCFLAGS = '')

#===============================================================================
# Additions to include directories for this executable
#===============================================================================
lib_inc = [src + '/lagrangian/basic/lnInclude']
steadyParticleTracksEnv.Prepend(CPPPATH = lib_inc)

#===============================================================================
# Additions to link library paths for this executable
#===============================================================================
lib_link_path = []
steadyParticleTracksEnv.Prepend(LIBPATH = lib_link_path)

#===============================================================================
# Additions to link libraries for this executable
#===============================================================================
lib_link = ['lagrangian']
     
steadyParticleTracksEnv.Append(LIBS = lib_link)

#===============================================================================
# Sources for this executable
#===============================================================================
src_files = Split("""
  steadyParticleTracks.cpp
  """)

#===============================================================================
# Build this executable
#===============================================================================
binsteadyParticleTracks = steadyParticleTracksEnv.Program(target = 'steadyParticleTracks', 
source = src_files)

#===============================================================================
# Install this executable
#===============================================================================
install_dir = steadyParticleTracksEnv['BIN_PLATFORM_INSTALL']
steadyParticleTracksEnv.Alias('install', install_dir)
steadyParticleTracksEnv.Install(install_dir, binsteadyParticleTracks)
