#Copyright (C) 2014 Applied CCM
import subprocess
Import('globalEnv')

# Clone the global environment so changes made he are not pass onto subsequent 
# libraries
thermoLiqPropEnv = globalEnv.Clone()

# Path to source
src = thermoLiqPropEnv['LIB_SRC']

#===============================================================================
# Additions to compiler flags for this library
#===============================================================================
thermoLiqPropEnv.Append(CCFLAGS = '')

#===============================================================================
# Additions to include directories for this library
#===============================================================================
lib_inc = ['lnInclude',
src + '/thermophysicalModels/thermophysicalFunctions/lnInclude'
]
thermoLiqPropEnv.Prepend(CPPPATH = lib_inc)

#===============================================================================
# Additions to link library paths for this library
#===============================================================================
lib_link_path = []
thermoLiqPropEnv.Prepend(LIBPATH = lib_link_path)

#===============================================================================
# Additions to link libraries for this library
#===============================================================================
lib_link = ['core','thermophysicalFunctions']
thermoLiqPropEnv.Append(LIBS = lib_link)

#===============================================================================
# Sources for this library
#===============================================================================
src_files = Split("""
  liquidProperties/liquidProperties.cpp
  H2O/H2O.cpp
  C7H16/C7H16.cpp
  C12H26/C12H26.cpp
  C10H22/C10H22.cpp
  C8H18/C8H18.cpp
  IC8H18/IC8H18.cpp
  C4H10O/C4H10O.cpp
  C2H6O/C2H6O.cpp
  IDEA/IDEA.cpp
  aC10H7CH3/aC10H7CH3.cpp
  bC10H7CH3/bC10H7CH3.cpp
  C8H10/C8H10.cpp
  C16H34/C16H34.cpp
  C9H20/C9H20.cpp
  C6H6/C6H6.cpp
  C7H8/C7H8.cpp
  C6H14/C6H14.cpp
  C13H28/C13H28.cpp
  C14H30/C14H30.cpp
  C3H8/C3H8.cpp
  C3H6O/C3H6O.cpp
  C2H6/C2H6.cpp
  CH3OH/CH3OH.cpp
  C2H5OH/C2H5OH.cpp
  Ar/Ar.cpp
  N2/N2.cpp
  MB/MB.cpp
  CH4N2O/CH4N2O.cpp
  nC3H8O/nC3H8O.cpp
  iC3H8O/iC3H8O.cpp
  """) 

#===============================================================================
# Build this library
#===============================================================================
libliquidProperties = thermoLiqPropEnv.SharedLibrary(target = 
'liquidProperties', source = src_files)

#===============================================================================
# Install this library
#===============================================================================
install_dir = thermoLiqPropEnv['LIB_PLATFORM_INSTALL']
thermoLiqPropEnv.Alias('install', install_dir)
thermoLiqPropEnv.Install(install_dir, libliquidProperties)

if (thermoLiqPropEnv['WHICH_OS'] == "darwin"):

  thermoLiqPropEnv.Append(SHLINKFLAGS ='-install_name @executable_path/../lib/libliquidProperties.dylib')
