# -*- mode: python -*-

from build import build_lib
Import('env')

target = 'liquidProperties'

sources = Split("""
liquidProperties/liquidProperties.cpp
H2O/H2O.cpp
C7H16/C7H16.cpp
C12H26/C12H26.cpp
C10H22/C10H22.cpp
C8H18/C8H18.cpp
IC8H18/IC8H18.cpp
C4H10O/C4H10O.cpp
C2H6O/C2H6O.cpp
IDEA/IDEA.cpp
aC10H7CH3/aC10H7CH3.cpp
bC10H7CH3/bC10H7CH3.cpp
C8H10/C8H10.cpp
C16H34/C16H34.cpp
C9H20/C9H20.cpp
C6H6/C6H6.cpp
C7H8/C7H8.cpp
C6H14/C6H14.cpp
C13H28/C13H28.cpp
C14H30/C14H30.cpp
C3H8/C3H8.cpp
C3H6O/C3H6O.cpp
C2H6/C2H6.cpp
CH3OH/CH3OH.cpp
C2H5OH/C2H5OH.cpp
Ar/Ar.cpp
N2/N2.cpp
MB/MB.cpp
CH4N2O/CH4N2O.cpp
nC3H8O/nC3H8O.cpp
iC3H8O/iC3H8O.cpp
""")

caelus_inc = [
'thermophysicalModels/thermophysicalFunctions/lnInclude'
]

caelus_libs = [
'core',
'thermophysicalFunctions'
]

build_lib(env,
          target=target,
          sources=sources,
          caelus_inc=caelus_inc,
          caelus_libs=caelus_libs)
