# -*- mode: python -*-

from build import build_lib
Import('env')

target = 'fvOptions'

sources = Split("""
fvOptions/fvOption.cpp
fvOptions/fvOptionList.cpp
fvOptions/fvIOoptionList.cpp
sources/general/semiImplicitSource/semiImplicitSource.cpp
sources/derived/actuationDiskSource/actuationDiskSource.cpp
sources/derived/explicitPorositySource/explicitPorositySource.cpp
sources/derived/meanVelocityForce/meanVelocityForce.cpp
sources/derived/meanVelocityForce/patchMeanVelocityForce/patchMeanVelocityForce.cpp
sources/derived/radialActuationDiskSource/radialActuationDiskSource.cpp
sources/derived/rotorDiskSource/rotorDiskSource.cpp
sources/derived/rotorDiskSource/bladeModel/bladeModel.cpp
sources/derived/rotorDiskSource/profileModel/profileModel.cpp
sources/derived/rotorDiskSource/profileModel/profileModelList.cpp
sources/derived/rotorDiskSource/profileModel/lookup/lookupProfile.cpp
sources/derived/rotorDiskSource/profileModel/series/seriesProfile.cpp
sources/derived/rotorDiskSource/trimModel/trimModel/trimModel.cpp
sources/derived/rotorDiskSource/trimModel/trimModel/trimModelNew.cpp
sources/derived/rotorDiskSource/trimModel/fixed/fixedTrim.cpp
sources/derived/rotorDiskSource/trimModel/targetCoeff/targetCoeffTrim.cpp
constraints/general/explicitSetValue/explicitSetValue.cpp
corrections/limitVelocity/limitVelocity.cpp
""")

caelus_inc = [
'core/lnInclude',
'sampling/lnInclude',
'thermophysicalModels/solidThermo/lnInclude',
'thermophysicalModels/basic/lnInclude',
'thermophysicalModels/specie/lnInclude',
'turbulenceModels/compressible/turbulenceModel/lnInclude',
'turbulenceModels'
]

caelus_libs = [
'core',
'sampling',
'incompressibleTurbulenceModel'
]

build_lib(env,
          target=target,
          sources=sources,
          caelus_inc=caelus_inc,
          caelus_libs=caelus_libs)
