# -*- mode: python -*-

from build import build_lib
Import('env')

target = 'fluidThermophysicalModels'

sources = Split("""
basicThermo/basicThermo.cpp
fluidThermo/fluidThermo.cpp
psiThermo/psiThermo.cpp
psiThermo/psiThermos.cpp
rhoThermo/rhoThermo.cpp
rhoThermo/rhoThermos.cpp
rhoThermo/liquidThermo.cpp
derivedFvPatchFields/fixedEnergy/fixedEnergyFvPatchScalarField.cpp
derivedFvPatchFields/gradientEnergy/gradientEnergyFvPatchScalarField.cpp
derivedFvPatchFields/mixedEnergy/mixedEnergyFvPatchScalarField.cpp
derivedFvPatchFields/energyJump/energyJump/energyJumpFvPatchScalarField.cpp
derivedFvPatchFields/energyJump/energyJumpAMI/energyJumpAMIFvPatchScalarField.cpp
derivedFvPatchFields/isentropicTotalTemperature/isentropicTotalTemperatureFvPatchScalarField.cpp
derivedFvPatchFields/temperatureDirectedInletOutletVelocity/temperatureDirectedInletOutletVelocityFvPatchVectorField.cpp
""")

caelus_inc = [
'thermophysicalModels/specie/lnInclude',
'thermophysicalModels/thermophysicalProperties/lnInclude'
]

caelus_libs = [
'core',
'specie',
'thermophysicalProperties'
]

build_lib(env,
          target=target,
          sources=sources,
          caelus_inc=caelus_inc,
          caelus_libs=caelus_libs)
