# -*- mode: python -*-

from build import build_lib
Import('env')

target = 'basicThermophysicalModels'

sources = Split("""
mixtures/basicMixture/basicMixture.cpp
mixtures/basicMixture/basicMixtures.cpp
basicThermo/basicThermo.cpp
basicThermo/basicThermoNew.cpp
psiThermo/basicPsiThermo/basicPsiThermo.cpp
psiThermo/basicPsiThermo/basicPsiThermoNew.cpp
psiThermo/hPsiThermo/hPsiThermos.cpp
psiThermo/hsPsiThermo/hsPsiThermos.cpp
psiThermo/ePsiThermo/ePsiThermos.cpp
rhoThermo/basicRhoThermo/basicRhoThermo.cpp
rhoThermo/basicRhoThermo/basicRhoThermoNew.cpp
rhoThermo/hRhoThermo/hRhoThermos.cpp
rhoThermo/hsRhoThermo/hsRhoThermos.cpp
derivedFvPatchFields/fixedEnthalpy/fixedEnthalpyFvPatchScalarField.cpp
derivedFvPatchFields/gradientEnthalpy/gradientEnthalpyFvPatchScalarField.cpp
derivedFvPatchFields/mixedEnthalpy/mixedEnthalpyFvPatchScalarField.cpp
derivedFvPatchFields/fixedInternalEnergy/fixedInternalEnergyFvPatchScalarField.cpp
derivedFvPatchFields/gradientInternalEnergy/gradientInternalEnergyFvPatchScalarField.cpp
derivedFvPatchFields/mixedInternalEnergy/mixedInternalEnergyFvPatchScalarField.cpp
derivedFvPatchFields/wallHeatTransfer/wallHeatTransferFvPatchScalarField.cpp
derivedFvPatchFields/isentropicTotalTemperature/isentropicTotalTemperatureFvPatchScalarField.cpp
derivedFvPatchFields/temperatureDirectedInletOutletVelocity/temperatureDirectedInletOutletVelocityFvPatchVectorField.cpp
""")

caelus_inc = [
'thermophysicalModels/specie/lnInclude'
]

caelus_libs = [
'core',
'specie'
]

build_lib(env,
          target=target,
          sources=sources,
          caelus_inc=caelus_inc,
          caelus_libs=caelus_libs)
