# -*- mode: python -*-

import utils
from build import build_app
Import('env')

target = 'decomposePar'

sources = Split("""
decomposePar.cpp
domainDecomposition.cpp
domainDecompositionMesh.cpp
domainDecompositionDistribute.cpp
dimFieldDecomposer.cpp
pointFieldDecomposer.cpp
lagrangianFieldDecomposer.cpp
""")

caelus_inc = [
'parallel/decompose/decompose/lnInclude',
'parallel/decompose/decompositionMethods/lnInclude',
'lagrangian/basic/lnInclude',
'regionModels/regionModel/lnInclude',
'dynamicMesh/dynamicMesh/lnInclude',
]

caelus_libs = [
'core',
'genericPatchFields',
'lagrangian',
'decompose',
'decompositionMethods',
'scotchDecomp',
'metisDecomp',
'regionModels',
'dynamicMesh'
]

ostype = utils.ostype()
prepend_args = {}
if ostype == 'windows':
   prepend_args = {'LINKFLAGS' :
      '-u genericPatchFieldsLoad -u scotchDecompLoad -u metisDecompLoad'
}

build_app(env,
          target=target,
          sources=sources,
          caelus_inc=caelus_inc,
          caelus_libs=caelus_libs,
          prepend_args=prepend_args)
