# -*- mode: python -*-

import os
from build import build_app
Import('env')

target = 'extrudeMesh'

sources = Split("""
extrudedMesh/extrudedMesh.cpp
extrudeMesh.cpp
""")

caelus_inc = [
'dynamicMesh/dynamicMesh/lnInclude',
'surfMesh/lnInclude',
'mesh/extrudeModel/lnInclude'
]

caelus_libs = [
'core',
'surfMesh',
'dynamicMesh',
'extrudeModel'
]

local_dir = env.Dir(".").srcnode().abspath
model_dir = os.path.join(local_dir, '../extrudeModel/lnInclude')
mesh_dir = os.path.join(local_dir,'extrudedMesh')

append_args = {}
append_args = { 'CPPPATH' : [
                  os.path.normpath(model_dir),
                  os.path.normpath(mesh_dir)
               ]
            }

build_app(env,
          target=target,
          sources=sources,
          caelus_inc=caelus_inc,
          caelus_libs=caelus_libs,
          append_args=append_args)
