# -*- mode: python -*-

import os
import utils
from build import build_app
Import('env')

# Build Fluent mesh converter
ostype = utils.ostype()

if ostype == "windows":
    src_from_flex = ['windows/fluentMeshToCAELUS.cpp']
else:
    src = 'fluentMeshToCAELUS.ll'
    tgt = 'posix/fluentMeshToCAELUS.cpp'
    flex_env = env.Clone()
    flex_env.CXXFile(tgt, src, LEXFLAGS='-+')
    src_from_flex = [tgt]


target = 'fluentMeshToCAELUS'

sources = Split("""
extrudedTriangleCellShape.cpp
extrudedQuadCellShape.cpp
create3DCellShape.cpp
""") + src_from_flex

caelus_inc = [
'dynamicMesh/dynamicMesh/lnInclude'
]

caelus_libs = [
'core',
'dynamicMesh'
]

local_dir = env.Dir(".").srcnode().abspath

append_args = {}
append_args = { "CPPPATH" : [os.path.normpath(local_dir)] }

build_app(env,
          target=target,
          sources=sources,
          caelus_inc=caelus_inc,
          caelus_libs=caelus_libs,
          append_args=append_args)
