# -*- mode: python -*-

from build import build_app
Import('env')

target = 'setSet'

sources = Split("""
writePointSet.cpp
  writeFuns.cpp
  writePatch.cpp
  setSet.cpp
""")

caelus_inc = [
]

caelus_libs = [
'core'
]

build_app(env,
          target=target,
          sources=sources,
          caelus_inc=caelus_inc,
          caelus_libs=caelus_libs)
