# -*- mode: python -*-

from build import build_lib
Import('env')

target = 'specie'

sources = Split("""
atomicWeights/atomicWeights.cpp
specie/specie.cpp
equationOfState/perfectGas/perfectGas.cpp
equationOfState/incompressible/incompressible.cpp
equationOfState/isobaricPerfectGas/isobaricPerfectGas.cpp
reaction/reactions/makeReactionThermoReactions.cpp
reaction/reactions/makeLangmuirHinshelwoodReactions.cpp
""")

caelus_inc = []

caelus_libs = [
'core'
]

build_lib(env,
          target=target,
          sources=sources,
          caelus_inc=caelus_inc,
          caelus_libs=caelus_libs)
