#Copyright (C) 2014 Applied CCM
import subprocess
Import('globalEnv')

# Clone the global environment so changes made he are not pass onto subsequent 
# libraries
distribEnv = globalEnv.Clone()

# Path to source
src = distribEnv['LIB_SRC']

#===============================================================================
# Additions to compiler flags for this library
#===============================================================================
distribEnv.Append(CCFLAGS = '')

#===============================================================================
# Additions to include directories for this library
#===============================================================================
lib_inc = ['lnInclude',
src + '/parallel/decompose/decompositionMethods/lnInclude'
]
distribEnv.Prepend(CPPPATH = lib_inc)

#===============================================================================
# Additions to link library paths for this library
#===============================================================================
lib_link_path = []
distribEnv.Prepend(LIBPATH = lib_link_path)

#===============================================================================
# Additions to link libraries for this library
#===============================================================================
lib_link = ['decompositionMethods', 'core']
distribEnv.Append(LIBS = lib_link)

#===============================================================================
# Sources for this library
#===============================================================================
src_files = Split("""
    distributedTriSurfaceMesh/distributedTriSurfaceMesh.cpp
              """)

#===============================================================================
# Build this library
#===============================================================================
libdistributed = distribEnv.SharedLibrary(target = 'distributed', 
source = src_files)

#===============================================================================
# Install this library
#===============================================================================
install_dir = distribEnv['LIB_PLATFORM_INSTALL']
distribEnv.Alias('install', install_dir)
distribEnv.Install(install_dir, libdistributed)

if (distribEnv['WHICH_OS'] == "darwin"):

  distribEnv.Append(SHLINKFLAGS ='-install_name @' + distribEnv['LIB_PLATFORM_INSTALL'] + '/libdistributed.dylib')
