# -*- mode: python -*-

from build import build_lib
Import('env')

target = 'distributed'

sources = Split("""
distributedTriSurfaceMesh/distributedTriSurfaceMesh.cpp
""")

caelus_inc = [
'parallel/decompose/decompositionMethods/lnInclude'
]

caelus_libs = [
'core',
'decompositionMethods'
]

build_lib(env,
          target=target,
          sources=sources,
          caelus_inc=caelus_inc,
          caelus_libs=caelus_libs)
