# -*- mode: python -*-

import utils
from build import build_app
Import('env')

target = 'caelusDataToEnsight'

sources = Split("""
itoa.cpp
ensightMesh.cpp
ensightParticlePositions.cpp
caelusToEnsight.cpp
""")

caelus_inc = [
'lagrangian/basic/lnInclude',
'sampling/lnInclude'
]

caelus_libs = [
'core',
'genericPatchFields',
'lagrangian',
'sampling']

ostype = utils.ostype()
prepend_args = {}
if ostype == 'windows':
   prepend_args = {'LINKFLAGS' :
         '-u genericPatchFieldsLoad'
}

build_app(env,
          target=target,
          sources=sources,
          caelus_inc=caelus_inc,
          caelus_libs=caelus_libs,
          prepend_args=prepend_args)
