# -*- mode: python -*-

import utils
from build import build_app
Import('env')

target = 'stressComponents'

sources = Split("""
stressComponents.cpp
""")

caelus_inc = [
'turbulenceModels/RAS', 
'transportModels',
'transportModels/incompressible/lnInclude'
]

caelus_libs = [
'core',
'genericPatchFields',
'incompressibleRASModels',
'incompressibleTransportModels'
]

ostype = utils.ostype()
prepend_args = {}
if ostype == 'windows':
   prepend_args = {'LINKFLAGS' :
         '-u genericPatchFieldsLoad'
}

build_app(env,
          target=target,
          sources=sources,
          caelus_inc=caelus_inc,
          caelus_libs=caelus_libs,
          prepend_args=prepend_args)
