# -*- mode: python -*-

import os
Import('env')

subdirs = Split("""
   basic/potentialSolver
   heatTransfer/buoyantBoussinesqSimpleSolver
   heatTransfer/buoyantSimpleSolver
   incompressible/simpleSolver
   incompressible/simpleSolver/SRFSimpleSolver
   incompressible/pimpleSolver
   incompressible/pimpleSolver/SRFPimpleSolver
   incompressible/pisoSolver
   compressible/PBNS/cpbnsLTS
   compressible/PBNS/cpbnsPIMPLE
   compressible/DBNS/explicitDBNSSolver
   compressible/DBNS/explicitDBNSSRFSolver
   combustion/reactingSolver
   multiphase/vof/vofSolver
   multiphase/vof/vofSolver/porousWaveSolver
   multiphase/vof/vofLPTSolver
   multiphase/lagrangian/pimpleParcelSolver
   multiphase/vof/isoVofSolver
""")

for d in subdirs:
    SConscript(os.path.join(d,'SConscript'),
               exports=['env'])
