# -*- mode: python -*-

from build import build_lib
Import('env')

target = 'distributionModels'

sources = Split("""
distributionModel/distributionModel.cpp
distributionModel/distributionModelNew.cpp
exponential/exponential.cpp
fixedValue/fixedValue.cpp
general/general.cpp
multiNormal/multiNormal.cpp
normal/normal.cpp
RosinRammler/RosinRammler.cpp
uniform/uniform.cpp
""")

caelus_inc = []

caelus_libs = [
'core'
]

build_lib(env,
          target=target,
          sources=sources,
          caelus_inc=caelus_inc,
          caelus_libs=caelus_libs)
