#Copyright (C) 2014 Applied CCM
import subprocess
Import('globalEnv')

# Clone the global environment so changes made he are not pass onto subsequent 
# libraries
lagDistModelsEnv = globalEnv.Clone()

#===============================================================================
# Additions to compiler flags for this library
#===============================================================================
lagDistModelsEnv.Append(CXXFLAGS = '')

#===============================================================================
# Additions to include directories for this library
#===============================================================================
lib_inc = ['lnInclude']
lagDistModelsEnv.Prepend(CPPPATH = lib_inc)

#===============================================================================
# Additions to link library paths for this library
#===============================================================================
lib_link_path = []
lagDistModelsEnv.Prepend(LIBPATH = lib_link_path)

#===============================================================================
# Additions to link libraries for this library
#===============================================================================
lib_link = ['core']
lagDistModelsEnv.Append(LIBS = lib_link)

#===============================================================================
# Sources for this library
#===============================================================================
src_files = Split("""
  distributionModel/distributionModel.cpp
  distributionModel/distributionModelNew.cpp
  exponential/exponential.cpp
  fixedValue/fixedValue.cpp
  general/general.cpp
  multiNormal/multiNormal.cpp
  normal/normal.cpp
  RosinRammler/RosinRammler.cpp
  uniform/uniform.cpp
  """)

#===============================================================================
# Build this library
#===============================================================================
libdistributionModels = lagDistModelsEnv.SharedLibrary(target = 
'distributionModels', source = src_files)

#===============================================================================
# Install this library
#===============================================================================
install_dir = lagDistModelsEnv['LIB_PLATFORM_INSTALL']
lagDistModelsEnv.Alias('install', install_dir)
lagDistModelsEnv.Install(install_dir, libdistributionModels)

if (lagDistModelsEnv['WHICH_OS'] == "darwin"):

  lagDistModelsEnv.Append(SHLINKFLAGS ='-install_name @' + lagDistModelsEnv['LIB_PLATFORM_INSTALL'] + '/libdistributionModels.dylib')
