#Copyright (C) 2014 Applied CCM
import subprocess
Import('globalEnv')

# Clone the global environment so changes made he are not pass onto subsequent 
# libraries
turbDerPatFieldsEnv = globalEnv.Clone()

# Path to source
src = turbDerPatFieldsEnv['LIB_SRC']

#===============================================================================
# Additions to compiler flags for this library
#===============================================================================
turbDerPatFieldsEnv.Append(CCFLAGS = '')

#===============================================================================
# Additions to include directories for this library
#===============================================================================
lib_inc = ['lnInclude', src + '/transportModels', src + '/turbulenceModels',   
src + '/thermophysicalModels/basic/lnInclude',
src + '/thermophysicalModels/specie/lnInclude',
src + '/transportModels/incompressible/singlePhaseTransportModel' 
]
turbDerPatFieldsEnv.Prepend(CPPPATH = lib_inc)
          
#===============================================================================
# Additions to link library paths for this library
#===============================================================================
lib_link_path = [] 
turbDerPatFieldsEnv.Prepend(LIBPATH = lib_link_path)

#===============================================================================
# Additions to link libraries for this library
#===============================================================================
lib_link = ['core','basicThermophysicalModels','specie',
'compressibleTurbulenceModel','incompressibleTurbulenceModel'] 
turbDerPatFieldsEnv.Append(LIBS = lib_link)
      
#===============================================================================
# Sources for this library
#===============================================================================
src_files = Split("""
  porousBafflePressure/porousBafflePressureFvPatchFields.cpp
  """)

#===============================================================================
# Build this library
#===============================================================================
libturbulenceDerivedFvPatchFields = turbDerPatFieldsEnv.SharedLibrary(target = 
'turbulenceDerivedFvPatchFields', source = src_files)

#===============================================================================
# Install this library
#===============================================================================
install_dir = turbDerPatFieldsEnv['LIB_PLATFORM_INSTALL']
turbDerPatFieldsEnv.Alias('install', install_dir)
turbDerPatFieldsEnv.Install(install_dir, libturbulenceDerivedFvPatchFields)

if (turbDerPatFieldsEnv['WHICH_OS'] == "darwin"):

  turbDerPatFieldsEnv.Append(SHLINKFLAGS ='-install_name @' + turbDerPatFieldsEnv['LIB_PLATFORM_INSTALL'] + '/libturbulenceDerivedFvPatchFields.dylib')
