# -*- mode: python -*-

from build import build_lib
Import('env')

target = 'turbulenceDerivedFvPatchFields'

sources = Split("""
porousBafflePressure/porousBafflePressureFvPatchFields.cpp
fixedShearStress/fixedShearStressFvPatchVectorField.cpp
wallFunctions/kqRWFs/kqRWF/kqRWFFvPatchFields.cpp
""")

caelus_inc = [
'transportModels',
'turbulenceModels',
'thermophysicalModels/basic/lnInclude',
'thermophysicalModels/specie/lnInclude',
'transportModels/incompressible/singlePhaseTransportModel'
]

caelus_libs = [
'core',
'fluidThermophysicalModels',
'specie',
'compressibleTurbulenceModel',
'incompressibleTurbulenceModel'
]

build_lib(env,
          target=target,
          sources=sources,
          caelus_inc=caelus_inc,
          caelus_libs=caelus_libs)
