# -*- mode: python -*-

import os
import utils
from build import build_app
Import('env')

target = "vofSolver"

sources = Split("""
vofSolver.cpp
""")

caelus_inc = [
'core/lnInclude',
'turbulenceModels/',
'turbulenceModels/incompressible/turbulenceModel/lnInclude',
'transportModels',
'transportModels/incompressible/singlePhaseTransportModel',
'transportModels/incompressible/lnInclude',
'transportModels/interfaceProperties/lnInclude',
'fvOptions/lnInclude',
'sampling/lnInclude',
'dynamicMesh/dynamicMesh/lnInclude',
'dynamicMesh/dynamicFvMesh/lnInclude',
'waves/waves/lnInclude',
'waves/wavesSampling/lnInclude',
env['GSL_INC_PATH']
]

caelus_libs = [
'core',
'incompressibleTurbulenceModel',
'incompressibleRASModels',
'incompressibleLESModels',
'incompressibleVLESModels',
'incompressibleTransportModels',
'turbulenceDerivedFvPatchFields',
'interfaceProperties',
'twoPhaseInterfaceProperties',
'fvOptions',
'sampling',
'dynamicMesh',
'dynamicFvMesh',
'topoChangerFvMesh',
'waves',
'wavesSampling',
'pgsl'
]

append_args = {}

ostype = utils.ostype()
prepend_args = {}
if ostype == 'windows':
   prepend_args = {'LINKFLAGS' :
            '-u incompressibleRASModelsLoad -u incompressibleLESModelsLoad -u incompressibleVLESModelsLoad -u interfacePropertiesLoad -u turbulenceDerivedFvPatchFieldsLoad'
}

build_app(env,
          target=target,
          sources=sources,
          caelus_inc=caelus_inc,
          caelus_libs=caelus_libs,
          prepend_args=prepend_args,
          append_args=append_args)
