#Copyright (C) 2014 Applied CCM
import subprocess
Import('globalEnv')

# Clone the global environment so changes made he are not pass onto subsequent 
# libraries
rotateMeshEnv = globalEnv.Clone()

# Path to source
src = rotateMeshEnv['LIB_SRC']

rotateMeshEnv.Append(CXXFLAGS = '')
#===============================================================================
# Additions to compiler flags for this executable
#===============================================================================
rotateMeshEnv.Append(CCFLAGS = '')

#===============================================================================
# Additions to include directories for this executable
#===============================================================================
lib_inc = []

rotateMeshEnv.Prepend(CPPPATH = lib_inc)

#===============================================================================
# Additions to link library paths for this executable
#===============================================================================
lib_link_path = []
rotateMeshEnv.Prepend(LIBPATH = lib_link_path)

#===============================================================================
# Additions to link libraries for this executable
#===============================================================================
if rotateMeshEnv['WHICH_OS'] == "windows":
  lib_link = []
else:
  lib_link = []
  
rotateMeshEnv.Append(LIBS = lib_link)

#===============================================================================
# Sources for this executable
#===============================================================================
src_files = Split("""
  rotateMesh.cpp
  """)

#===============================================================================
# Build this executable
#===============================================================================
binrotateMesh = rotateMeshEnv.Program(target = 
'rotateMesh', source = src_files)

#===============================================================================
# Install this executable
#===============================================================================
install_dir = rotateMeshEnv['BIN_PLATFORM_INSTALL']
rotateMeshEnv.Alias('install', install_dir)
rotateMeshEnv.Install(install_dir, binrotateMesh)
