# -*- mode: python -*-

from build import build_lib
Import('env')

target = 'thermalBaffleModels'

sources = Split("""
thermalBaffleModel/thermalBaffleModel.cpp
thermalBaffleModel/thermalBaffleModelNew.cpp
thermalBaffle/thermalBaffle.cpp
noThermo/noThermo.cpp
derivedFvPatchFields/thermalBaffle/thermalBaffleFvPatchScalarField.cpp
""")

caelus_inc = [
'regionModels/regionModel/lnInclude',
'thermophysicalModels/basic/lnInclude',
'thermophysicalModels/specie/lnInclude',
'thermophysicalModels/solidThermo/lnInclude',
'turbulenceModels/compressible/turbulenceModel/lnInclude',
'thermophysicalModels/radiation/lnInclude',
'dynamicMesh/dynamicMesh/lnInclude',
'mesh/extrudeModel/lnInclude'
]

caelus_libs = [
'core',
'regionModels',
'solidThermo',
'compressibleTurbulenceModel',
'radiationModels',
'dynamicMesh'
]

build_lib(env,
          target=target,
          sources=sources,
          caelus_inc=caelus_inc,
          caelus_libs=caelus_libs)
