# -*- mode: python -*-

from build import build_lib
Import('env')

target = 'thermoBaffleModels'

sources = Split("""
thermoBaffleModel/thermoBaffleModel.cpp
thermoBaffleModel/thermoBaffleModelNew.cpp
thermoBaffle2D/thermoBaffle2D.cpp
noThermo/noThermo.cpp
derivedFvPatchFields/temperatureThermoBaffle/temperatureThermoBaffleFvPatchScalarField.cpp
""")

caelus_inc = [
'sampling/lnInclude',
'AMIInterpolation/lnInclude',
'regionModels/regionModel/lnInclude',
'thermophysicalModels/basic/lnInclude',
'thermophysicalModels/specie/lnInclude',
'thermophysicalModels/solid/lnInclude',
'thermophysicalModels/basicSolidThermo/lnInclude',
'turbulenceModels/compressible/turbulenceModel/lnInclude'
]

caelus_libs = [
'core',
'solid',
'regionModels',
'basicSolidThermo',
'compressibleTurbulenceModel'
]

build_lib(env,
          target=target,
          sources=sources,
          caelus_inc=caelus_inc,
          caelus_libs=caelus_libs)
