# -*- mode: python -*-

from build import build_lib
Import('env')

target = 'compressibleRASModels'

sources = Split("""
RASModel/compressibleRASModel.cpp
laminar/compressibleRASLaminar.cpp
realizableKE/compressibleRealizableKE.cpp
kEpsilon/compressiblekEpsilon.cpp
SpalartAllmaras/compressibleSpalartAllmaras.cpp
kOmegaSST/compressiblekOmegaSST.cpp
kOmegaSSTSAS/compressiblekOmegaSSTSAS.cpp
gammaReTheta/compressibleGammaReTheta.cpp
""")

caelus_inc = [
'turbulenceModels',
'thermophysicalModels/basic/lnInclude',
'thermophysicalModels/solidThermo/lnInclude'
]

caelus_libs = [
'core',
'specie',
'compressibleTurbulenceModel'
]

build_lib(env,
          target=target,
          sources=sources,
          caelus_inc=caelus_inc,
          caelus_libs=caelus_libs)
