#Copyright (C) 2014 Applied CCM
import subprocess
Import('globalEnv')

# Clone the global environment so changes made he are not pass onto subsequent 
# libraries
genPatFieldEnv = globalEnv.Clone()

# Path to source
src = genPatFieldEnv['LIB_SRC']

#===============================================================================
# Additions to compiler flags for this library
#===============================================================================
genPatFieldEnv.Append(CXXFLAGS = '')

#===============================================================================
# Additions to include directories for this library
#===============================================================================
lib_inc = ['lnInclude'] 
genPatFieldEnv.Prepend(CPPPATH = lib_inc)

#===============================================================================
# Additions to link library paths for this library
#===============================================================================
lib_link_path = []
genPatFieldEnv.Prepend(LIBPATH = lib_link_path)

#===============================================================================
# Additions to link libraries for this library
#===============================================================================
lib_link = ['core']
genPatFieldEnv.Append(LIBS = lib_link)

#===============================================================================
# Sources for this library
#===============================================================================
src_files = Split("""
  genericFvPatchField/genericFvPatchFields.cpp
  genericPointPatchField/genericPointPatchFields.cpp
  """)

#===============================================================================
# Build this library
#===============================================================================
libgenericPatchFields = genPatFieldEnv.SharedLibrary(target = 
'genericPatchFields', source = src_files)

#===============================================================================
# Install this library
#===============================================================================
install_dir = genPatFieldEnv['LIB_PLATFORM_INSTALL']
genPatFieldEnv.Alias('install', install_dir)
genPatFieldEnv.Install(install_dir, libgenericPatchFields)

if (genPatFieldEnv['WHICH_OS'] == "darwin"):

  genPatFieldEnv.Append(SHLINKFLAGS ='-install_name @executable_path/../lib/libgenericPatchFields.dylib')
