# -*- mode: python -*-

import utils
from build import build_app
Import('env')

target = 'probeLocations'

sources = Split("""
probeLocations.cpp
""")

caelus_inc = [
'sampling/lnInclude',
'lagrangian/basic/lnInclude'
]

caelus_libs = [
'core',
'genericPatchFields',
'sampling',
'lagrangian'
]

ostype = utils.ostype()
prepend_args = {}
if ostype == 'windows':
   prepend_args = {'LINKFLAGS' :
         '-u genericPatchFieldsLoad'
}

build_app(env,
          target=target,
          sources=sources,
          caelus_inc=caelus_inc,
          caelus_libs=caelus_libs,
          prepend_args=prepend_args)
