#Copyright (C) 2014 Applied CCM
import subprocess
Import('globalEnv')

# Clone the global environment so changes made he are not pass onto subsequent 
# libraries
reconstructEnv = globalEnv.Clone()

# Path to source
src = reconstructEnv['LIB_SRC']

#===============================================================================
# Additions to compiler flags for this library
#===============================================================================
reconstructEnv.Append(CCFLAGS = '')

#===============================================================================
# Additions to include directories for this library
#===============================================================================
lib_inc = ['lnInclude', src + '/lagrangian/basic/lnInclude']
reconstructEnv.Prepend(CPPPATH = lib_inc)

#===============================================================================
# Additions to link library paths for this library
#===============================================================================
lib_link_path = []
reconstructEnv.Prepend(LIBPATH = lib_link_path)

#===============================================================================
# Additions to link libraries for this library
#===============================================================================
lib_link = ['core', 'lagrangian']
reconstructEnv.Append(LIBS = lib_link)

#===============================================================================
# Sources for this library
#===============================================================================
src_files = Split("""
  processorMeshes.cpp
  fvFieldReconstructor.cpp
  pointFieldReconstructor.cpp
  reconstructLagrangianPositions.cpp
  """)

#===============================================================================
# Build this library
#===============================================================================
libreconstruct = reconstructEnv.SharedLibrary(target = 'reconstruct', 
source = src_files)

#===============================================================================
# Install this library
#===============================================================================
install_dir = reconstructEnv['LIB_PLATFORM_INSTALL']
reconstructEnv.Alias('install', install_dir)
reconstructEnv.Install(install_dir, libreconstruct)

if (reconstructEnv['WHICH_OS'] == "darwin"):

  reconstructEnv.Append(SHLINKFLAGS ='-install_name @executable_path/../lib/libreconstruct.dylib')
