# -*- mode: python -*-

from build import build_lib
Import('env')

target = 'reconstruct'

sources = Split("""
processorMeshes.cpp
fvFieldReconstructor.cpp
pointFieldReconstructor.cpp
reconstructLagrangianPositions.cpp
""")

caelus_inc = [
'lagrangian/basic/lnInclude'
]

caelus_libs = [
'core',
'lagrangian'
]

build_lib(env,
          target=target,
          sources=sources,
          caelus_inc=caelus_inc,
          caelus_libs=caelus_libs)
