#Copyright (C) 2014 Applied CCM
import subprocess
Import('globalEnv')

# Clone the global environment so changes made he are not pass onto subsequent 
# libraries
setFieldsEnv = globalEnv.Clone()

# Path to source
src = setFieldsEnv['LIB_SRC']

#===============================================================================
# Additions to compiler flags for this executable
#===============================================================================
setFieldsEnv.Append(CCFLAGS = '')

#===============================================================================
# Additions to include directories for this executable
#===============================================================================
lib_inc = []        

setFieldsEnv.Prepend(CPPPATH = lib_inc)

#===============================================================================
# Additions to link library paths for this executable
#===============================================================================
lib_link_path = []
setFieldsEnv.Prepend(LIBPATH = lib_link_path)

#===============================================================================
# Additions to link libraries for this executable
#===============================================================================
if setFieldsEnv['WHICH_OS'] == "windows":
  setFieldsEnv.Prepend(LINKFLAGS = ' -u genericPatchFieldsLoad')

lib_link = ['genericPatchFields']
    
setFieldsEnv.Append(LIBS = lib_link)
    
#===============================================================================
# Sources for this executable
#===============================================================================
src_files = Split("""  
  setFields.cpp
  """)

#===============================================================================
# Build this executable
#===============================================================================
binsetFields = setFieldsEnv.Program(target = 
'setFields', source = src_files)

#===============================================================================
# Install this executable
#===============================================================================
install_dir = setFieldsEnv['BIN_PLATFORM_INSTALL']
setFieldsEnv.Alias('install', install_dir)
setFieldsEnv.Install(install_dir, binsetFields)
