# -*- mode: python -*-

from build import build_lib
Import('env')

target = 'barotropicCompressibilityModel'

sources = Split("""
barotropicCompressibilityModel/barotropicCompressibilityModel.cpp
barotropicCompressibilityModel/barotropicCompressibilityModelNew.cpp
linear/linearCompressibility.cpp
Wallis/Wallis.cpp
Chung/Chung.cpp
""")

caelus_inc = []

caelus_libs = [
'core'
]

build_lib(env,
          target=target,
          sources=sources,
          caelus_inc=caelus_inc,
          caelus_libs=caelus_libs)
