# -*- mode: python -*-

import utils
from build import build_app
Import('env')

target = 'caelusToVTK'

sources = Split("""
surfaceMeshWriter.cpp
caelusToVTK.cpp
internalWriter.cpp
lagrangianWriter.cpp
patchWriter.cpp
writeFuns.cpp
writeFaceSet.cpp
writePointSet.cpp
writeSurfFields.cpp
vtkMesh.cpp
vtkTopo.cpp
""")

caelus_inc = [
'lagrangian/basic/lnInclude'
]

caelus_libs = [
'core',
'genericPatchFields',
'lagrangian'
]

ostype = utils.ostype()
prepend_args = {}
if ostype == 'windows':
   prepend_args = {'LINKFLAGS' :
         '-u genericPatchFieldsLoad'
}

build_app(env,
          target=target,
          sources=sources,
          caelus_inc=caelus_inc,
          caelus_libs=caelus_libs,
          prepend_args=prepend_args)
