# -*- mode: python -*-

import os
import utils
from build import build_app
Import('env')

target = 'createBaffles'

sources = Split("""
faceSelection/faceSelection.cpp
faceSelection/faceZoneSelection.cpp
faceSelection/searchableSurfaceSelection.cpp
createBaffles.cpp
""")

caelus_inc = [
'dynamicMesh/dynamicMesh/lnInclude'
]

caelus_libs = [
'core',
'dynamicMesh',
'genericPatchFields'
]

local_dir = env.Dir(".").srcnode().abspath
face_sel_dir = os.path.join(local_dir, 'faceSelection')

append_args = {}
append_args = { 'CPPPATH' : [os.path.normpath(face_sel_dir)] }

ostype = utils.ostype()
prepend_args = {}
if ostype == 'windows':
   prepend_args = {'LINKFLAGS' :
         '-u genericPatchFieldsLoad'
}

build_app(env,
          target=target,
          sources=sources,
          caelus_inc=caelus_inc,
          caelus_libs=caelus_libs,
          prepend_args=prepend_args,
          append_args=append_args)
