#Copyright (C) 2014 Applied CCM
import subprocess
Import('globalEnv')

# Clone the global environment so changes made he are not pass onto subsequent 
# libraries
pCorrSimpleSolEnv = globalEnv.Clone()

# Path to source
src = pCorrSimpleSolEnv['LIB_SRC']

#===============================================================================
# Additions to compiler flags for this executable
#===============================================================================
pCorrSimpleSolEnv.Append(CCFLAGS = '')

#===============================================================================
# Additions to include directories for this executable
#===============================================================================
lib_inc = [pCorrSimpleSolEnv['LIB_SRC'] +  '/turbulenceModels',
src + '/turbulenceModels/incompressible/turbulenceModel/lnInclude', 
src + '/turbulenceModels/incompressible/RAS/RASModel', 
src + '/turbulenceModels/incompressible/RAS/lnInclude',
src + '/transportModels',
src + '/transportModels/incompressible/singlePhaseTransportModel',
src + '/transportModels/incompressible/lnInclude',
src + '/fvOptions/lnInclude',
src + '/sampling/lnInclude'
]
pCorrSimpleSolEnv.Prepend(CPPPATH = lib_inc)

#===============================================================================
# Additions to link library paths for this executable
#===============================================================================
lib_link_path = []
pCorrSimpleSolEnv.Prepend(LIBPATH = lib_link_path)

#===============================================================================
# Additions to link libraries for this executable
#===============================================================================
if pCorrSimpleSolEnv['WHICH_OS'] == "windows":
  pCorrSimpleSolEnv.Prepend(LINKFLAGS = ' -u incompressibleRASModelsLoad')

lib_link = ['incompressibleTurbulenceModel', 'incompressibleRASModels',
'incompressibleTransportModels', 'fvOptions', 'sampling']
  
pCorrSimpleSolEnv.Append(LIBS = lib_link)

#===============================================================================
# Sources for this executable
#===============================================================================
src_files = Split("""
  pCorrSimple.cpp
  """)

#===============================================================================
# Build this executable
#===============================================================================
binpCorrSimpleSol = pCorrSimpleSolEnv.Program(target = 'pCorrSimple',
source = src_files)

#===============================================================================
# Install this executable
#===============================================================================
install_dir = pCorrSimpleSolEnv['BIN_PLATFORM_INSTALL']
pCorrSimpleSolEnv.Alias('install', install_dir)
pCorrSimpleSolEnv.Install(install_dir, binpCorrSimpleSol)
