#Copyright (C) 2014 Applied CCM
import subprocess
Import('globalEnv')

# Clone the global environment so changes made he are not pass onto subsequent 
# libraries
refineHexMeshEnv = globalEnv.Clone()

# Path to source
src = refineHexMeshEnv['LIB_SRC']

#===============================================================================
# Additions to compiler flags for this executable
#===============================================================================
refineHexMeshEnv.Append(CCFLAGS = '')

#===============================================================================
# Additions to include directories for this executable
#===============================================================================
lib_inc = [src + '/dynamicMesh/lnInclude']
refineHexMeshEnv.Prepend(CPPPATH = lib_inc)

#===============================================================================
# Additions to link library paths for this executable
#===============================================================================
lib_link_path = []
refineHexMeshEnv.Prepend(LIBPATH = lib_link_path)

#===============================================================================
# Additions to link libraries for this executable
#===============================================================================
if refineHexMeshEnv['WHICH_OS'] == "windows":
  refineHexMeshEnv.Prepend(LINKFLAGS = ' -u genericPatchFieldsLoad')

lib_link = ['dynamicMesh','genericPatchFields']
     

refineHexMeshEnv.Append(LIBS = lib_link)

#===============================================================================
# Sources for this executable
#===============================================================================
src_files = Split("""
  refineHexMesh.cpp
  """)

#===============================================================================
# Build this executable
#===============================================================================
binrefineHexMesh = refineHexMeshEnv.Program(target = 'refineHexMesh', 
source = src_files)

#===============================================================================
# Install this executable
#===============================================================================
install_dir = refineHexMeshEnv['BIN_PLATFORM_INSTALL']
refineHexMeshEnv.Alias('install', install_dir)
refineHexMeshEnv.Install(install_dir, binrefineHexMesh)
