#Copyright (C) 2014 Applied CCM
import subprocess
Import('globalEnv')

# Clone the global environment so changes made he are not pass onto subsequent 
# libraries
inter2PropEnv = globalEnv.Clone()

# Path to source
src = inter2PropEnv['LIB_SRC']

#===============================================================================
# Additions to compiler flags for this library
#===============================================================================
inter2PropEnv.Append(CCFLAGS = '')

#===============================================================================
# Additions to include directories for this library
#===============================================================================
lib_inc = ['lnInclude',
src + '/transportModels/interfaceProperties/lnInclude'     
]
inter2PropEnv.Prepend(CPPPATH = lib_inc)
      
#===============================================================================
# Additions to link library paths for this library
#===============================================================================
lib_link_path = []
inter2PropEnv.Prepend(LIBPATH = lib_link_path)

#===============================================================================
# Additions to link libraries for this library
#===============================================================================
lib_link = ['core']
inter2PropEnv.Append(LIBS = lib_link)
   
#===============================================================================
# Sources for this library
#===============================================================================
src_files = Split("""
  alphaContactAngle/alphaContactAngle/alphaContactAngleFvPatchScalarField.cpp
  alphaContactAngle/constantAlphaContactAngle/constantAlphaContactAngleFvPatchScalarField.cpp
  alphaContactAngle/dynamicAlphaContactAngle/dynamicAlphaContactAngleFvPatchScalarField.cpp
  alphaContactAngle/timeVaryingAlphaContactAngle/timeVaryingAlphaContactAngleFvPatchScalarField.cpp
  alphaFixedPressure/alphaFixedPressureFvPatchScalarField.cpp
  """)

#===============================================================================
# Build this library
#===============================================================================
libtwoPhaseInterfaceProperties = inter2PropEnv.SharedLibrary(target = 
'twoPhaseInterfaceProperties', source = src_files)

#===============================================================================
# Install this library
#===============================================================================
install_dir = inter2PropEnv['LIB_PLATFORM_INSTALL']
inter2PropEnv.Alias('install', install_dir)
inter2PropEnv.Install(install_dir, libtwoPhaseInterfaceProperties)

if (inter2PropEnv['WHICH_OS'] == "darwin"):

  inter2PropEnv.Append(SHLINKFLAGS ='-install_name @executable_path/../lib/libtwoPhaseInterfaceProperties.dylib')
