#Copyright (C) 2014 Applied CCM
import subprocess
Import('globalEnv')

# Clone the global environment so changes made he are not pass onto subsequent 
# libraries
OSspecEnv = globalEnv.Clone()

#===============================================================================
# Additions to compiler flags for this library
#===============================================================================
OSspecEnv.Append(CCFLAGS = '')

#===============================================================================
# Additions to include directories for this library
#===============================================================================
lib_inc = []
OSspecEnv.Prepend(CPPPATH = lib_inc)

#===============================================================================
# Additions to link library paths for this library
#===============================================================================
lib_link_path = []
OSspecEnv.Prepend(LIBPATH = lib_link_path)

#===============================================================================
# Additions to link libraries for this library
#===============================================================================
lib_link = []
OSspecEnv.Append(LIBS = lib_link)

#===============================================================================
# Sources for this library
#===============================================================================
src_files = Split("""
  signals/sigFpe.cpp
  signals/sigSegv.cpp
  signals/sigInt.cpp
  signals/sigQuit.cpp
  signals/sigStopAtWriteNow.cpp
  signals/sigWriteNow.cpp
  regExp.cpp
  timer.cpp
  fileStat.cpp
  POSIX.cpp
  cpuTime/cpuTime.cpp
  clockTime/clockTime.cpp
  memInfo/memInfo.cpp
  fileMonitor.cpp
  printStack.cpp
  """)

#===============================================================================
# Build this library
#===============================================================================
libOSspecific = OSspecEnv.SharedLibrary(target = 'libOSspecific', 
source = src_files)

#===============================================================================
# Install this library
#===============================================================================
install_dir = OSspecEnv['LIB_PLATFORM_INSTALL']
OSspecEnv.Alias('install', install_dir)
OSspecEnv.Install(install_dir, libOSspecific)
