# -*- mode: python -*-

from build import build_lib
Import('env')

target = 'FVFunctionObjects'

sources = Split("""
calcFvcDiv/calcFvcDiv.cpp
calcFvcDiv/calcFvcDivFunctionObject.cpp
calcFvcGrad/calcFvcGrad.cpp
calcFvcGrad/calcFvcGradFunctionObject.cpp
calcMag/calcMag.cpp
calcMag/calcMagFunctionObject.cpp
""")

caelus_inc = [
]

caelus_libs = [
'core'
]

build_lib(env,
          target=target,
          sources=sources,
          caelus_inc=caelus_inc,
          caelus_libs=caelus_libs)
