#Copyright (C) 2014 Applied CCM
import subprocess
Import('globalEnv')

# Clone the global environment so changes made he are not pass onto subsequent 
# libraries
modifyMeshEnv = globalEnv.Clone()

# Path to source
src = modifyMeshEnv['LIB_SRC']

#===============================================================================
# Additions to compiler flags for this executable
#===============================================================================
modifyMeshEnv.Append(CCFLAGS = '')

#===============================================================================
# Additions to include directories for this executable
#===============================================================================
lib_inc = [src + '/dynamicMesh/lnInclude']
modifyMeshEnv.Prepend(CPPPATH = lib_inc)

#===============================================================================
# Additions to link library paths for this executable
#===============================================================================
lib_link_path = []
modifyMeshEnv.Prepend(LIBPATH = lib_link_path)

#===============================================================================
# Additions to link libraries for this executable
#===============================================================================
if modifyMeshEnv['WHICH_OS'] == "windows":
  lib_link = ['libdynamicMesh']
else:
  lib_link = ['dynamicMesh']
     

modifyMeshEnv.Append(LIBS = lib_link)

#===============================================================================
# Sources for this executable
#===============================================================================
src_files = Split("""
 cellSplitter.cpp
 modifyMesh.cpp
  """)

#===============================================================================
# Build this executable
#===============================================================================
binmodifyMesh = modifyMeshEnv.Program(target = 'modifyMesh', 
source = src_files)

#===============================================================================
# Install this executable
#===============================================================================
install_dir = modifyMeshEnv['BIN_PLATFORM_INSTALL']
modifyMeshEnv.Alias('install', install_dir)
modifyMeshEnv.Install(install_dir, binmodifyMesh)
