# -*- mode: python -*-

from build import build_lib
Import('env')

target = 'basicSolidThermo'

sources = Split("""
basicSolidThermo/basicSolidThermo.cpp
basicSolidThermo/basicSolidThermoNew.cpp
constSolidThermo/constSolidThermo.cpp
interpolatedSolidThermo/interpolatedSolidThermo.cpp
interpolatedSolidThermo/interpolateSolid/interpolateSolid.cpp
isotropicKSolidThermo/isotropicKSolidThermo.cpp
solidMixtureThermo/mixtures/basicSolidMixture/basicSolidMixture.cpp
solidMixtureThermo/solidMixtureThermo/solidMixtureThermos.cpp
""")

#solidMixtureThermo/solidMixtureThermo/solidMixtureThermos.cpp

caelus_inc = [
'thermophysicalModels/solid/lnInclude',
'thermophysicalModels/specie/lnInclude',
]

caelus_libs = [
'core',
'specie',
'solid'
]

build_lib(env,
          target=target,
          sources=sources,
          caelus_inc=caelus_inc,
          caelus_libs=caelus_libs)
