#Copyright (C) 2014 Applied CCM
import subprocess
Import('globalEnv')

# Clone the global environment so changes made he are not pass onto subsequent 
# libraries
writeCellCentresEnv = globalEnv.Clone()

# Path to source
src = writeCellCentresEnv['LIB_SRC']

#===============================================================================
# Additions to compiler flags for this executable
#===============================================================================
writeCellCentresEnv.Append(CCFLAGS = '')

#===============================================================================
# Additions to include directories for this executable
#===============================================================================
lib_inc = []
writeCellCentresEnv.Prepend(CPPPATH = lib_inc)

#===============================================================================
# Additions to link library paths for this executable
#===============================================================================
lib_link_path = []
writeCellCentresEnv.Prepend(LIBPATH = lib_link_path)

#===============================================================================
# Additions to link libraries for this executable
#===============================================================================
lib_link = []
     

writeCellCentresEnv.Append(LIBS = lib_link)

#===============================================================================
# Sources for this executable
#===============================================================================
src_files = Split("""
  writeCellCentres.cpp
  """)

#===============================================================================
# Build this executable
#===============================================================================
binwriteCellCentres = writeCellCentresEnv.Program(target = 'writeCellCentres', 
source = src_files)

#===============================================================================
# Install this executable
#===============================================================================
install_dir = writeCellCentresEnv['BIN_PLATFORM_INSTALL']
writeCellCentresEnv.Alias('install', install_dir)
writeCellCentresEnv.Install(install_dir, binwriteCellCentres)
