# -*- mode: python -*-

from build import build_lib
Import('env')

target = 'CAELUSCalcFunctions'

sources = Split("""
calcType/calcType.cpp
calcType/calcTypeNew.cpp
field/components/components.cpp
field/mag/mag.cpp
field/magSqr/magSqr.cpp
field/magGrad/magGrad.cpp
field/div/div.cpp
field/randomise/randomise.cpp
field/interpolate/interpolate.cpp
basic/addSubtract/addSubtract.cpp
""")

caelus_inc = []

caelus_libs = [
'core'
]

build_lib(env,
          target=target,
          sources=sources,
          caelus_inc=caelus_inc,
          caelus_libs=caelus_libs)
