#Copyright (C) 2014 Applied CCM
import subprocess
Import('globalEnv')

# Clone the global environment so changes made he are not pass onto subsequent 
# libraries
caelusCalcFuncEnv = globalEnv.Clone()

sl = caelusCalcFuncEnv['SLASH']

#===============================================================================
# Additions to compiler flags for this library
#===============================================================================
caelusCalcFuncEnv.Append(CCFLAGS = '')

#===============================================================================
# Additions to include directories for this library
#===============================================================================
lib_inc = ['lnInclude']
caelusCalcFuncEnv.Prepend(CPPPATH = lib_inc)
    
#===============================================================================
# Additions to link library paths for this library
#===============================================================================
lib_link_path = []
caelusCalcFuncEnv.Prepend(LIBPATH = lib_link_path)

#===============================================================================
# Additions to link libraries for this library
#===============================================================================
lib_link = ['core']
caelusCalcFuncEnv.Append(LIBS = lib_link)
           
#===============================================================================
# Sources for this library
#===============================================================================
src_files = Split("""
  calcType/calcType.cpp
  calcType/calcTypeNew.cpp
  field/components/components.cpp
  field/mag/mag.cpp
  field/magSqr/magSqr.cpp
  field/magGrad/magGrad.cpp
  field/div/div.cpp
  field/randomise/randomise.cpp
  field/interpolate/interpolate.cpp
  basic/addSubtract/addSubtract.cpp
  """) 

#===============================================================================
# Build this library
#===============================================================================
libcaelusCalcFunctions = caelusCalcFuncEnv.SharedLibrary(target = 
'CAELUSCalcFunctions', source = src_files)

#===============================================================================
# Install this library
#===============================================================================
install_dir = caelusCalcFuncEnv['LIB_PLATFORM_INSTALL']
caelusCalcFuncEnv.Alias('install', install_dir)
caelusCalcFuncEnv.Install(install_dir, libcaelusCalcFunctions)

if (caelusCalcFuncEnv['WHICH_OS'] == "darwin"):

  caelusCalcFuncEnv.Append(SHLINKFLAGS ='-install_name @' + caelusCalcFuncEnv['LIB_PLATFORM_INSTALL'] + '/libcaelusCalcFunctions.dylib')
