#Copyright (C) 2014 Applied CCM
import subprocess
Import('globalEnv')

# Clone the global environment so changes made he are not pass onto subsequent 
# libraries
topoSetEnv = globalEnv.Clone()

# Path to source
src = topoSetEnv['LIB_SRC']

topoSetEnv.Append(CXXFLAGS = '')
#===============================================================================
# Additions to compiler flags for this executable
#===============================================================================
topoSetEnv.Append(CCFLAGS = '')

#===============================================================================
# Additions to include directories for this executable
#===============================================================================
lib_inc = []

topoSetEnv.Prepend(CPPPATH = lib_inc)

#===============================================================================
# Additions to link library paths for this executable
#===============================================================================
lib_link_path = []
topoSetEnv.Prepend(LIBPATH = lib_link_path)

#===============================================================================
# Additions to link libraries for this executable
#===============================================================================
if topoSetEnv['WHICH_OS'] == "windows":
  lib_link = []
else:
  lib_link = []
  
topoSetEnv.Append(LIBS = lib_link)

#===============================================================================
# Sources for this executable
#===============================================================================
src_files = Split("""
  topoSet.cpp
  """)

#===============================================================================
# Build this executable
#===============================================================================
bintopoSet = topoSetEnv.Program(target = 
'topoSet', source = src_files)

#===============================================================================
# Install this executable
#===============================================================================
install_dir = topoSetEnv['BIN_PLATFORM_INSTALL']
topoSetEnv.Alias('install', install_dir)
topoSetEnv.Install(install_dir, bintopoSet)
