#Copyright (C) 2014 Applied CCM
import subprocess
Import('globalEnv')

# Clone the global environment so changes made he are not pass onto subsequent 
# libraries
pTotEnv = globalEnv.Clone()

# Path to source
src = pTotEnv['LIB_SRC']

#===============================================================================
# Additions to compiler flags for this executable
#===============================================================================
pTotEnv.Append(CCFLAGS = '')

#===============================================================================
# Additions to include directories for this executable
#===============================================================================
lib_inc = []
pTotEnv.Prepend(CPPPATH = lib_inc)

#===============================================================================
# Additions to link library paths for this executable
#===============================================================================
lib_link_path = []
pTotEnv.Prepend(LIBPATH = lib_link_path)

#===============================================================================
# Additions to link libraries for this executable
#===============================================================================
if pTotEnv['WHICH_OS'] == "windows":
  pTotEnv.Prepend(LINKFLAGS = ' -u genericPatchFieldsLoad')

lib_link = ['genericPatchFields']
     

pTotEnv.Append(LIBS = lib_link)

#===============================================================================
# Sources for this executable
#===============================================================================
src_files = Split("""
  ptot.cpp
  """)

#===============================================================================
# Build this executable
#===============================================================================
binpTot = pTotEnv.Program(target = 'pTot', 
source = src_files)

#===============================================================================
# Install this executable
#===============================================================================
install_dir = pTotEnv['BIN_PLATFORM_INSTALL']
pTotEnv.Alias('install', install_dir)
pTotEnv.Install(install_dir, binpTot)
