#Copyright (C) 2014 Applied CCM
import subprocess
Import('globalEnv')

# Clone the global environment so changes made he are not pass onto subsequent 
# libraries
lamFlameSpdEnv = globalEnv.Clone()

# Path to source
src = lamFlameSpdEnv['LIB_SRC']

#===============================================================================
# Additions to compiler flags for this library
#===============================================================================
lamFlameSpdEnv.Append(CCFLAGS = '')

#===============================================================================
# Additions to include directories for this library
#===============================================================================
lib_inc = ['lnInclude',
src + '/thermophysicalModels/specie/lnInclude',
src + '/thermophysicalModels/basic/lnInclude',
src + '/thermophysicalModels/reactionThermo/lnInclude'
]
lamFlameSpdEnv.Prepend(CPPPATH = lib_inc)

#===============================================================================
# Additions to link library paths for this library
#===============================================================================
lib_link_path = []
lamFlameSpdEnv.Prepend(LIBPATH = lib_link_path)

#===============================================================================
# Additions to link libraries for this library
#===============================================================================
lib_link = ['core']
lamFlameSpdEnv.Append(LIBS = lib_link)

#===============================================================================
# Sources for this library
#===============================================================================
src_files = Split("""
  laminarFlameSpeed/laminarFlameSpeed.cpp
  laminarFlameSpeed/laminarFlameSpeedNew.cpp
  constant/constant.cpp
  Gulders/Gulders.cpp
  GuldersEGR/GuldersEGR.cpp
  """)

#===============================================================================
# Build this library
#===============================================================================
liblaminarFlameSpeedModels = lamFlameSpdEnv.SharedLibrary(target = 
'laminarFlameSpeedModels', source = src_files)

#============================================================================================
# Install this library
#============================================================================================
install_dir = lamFlameSpdEnv['LIB_PLATFORM_INSTALL']
lamFlameSpdEnv.Alias('install', install_dir)
lamFlameSpdEnv.Install(install_dir, liblaminarFlameSpeedModels)

if (lamFlameSpdEnv['WHICH_OS'] == "darwin"):

  lamFlameSpdEnv.Append(SHLINKFLAGS ='-install_name @' + lamFlameSpdEnv['LIB_PLATFORM_INSTALL'] + '/liblaminarFlameSpeedModels.dylib')
