# -*- mode: python -*-

from build import build_lib
Import('env')

target = 'laminarFlameSpeedModels'

sources = Split("""
laminarFlameSpeed/laminarFlameSpeed.cpp
laminarFlameSpeed/laminarFlameSpeedNew.cpp
constant/constant.cpp
Gulders/Gulders.cpp
GuldersEGR/GuldersEGR.cpp
RaviPetersen/RaviPetersen.cpp
""")

caelus_inc = [
'thermophysicalModels/specie/lnInclude',
'thermophysicalModels/basic/lnInclude',
'thermophysicalModels/reactionThermo/lnInclude',
]

caelus_libs = [
'core'
]

build_lib(env,
          target=target,
          sources=sources,
          caelus_inc=caelus_inc,
          caelus_libs=caelus_libs)
