#Copyright (C) 2014 Applied CCM
import subprocess
Import('globalEnv')

# Clone the global environment so changes made he are not pass onto subsequent 
# libraries
scotchDecompEnv = globalEnv.Clone()

sl =scotchDecompEnv['SLASH']

scotchDecompEnv.Append(CXXFLAGS = '-DscotchDecomp_EXPORTS')
#===============================================================================
# Additions to compiler flags for this library
#===============================================================================
scotchDecompEnv.Append(CXXFLAGS = '')

#===============================================================================
# Additions to include directories for this library
#===============================================================================
lib_inc = ['lnInclude',
'..' + sl + 'decompositionMethods' + sl + 'lnInclude',
scotchDecompEnv['SCOTCH_PATH'] + sl + 'include']
scotchDecompEnv.Prepend(CPPPATH = lib_inc)

#===============================================================================
# Additions to link library paths for this library
#===============================================================================
lib_link_path = [scotchDecompEnv['SCOTCH_PATH']  + sl + 'lib']
scotchDecompEnv.Prepend(LIBPATH = lib_link_path)

#===============================================================================
# Additions to link libraries for this library
#===============================================================================
lib_link = ['core','decompositionMethods','scotch','scotcherr','scotcherrexit']
scotchDecompEnv.Append(LIBS = lib_link)

#===============================================================================
# Sources for this library
#===============================================================================
src_files = Split("""
  scotchDecomp.cpp
  """)

#===============================================================================
# Build this library
#===============================================================================
if scotchDecompEnv['WHICH_OS'] == "windows" :
  libscotchDecomp =scotchDecompEnv.SharedLibrary(target = 'scotchDecomp', 
  source = src_files)

else :
  libscotchDecomp =scotchDecompEnv.SharedLibrary(target = 'libscotchDecomp', 
  source = src_files)

#===============================================================================
# Install this library
#===============================================================================
install_dir =scotchDecompEnv['LIB_PLATFORM_INSTALL']
scotchDecompEnv.Alias('install', install_dir)
scotchDecompEnv.Install(install_dir, libscotchDecomp)

if (scotchDecompEnv['WHICH_OS'] == "darwin"):

  scotchDecompEnv.Append(SHLINKFLAGS ='-install_name @executable_path/../lib/libscotchDecomp.dylib')
