# -*- mode: python -*-

from build import build_lib
Import('env')

target = 'LESfilters'

sources = Split("""
LESfilter/LESfilter.cpp
simpleFilter/simpleFilter.cpp
laplaceFilter/laplaceFilter.cpp
anisotropicFilter/anisotropicFilter.cpp
""")

caelus_inc = []

caelus_libs = [
'core'
]

build_lib(env,
          target=target,
          sources=sources,
          caelus_inc=caelus_inc,
          caelus_libs=caelus_libs)
