# -*- mode: python -*-

from build import build_app
Import('env')

target = "potentialSolver"

sources = Split("""
potentialSolver.cpp
""")

caelus_inc = [
'fvOptions/lnInclude',
'sampling/lnInclude'
]

caelus_libs = [
'core',
'fvOptions',
'sampling'
]

build_app(env,
          target=target,
          sources=sources,
          caelus_inc=caelus_inc,
          caelus_libs=caelus_libs)
