#Copyright (C) 2014 Applied CCM
import subprocess
Import('globalEnv')

# Clone the global environment so changes made he are not pass onto subsequent 
# libraries
potentialSolEnv = globalEnv.Clone()

# Path to source
src = potentialSolEnv['LIB_SRC']

#===============================================================================
# Additions to include directories for this executable
#===============================================================================
lib_inc = [src + '/fvOptions/lnInclude',
  src + '/sampling/lnInclude']
potentialSolEnv.Prepend(CPPPATH = lib_inc)

#===============================================================================
# Additions to link libraries for this executable
#===============================================================================
lib_link = ['fvOptions','sampling']
     

potentialSolEnv.Append(LIBS = lib_link)

#===============================================================================
# Sources for this executable
#===============================================================================
src_files = Split("""
  potentialSolver.cpp
  """)

#===============================================================================
# Build this executable
#===============================================================================
binpotentialSol = potentialSolEnv.Program(target = 'potentialSolver',
source = src_files)

#===============================================================================
# Install this executable
#===============================================================================
install_dir = potentialSolEnv['BIN_PLATFORM_INSTALL']
potentialSolEnv.Alias('install', install_dir)
potentialSolEnv.Install(install_dir, binpotentialSol)
