#Copyright (C) 2014 Applied CCM
import subprocess
Import('globalEnv')

# Clone the global environment so changes made he are not pass onto subsequent 
# libraries
potentialSolEnv = globalEnv.Clone()

#===============================================================================
# Sources for this executable
#===============================================================================
src_files = Split("""
  potentialSolver.cpp
  """)

#===============================================================================
# Build this executable
#===============================================================================
binpotentialSol = potentialSolEnv.Program(target = 'potentialSolver',
source = src_files)

#===============================================================================
# Install this executable
#===============================================================================
install_dir = potentialSolEnv['BIN_PLATFORM_INSTALL']
potentialSolEnv.Alias('install', install_dir)
potentialSolEnv.Install(install_dir, binpotentialSol)
