#Copyright (C) 2014 Applied CCM
import subprocess
Import('globalEnv')

# Clone the global environment so changes made he are not pass onto subsequent 
# libraries
funcObjJobEnv = globalEnv.Clone()

sl = funcObjJobEnv['SLASH']

#===============================================================================
# Additions to compiler flags for this library
#===============================================================================
funcObjJobEnv.Append(CCFLAGS = '')

#===============================================================================
# Additions to include directories for this library
#===============================================================================
lib_inc = ['lnInclude']
funcObjJobEnv.Prepend(CPPPATH = lib_inc)

#===============================================================================
# Additions to link library paths for this library
#===============================================================================
lib_link_path = []
funcObjJobEnv.Prepend(LIBPATH = lib_link_path)

#===============================================================================
# Additions to link libraries for this library
#===============================================================================
lib_link = ['core'] 
funcObjJobEnv.Append(LIBS = lib_link)
   
#===============================================================================
# Sources for this library
#===============================================================================
src_files = Split("""
  abortCalculation/abortCalculation.cpp
  abortCalculation/abortCalculationFunctionObject.cpp
  """)

#===============================================================================
# Build this library
#===============================================================================
libjobControl = funcObjJobEnv.SharedLibrary(target = 'jobControl', 
source = src_files)

#===============================================================================
# Install this library
#===============================================================================
install_dir = funcObjJobEnv['LIB_PLATFORM_INSTALL']
funcObjJobEnv.Alias('install', install_dir)
funcObjJobEnv.Install(install_dir, libjobControl)

if (funcObjJobEnv['WHICH_OS'] == "darwin"):

  funcObjJobEnv.Append(SHLINKFLAGS ='-install_name @executable_path/../lib/libjobControl.dylib')
