# -*- mode: python -*-

from build import build_app
Import('env')

target = 'refinementLevel'

sources = Split("""
refinementLevel.cpp
""")

caelus_inc = [
'dynamicMesh/dynamicMesh/lnInclude'
]

caelus_libs = [
'core',
'dynamicMesh'
]

build_app(env,
          target=target,
          sources=sources,
          caelus_inc=caelus_inc,
          caelus_libs=caelus_libs)
