#Copyright (C) 2014 Applied CCM
import subprocess
Import('globalEnv')

# Clone the global environment so changes made he are not pass onto subsequent 
# libraries
refinementLevelEnv = globalEnv.Clone()

# Path to source
src = refinementLevelEnv['LIB_SRC']

#===============================================================================
# Additions to compiler flags for this executable
#===============================================================================
refinementLevelEnv.Append(CCFLAGS = '')

#===============================================================================
# Additions to include directories for this executable
#===============================================================================
lib_inc = [src + '/dynamicMesh/lnInclude']
refinementLevelEnv.Prepend(CPPPATH = lib_inc)

#===============================================================================
# Additions to link library paths for this executable
#===============================================================================
lib_link_path = []
refinementLevelEnv.Prepend(LIBPATH = lib_link_path)

#===============================================================================
# Additions to link libraries for this executable
#===============================================================================
lib_link = ['dynamicMesh']
     

refinementLevelEnv.Append(LIBS = lib_link)

#===============================================================================
# Sources for this executable
#===============================================================================
src_files = Split("""
  refinementLevel.cpp
  """)

#===============================================================================
# Build this executable
#===============================================================================
binrefinementLevel = refinementLevelEnv.Program(target = 'refinementLevel', 
source = src_files)

#===============================================================================
# Install this executable
#===============================================================================
install_dir = refinementLevelEnv['BIN_PLATFORM_INSTALL']
refinementLevelEnv.Alias('install', install_dir)
refinementLevelEnv.Install(install_dir, binrefinementLevel)
