# -*- mode: python -*-

import utils
from build import build_app
Import('env')

target = 'sample'

sources = Split("""
sample.cpp
""")

caelus_inc = [
'sampling/lnInclude',
'surfMesh/lnInclude',
'lagrangian/basic/lnInclude'
]

caelus_libs = [
'core',
'genericPatchFields',
'sampling',
'surfMesh',
'lagrangian']

ostype = utils.ostype()
prepend_args = {}
if ostype == 'windows':
   prepend_args = {'LINKFLAGS' :
         '-u genericPatchFieldsLoad'
}

build_app(env,
          target=target,
          sources=sources,
          caelus_inc=caelus_inc,
          caelus_libs=caelus_libs,
          prepend_args=prepend_args)
