# -*- mode: python -*-

from build import build_lib
Import('env')

target = 'solidChemistryModel'

sources = Split("""
solidChemistryModel/solidChemistryModel.cpp
solidChemistryModel/solidChemistryModelNew.cpp
solidChemistryModel/solidChemistryModels.cpp
solidChemistrySolver/makeSolidChemistrySolvers.cpp
""")

caelus_inc = [
'thermophysicalModels/solid/lnInclude',
'thermophysicalModels/specie/lnInclude',
'thermophysicalModels/basic/lnInclude',
'thermophysicalModels/chemistryModel/lnInclude',
'thermophysicalModels/basicSolidThermo/lnInclude',
'thermophysicalModels/reactionThermo/lnInclude',
'ODE/lnInclude'
]

caelus_libs = [
'core',
'specie',
'basicSolidThermo',
'chemistryModel',
'ODE'
]

build_lib(env,
          target=target,
          sources=sources,
          caelus_inc=caelus_inc,
          caelus_libs=caelus_libs)
