#Copyright (C) 2014 Applied CCM
import subprocess
Import('globalEnv')

# Clone the global environment so changes made he are not pass onto subsequent 
# libraries
solidChemEnv = globalEnv.Clone()

# Path to source
src = solidChemEnv['LIB_SRC']

#===============================================================================
# Additions to compiler flags for this library
#===============================================================================
solidChemEnv.Append(CCFLAGS = '')

#===============================================================================
# Additions to include directories for this library
#===============================================================================
lib_inc = ['lnInclude',
src + '/thermophysicalModels/solid/lnInclude',
src + '/thermophysicalModels/specie/lnInclude',
src + '/thermophysicalModels/basic/lnInclude',
src + '/thermophysicalModels/chemistryModel/lnInclude',
src + '/thermophysicalModels/basicSolidThermo/lnInclude',
src + '/thermophysicalModels/reactionThermo/lnInclude',
src + '/ODE/lnInclude'        
]
solidChemEnv.Prepend(CPPPATH = lib_inc)
         
#===============================================================================
# Additions to link library paths for this library
#===============================================================================
lib_link_path = []
solidChemEnv.Prepend(LIBPATH = lib_link_path)

#===============================================================================
# Additions to link libraries for this library
#===============================================================================
lib_link = ['core','specie','basicSolidThermo','chemistryModel','ODE'] 
solidChemEnv.Append(LIBS = lib_link)
           
#===============================================================================
# Sources for this library
#===============================================================================
src_files = Split("""
  solidChemistryModel/solidChemistryModel.cpp
  solidChemistryModel/solidChemistryModelNew.cpp
  solidChemistryModel/solidChemistryModels.cpp
  solidChemistrySolver/makeSolidChemistrySolvers.cpp
  """) 

#===============================================================================
# Build this library
#===============================================================================
libsolidChemistryModel = solidChemEnv.SharedLibrary(target = 
'solidChemistryModel', source = src_files)

#===============================================================================
# Install this library
#===============================================================================
install_dir = solidChemEnv['LIB_PLATFORM_INSTALL']
solidChemEnv.Alias('install', install_dir)
solidChemEnv.Install(install_dir, libsolidChemistryModel)

if (solidChemEnv['WHICH_OS'] == "darwin"):

  solidChemEnv.Append(SHLINKFLAGS ='-install_name @executable_path/../lib/libsolidChemistryModel.dylib')
