# -*- mode: python -*-

from build import build_lib
Import('env')

target = 'solidChemistryModel'

sources = Split("""
basicSolidChemistryModel/basicSolidChemistryModel.cpp
basicSolidChemistryModel/basicSolidChemistryModelNew.cpp
basicSolidChemistryModel/basicSolidChemistryModels.cpp
solidChemistrySolver/makeSolidChemistrySolvers.cpp
""")

caelus_inc = [
'thermophysicalModels/specie/lnInclude',
'thermophysicalModels/solidSpecie/lnInclude',
'thermophysicalModels/basic/lnInclude',
'thermophysicalModels/chemistryModel/lnInclude',
'thermophysicalModels/solidThermo/lnInclude',
'thermophysicalModels/reactionThermo/lnInclude',
'ODE/lnInclude'
]

caelus_libs = [
'core',
'fluidThermophysicalModels',
'chemistryModel',
'specie',
'ODE',
'reactionThermophysicalModels'
]

build_lib(env,
          target=target,
          sources=sources,
          caelus_inc=caelus_inc,
          caelus_libs=caelus_libs)
