# -*- mode: python -*-

from build import build_app
Import('env')

target = 'moveDynamicMesh'

sources = Split("""
moveDynamicMesh.cpp
""")

caelus_inc = [
'dynamicMesh/dynamicFvMesh/lnInclude',
'sampling/lnInclude'
]

caelus_libs = [
'core',
'dynamicMesh',
'dynamicFvMesh',
'sampling'
]

build_app(env,
          target=target,
          sources=sources,
          caelus_inc=caelus_inc,
          caelus_libs=caelus_libs)
