# -*- mode: python -*-

from build import build_lib
Import('env')

target = 'decompositionMethods'

sources = Split("""
decompositionMethod/decompositionMethod.cpp
geomDecomp/geomDecomp.cpp
simpleGeomDecomp/simpleGeomDecomp.cpp
hierarchGeomDecomp/hierarchGeomDecomp.cpp
manualDecomp/manualDecomp.cpp
multiLevelDecomp/multiLevelDecomp.cpp
structuredDecomp/topoDistanceData.cpp
structuredDecomp/structuredDecomp.cpp
decompositionConstraints/decompositionConstraint/decompositionConstraint.cpp
decompositionConstraints/preserveBaffles/preserveBafflesConstraint.cpp
decompositionConstraints/preserveFaceZones/preserveFaceZonesConstraint.cpp
decompositionConstraints/preservePatches/preservePatchesConstraint.cpp
decompositionConstraints/singleProcessorFaceSets/singleProcessorFaceSetsConstraint.cpp
decompositionConstraints/refinementHistory/refinementHistoryConstraint.cpp
""")

caelus_inc = [
'dynamicMesh/dynamicMesh/lnInclude'
]

caelus_libs = [
'core',
'dynamicMesh'
]

build_lib(env,
          target=target,
          sources=sources,
          caelus_inc=caelus_inc,
          caelus_libs=caelus_libs)
