#Copyright (C) 2014 Applied CCM
import subprocess
Import('globalEnv')

# Clone the global environment so changes made he are not pass onto subsequent 
# libraries
decomposeMethodsEnv = globalEnv.Clone()

#===============================================================================
# Additions to compiler flags for this library
#===============================================================================
decomposeMethodsEnv.Append(CXXFLAGS = '')

#===============================================================================
# Additions to include directories for this library
#===============================================================================
lib_inc = ['lnInclude']
decomposeMethodsEnv.Prepend(CPPPATH = lib_inc)

#===============================================================================
# Additions to link library paths for this library
#===============================================================================
lib_link_path = []
decomposeMethodsEnv.Prepend(LIBPATH = lib_link_path)

#===============================================================================
# Additions to link libraries for this library
#===============================================================================
lib_link = ['core']
decomposeMethodsEnv.Append(LIBS = lib_link)

#===============================================================================
# Sources for this library
#===============================================================================
src_files = Split("""
  decompositionMethod/decompositionMethod.cpp
  geomDecomp/geomDecomp.cpp
  simpleGeomDecomp/simpleGeomDecomp.cpp
  hierarchGeomDecomp/hierarchGeomDecomp.cpp
  manualDecomp/manualDecomp.cpp
  multiLevelDecomp/multiLevelDecomp.cpp
  structuredDecomp/topoDistanceData.cpp
  structuredDecomp/structuredDecomp.cpp
  """)

#===============================================================================
# Build this library
#===============================================================================
libdecompositionMethods = decomposeMethodsEnv.SharedLibrary(target = 
'libdecompositionMethods', source = src_files)

#===============================================================================
# Install this library
#===============================================================================
install_dir = decomposeMethodsEnv['LIB_PLATFORM_INSTALL']
decomposeMethodsEnv.Alias('install', install_dir)
decomposeMethodsEnv.Install(install_dir, libdecompositionMethods)

if (decomposeMethodsEnv['WHICH_OS'] == "darwin"):

  decomposeMethodsEnv.Append(SHLINKFLAGS ='-install_name @' + decomposeMethodsEnv['LIB_PLATFORM_INSTALL'] + '/libdecompositionMethods.dylib')
