# -*- mode: python -*-

from build import build_lib
Import('env')

target = 'incompressibleTransportModels'

sources = Split("""
viscosityModels/viscosityModel/viscosityModel.cpp
viscosityModels/viscosityModel/viscosityModelNew.cpp
viscosityModels/Newtonian/Newtonian.cpp
viscosityModels/powerLaw/powerLaw.cpp
viscosityModels/CrossPowerLaw/CrossPowerLaw.cpp
viscosityModels/CarreauYasudaCross/CarreauYasudaCross.cpp
viscosityModels/HerschelBulkley/HerschelBulkley.cpp
transportModel/transportModel.cpp
singlePhaseTransportModel/singlePhaseTransportModel.cpp
incompressibleTwoPhaseMixture/twoPhaseMixture.cpp
""")

caelus_inc = [
'transportModels'
]

caelus_libs = [
'core'
]

build_lib(env,
          target=target,
          sources=sources,
          caelus_inc=caelus_inc,
          caelus_libs=caelus_libs)
