# -*- mode: python -*-

import utils
from build import build_app
Import('env')

target = 'wallShearStress'

sources = Split("""
wallShearStress_app.cpp
""")

caelus_inc = [
'turbulenceModels',
'turbulenceModels/compressible/turbulenceModel/lnInclude',
'turbulenceModels/incompressible/turbulenceModel/lnInclude',
'turbulenceModels/compressible/RAS/lnInclude',
'turbulenceModels/incompressible/RAS/lnInclude',
'transportModels',
'transportModels/incompressible/lnInclude',
'thermophysicalModels/basic/lnInclude'
]

caelus_libs = [
'core',
'compressibleRASModels',
'reactionThermophysicalModels',
'specie',
'fluidThermophysicalModels',
'compressibleTurbulenceModel',
'incompressibleRASModels',
'incompressibleTransportModels',
'incompressibleTurbulenceModel'
]

ostype = utils.ostype()
prepend_args = {}
if ostype == 'windows':
   prepend_args = {'LINKFLAGS' :
         '-u genericPatchFieldsLoad -u incompressibleRASModelsLoad -u compressibleRASModelsLoad -u turbulenceDerivedFvPatchFieldsLoad'
}

build_app(env,
          target=target,
          sources=sources,
          caelus_inc=caelus_inc,
          caelus_libs=caelus_libs,
          prepend_args=prepend_args)
