#Copyright (C) 2014 Applied CCM
import subprocess
Import('globalEnv')

# Clone the global environment so changes made he are not pass onto subsequent 
# libraries
splitCellsEnv = globalEnv.Clone()

# Path to source
src = splitCellsEnv['LIB_SRC']

#===============================================================================
# Additions to compiler flags for this executable
#===============================================================================
splitCellsEnv.Append(CCFLAGS = '')

#===============================================================================
# Additions to include directories for this executable
#===============================================================================
lib_inc = [src + '/dynamicMesh/lnInclude']
splitCellsEnv.Prepend(CPPPATH = lib_inc)

#===============================================================================
# Additions to link library paths for this executable
#===============================================================================
lib_link_path = []
splitCellsEnv.Prepend(LIBPATH = lib_link_path)

#===============================================================================
# Additions to link libraries for this executable
#===============================================================================
lib_link = ['dynamicMesh']
     

splitCellsEnv.Append(LIBS = lib_link)

#===============================================================================
# Sources for this executable
#===============================================================================
src_files = Split("""
  splitCells.cpp
  """)

#===============================================================================
# Build this executable
#===============================================================================
binsplitCells = splitCellsEnv.Program(target = 'splitCells', 
source = src_files)

#===============================================================================
# Install this executable
#===============================================================================
install_dir = splitCellsEnv['BIN_PLATFORM_INSTALL']
splitCellsEnv.Alias('install', install_dir)
splitCellsEnv.Install(install_dir, binsplitCells)
