# -*- mode: python -*-

import utils
from build import build_app
Import('env')

target = "cpbnsLTS"

sources = Split("""
cpbnsLTS.cpp
""")

caelus_inc = [
'turbulenceModels/',
'turbulenceModels/compressible/turbulenceModel/lnInclude',
'transportModels',
'transportModels/compressible/singlePhaseTransportModel',
'transportModels/compressible/lnInclude',
'thermophysicalModels/basic/lnInclude',
'fvOptions/lnInclude',
'sampling/lnInclude'
]

caelus_libs = [
'core',
'compressibleTurbulenceModel',
'compressibleRASModels',
'compressibleLESModels',
'compressibleVLESModels',
'fluidThermophysicalModels',
'turbulenceDerivedFvPatchFields',
'fvOptions',
'sampling'
]

ostype = utils.ostype()
prepend_args = {}
if ostype == 'windows':
   prepend_args = {'LINKFLAGS' :
            '-u compressibleRASModelsLoad -u compressibleLESModelsLoad -u compressibleVLESModelsLoad -u turbulenceDerivedFvPatchFieldsLoad'
}

build_app(env,
          target=target,
          sources=sources,
          caelus_inc=caelus_inc,
          caelus_libs=caelus_libs,
          prepend_args=prepend_args)
