# -*- mode: python -*-

from build import build_lib
Import('env')

target = 'regionCoupling'

sources = Split("""
derivedFvPatchFields/filmPyrolysisVelocityCoupled/filmPyrolysisVelocityCoupledFvPatchVectorField.cpp
derivedFvPatchFields/filmPyrolysisTemperatureCoupled/filmPyrolysisTemperatureCoupledFvPatchScalarField.cpp
derivedFvPatchFields/filmPyrolysisRadiativeCoupledMixed/filmPyrolysisRadiativeCoupledMixedFvPatchScalarField.cpp
""")

caelus_inc = [
'sampling/lnInclude',
'AMIInterpolation/lnInclude',
'turbulenceModels',
'thermophysicalModels/basic/lnInclude',
'thermophysicalModels/specie/lnInclude',
'thermophysicalModels/chemistryModel/lnInclude',
'thermophysicalModels/solidThermo/lnInclude',
'thermophysicalModels/solidChemistryModel/lnInclude',
'thermophysicalModels/solidSpecie/lnInclude',
'thermophysicalModels/reactionThermo/lnInclude',
'thermophysicalModels/radiation/lnInclude',
'thermophysicalModels/SLGThermo/lnInclude',
'thermophysicalModels/thermophysicalProperties/lnInclude',
'turbulenceModels/compressible/turbulenceModel/lnInclude',
'turbulenceModels/compressible/LES/lnInclude',
'turbulenceModels/compressible/RAS/lnInclude',
'turbulenceModels/LES/LESdeltas/lnInclude',
'regionModels/regionModel/lnInclude',
'regionModels/pyrolysisModels/lnInclude',
'regionModels/surfaceFilmModels/lnInclude'
]

caelus_libs = [
'core',
'regionModels',
'pyrolysisModels',
'surfaceFilmModels',
'solidChemistryModel',
'compressibleTurbulenceModel',
'compressibleRASModels',
'compressibleLESModels',
'reactionThermophysicalModels',
'SLGThermo'
]

build_lib(env,
          target=target,
          sources=sources,
          caelus_inc=caelus_inc,
          caelus_libs=caelus_libs)
