# -*- mode: python -*-

from build import build_lib
Import('env')

target = 'regionCoupling'

sources = Split("""
derivedFvPatchFields/filmPyrolysisVelocityCoupled/filmPyrolysisVelocityCoupledFvPatchVectorField.cpp
  derivedFvPatchFields/filmPyrolysisTemperatureCoupled/filmPyrolysisTemperatureCoupledFvPatchScalarField.cpp
""")

caelus_inc = [
'sampling/lnInclude',
'AMIInterpolation/lnInclude',
'turbulenceModels',
'thermophysicalModels/basic/lnInclude',
'thermophysicalModels/specie/lnInclude',
'hermophysicalModels/solid/lnInclude',
'thermophysicalModels/chemistryModel/lnInclude',
'thermophysicalModels/basicSolidThermo/lnInclude',
'thermophysicalModels/solidChemistryModel/lnInclude',
'thermophysicalModels/radiationModels/lnInclude',
'turbulenceModels/compressible/turbulenceModel/lnInclude',
'turbulenceModels/compressible/LES/lnInclude',
'turbulenceModels/compressible/RAS/lnInclude',
'turbulenceModels/LES/LESdeltas/lnInclude',
'regionModels/regionModel/lnInclude',
'regionModels/pyrolysisModels/lnInclude',
'regionModels/surfaceFilmModels/lnInclude'
]

caelus_libs = [
'core',
'regionModels',
'pyrolysisModels',
'surfaceFilmModels',
'solidChemistryModel',
'compressibleRASModels',
'compressibleLESModels'
]

build_lib(env,
          target=target,
          sources=sources,
          caelus_inc=caelus_inc,
          caelus_libs=caelus_libs)
