#Copyright (C) 2014 Applied CCM
import subprocess
Import('globalEnv')

# Clone the global environment so changes made he are not pass onto subsequent 
# libraries
regCoupEnv = globalEnv.Clone()

# Path to source
src = regCoupEnv['LIB_SRC']

#===============================================================================
# Additions to compiler flags for this library
#===============================================================================
regCoupEnv.Append(CCFLAGS = '')

#===============================================================================
# Additions to include directories for this library
#===============================================================================
lib_inc = ['lnInclude',
src + '/sampling/lnInclude', 
src + '/AMIInterpolation/lnInclude',  
src + '/turbulenceModels',   
src + '/thermophysicalModels/basic/lnInclude',
src + '/thermophysicalModels/specie/lnInclude',
src + 'thermophysicalModels/solid/lnInclude',
src + '/thermophysicalModels/chemistryModel/lnInclude',
src + '/thermophysicalModels/basicSolidThermo/lnInclude',
src + '/thermophysicalModels/solidChemistryModel/lnInclude',
src + '/thermophysicalModels/radiationModels/lnInclude',
src + '/turbulenceModels/compressible/turbulenceModel/lnInclude', 
src + '/turbulenceModels/compressible/LES/lnInclude', 
src + '/turbulenceModels/compressible/RAS/lnInclude',  
src + '/turbulenceModels/LES/LESdeltas/lnInclude',
src + '/regionModels/regionModel/lnInclude',
src + '/regionModels/pyrolysisModels/lnInclude',
src + '/regionModels/surfaceFilmModels/lnInclude' 
] 
regCoupEnv.Prepend(CPPPATH = lib_inc)

#===============================================================================
# Additions to link library paths for this library
#===============================================================================
lib_link_path = []
regCoupEnv.Prepend(LIBPATH = lib_link_path)

#===============================================================================
# Additions to link libraries for this library
#===============================================================================
lib_link = ['core','regionModels','pyrolysisModels',
'surfaceFilmModels','solidChemistryModel','compressibleRASModels',
'compressibleLESModels'
] 
regCoupEnv.Append(LIBS = lib_link)
       
#===============================================================================
# Sources for this library
#===============================================================================
src_files = Split("""
  derivedFvPatchFields/filmPyrolysisVelocityCoupled/filmPyrolysisVelocityCoupledFvPatchVectorField.cpp
  derivedFvPatchFields/filmPyrolysisTemperatureCoupled/filmPyrolysisTemperatureCoupledFvPatchScalarField.cpp
  """)

#===============================================================================
# Build this library
#===============================================================================
libregionCoupling = regCoupEnv.SharedLibrary(target = 'regionCoupling', 
source = src_files)

#===============================================================================
# Install this library
#===============================================================================
install_dir = regCoupEnv['LIB_PLATFORM_INSTALL']
regCoupEnv.Alias('install', install_dir)
regCoupEnv.Install(install_dir, libregionCoupling)

if (regCoupEnv['WHICH_OS'] == "darwin"):

  regCoupEnv.Append(SHLINKFLAGS ='-install_name @executable_path/../lib/libregionCoupling.dylib')
