# -*- mode: python -*-

import utils
from build import build_app
Import('env')

target = "explicitDBNSSRFSolver"

sources = Split("""
explicitDBNSSRFSolver.cpp
""")

caelus_inc = [
'turbulenceModels/',
'turbulenceModels/compressible/turbulenceModel/lnInclude',
'transportModels',
'transportModels/compressible/singlePhaseTransportModel',
'transportModels/compressible/lnInclude',
'thermophysicalModels/basic/lnInclude',
'fvOptions/lnInclude',
'sampling/lnInclude',
'thermophysicalModels/numericFluxes/DBNS/numericFlux/lnInclude',
]

caelus_libs = [
'core',
'compressibleTurbulenceModel',
'compressibleRASModels',
'compressibleLESModels',
'compressibleVLESModels',
'fluidThermophysicalModels',
'turbulenceDerivedFvPatchFields',
'fvOptions',
'sampling',
'numericFlux'
]

ostype = utils.ostype()

if ostype == 'windows':
    append_args = dict(CPPPATH = ["..\\explicitDBNSSolver"])
else:
    append_args = dict(CPPPATH = ["../explicitDBNSSolver"])

prepend_args = {}
if ostype == 'windows':
   prepend_args = {'LINKFLAGS' :
            '-u compressibleRASModelsLoad -u compressibleLESModelsLoad -u compressibleVLESModelsLoad -u turbulenceDerivedFvPatchFieldsLoad'
}

build_app(env,
          target=target,
          sources=sources,
          caelus_inc=caelus_inc,
          caelus_libs=caelus_libs,
          append_args=append_args,
          prepend_args=prepend_args)
