#Copyright (C) 2014 Applied CCM
import subprocess
Import('globalEnv')

# Clone the global environment so changes made he are not pass onto subsequent 
# libraries
explicitDBNSSRFSolverEnv = globalEnv.Clone()

# Path to source
src = explicitDBNSSRFSolverEnv['LIB_SRC']

#===============================================================================
# Additions to compiler flags for this executable
#===============================================================================
explicitDBNSSRFSolverEnv.Append(CCFLAGS = '')

#===============================================================================
# Additions to include directories for this executable
#===============================================================================
lib_inc = [explicitDBNSSRFSolverEnv['LIB_SRC'] +  '/turbulenceModels',
src + '/turbulenceModels/compressible/turbulenceModel/lnInclude', 
src + '/turbulenceModels/compressible/RAS/RASModel', 
src + '/turbulenceModels/compressible/RAS/lnInclude',
src + '/thermophysicalModels',
src + '/thermophysicalModels/basic/psiThermo/basicPsiThermo',
src + '/thermophysicalModels/basic/basicThermo',
src + '/transportModels/basic/lnInclude',
src + '/fvOptions/lnInclude',
src + '/sampling/lnInclude',
src + '/core/lnInclude',
src + '/thermophysicalModels/numericFluxes/DBNS/numericFlux/roeFDSFlux',
src + '/thermophysicalModels/numericFluxes/DBNS/numericFlux/llfFlux',
src + '/thermophysicalModels/numericFluxes/DBNS/numericFlux/hllcFlux',
src + '/thermophysicalModels/numericFluxes/DBNS/numericFlux/ktpFlux',
src + '/thermophysicalModels/numericFluxes/DBNS/numericFlux/dwFlux'
]
explicitDBNSSRFSolverEnv.Prepend(CPPPATH = lib_inc)

#===============================================================================
# Additions to link library paths for this executable
#===============================================================================
lib_link_path = []
explicitDBNSSRFSolverEnv.Prepend(LIBPATH = lib_link_path)

#===============================================================================
# Additions to link libraries for this executable
#===============================================================================
if explicitDBNSSRFSolverEnv['WHICH_OS'] == "windows":
  explicitDBNSSRFSolverEnv.Prepend(LINKFLAGS = ' -u compressibleRASModelsLoad -u compressibleLESSModelsLoad -u compressibleVLESModelsLoad')

lib_link = ['compressibleTurbulenceModel', 'compressibleRASModels',
'basicThermophysicalModels', 'fvOptions', 'sampling', 'compressibleLESModels','numericFlux','compressibleVLESModels']
  
explicitDBNSSRFSolverEnv.Append(LIBS = lib_link)

#===============================================================================
# Sources for this executable
#===============================================================================
src_files = Split("""
  explicitDBNSSRFSolver.cpp
  """)

#===============================================================================
# Build this executable
#===============================================================================
binexplicitDBNSSRFSolver = explicitDBNSSRFSolverEnv.Program(target = 'explicitDBNSSRFSolver',
source = src_files)

#===============================================================================
# Install this executable
#===============================================================================
install_dir = explicitDBNSSRFSolverEnv['BIN_PLATFORM_INSTALL']
explicitDBNSSRFSolverEnv.Alias('install', install_dir)
explicitDBNSSRFSolverEnv.Install(install_dir, binexplicitDBNSSRFSolver)
