# -*- mode: python -*-

import utils
from build import build_app
Import('env')

target = 'caelusDebugSwitches'

sources = Split("""
caelusDebugSwitches.cpp
""")

caelus_inc = [
]

caelus_libs = [
'autoMesh',
'barotropicCompressibilityModel',
'solidThermo',
'fluidThermophysicalModels',
'blockMesh',
'chemistryModel',
'coalCombustion',
'compressibleLESModels',
'compressibleRASModels',
'compressibleTurbulenceModel',
'conversion',
'core',
'decompositionMethods',
'distributed',
'distributionModels',
'dynamicFvMesh',
'dynamicMesh',
'edgeMesh',
'fieldFunctionObjects',
'CAELUSCalcFunctions',
'forces',
'fvMotionSolvers',
'incompressibleLESModels',
'incompressibleRASModels',
'incompressibleTransportModels',
'incompressibleTurbulenceModel',
'interfaceProperties',
'IOFunctionObjects',
'jobControl',
'lagrangian',
'lagrangianIntermediate',
'laminarFlameSpeedModels',
'LESdeltas',
'LESfilters',
'ODE',
'radiationModels',
'randomProcesses',
'reactionThermophysicalModels',
'reconstruct',
'sampling',
'SLGThermo',
'solidParticle',
'solidSpecie',
'specie',
'surfaceFilmModels',
'surfMesh',
'systemCall',
'thermophysicalProperties',
'topoChangerFvMesh',
'twoPhaseInterfaceProperties',
'utilityFunctionObjects'
]

ostype = utils.ostype()
prepend_args = {}
if ostype == 'windows':
   prepend_args = {'LINKFLAGS' :
         '-u genericPatchFieldsLoad -u incompressibleRASModelsLoad -u incompressibleLESModelsLoad -u compressibleRASModelsLoad -u compressibleLESModelsLoad -u interfacePropertiesLoad -u lagrangianIntermediateLoad -u turbulenceDerivedFvPatchFieldsLoad'
}

build_app(env,
          target=target,
          sources=sources,
          caelus_inc=caelus_inc,
          caelus_libs=caelus_libs,
          prepend_args=prepend_args)
