# -*- mode: python -*-

from build import build_lib
Import('env')

target = 'chemistryModel'

sources = Split("""
chemistryModel/basicChemistryModel/basicChemistryModel.cpp
chemistryModel/BasicChemistryModel_/BasicChemistryModels.cpp
chemistryModel/TDACChemistryModel/reduction/makeChemistryReductionMethods.cpp
chemistryModel/TDACChemistryModel/tabulation/makeChemistryTabulationMethods.cpp
chemistrySolver/chemistrySolver/makeChemistrySolvers.cpp
""")

caelus_inc = [
'thermophysicalModels/specie/lnInclude',
'thermophysicalModels/basic/lnInclude',
'thermophysicalModels/reactionThermo/lnInclude',
'thermophysicalModels/functions/Polynomial/lnInclude',
'ODE/lnInclude',
]

caelus_libs = [
'core',
'fluidThermophysicalModels',
'reactionThermophysicalModels',
'specie',
'ODE'
]

build_lib(env,
          target=target,
          sources=sources,
          caelus_inc=caelus_inc,
          caelus_libs=caelus_libs)
