# -*- mode: python -*-

from build import build_lib
Import('env')

target = 'chemistryModel'

sources = Split("""
chemistryModel/basicChemistryModel/basicChemistryModel.cpp
chemistryModel/psiChemistryModel/psiChemistryModel.cpp
chemistryModel/psiChemistryModel/psiChemistryModelNew.cpp
chemistryModel/psiChemistryModel/psiChemistryModels.cpp
chemistryModel/rhoChemistryModel/rhoChemistryModel.cpp
chemistryModel/rhoChemistryModel/rhoChemistryModelNew.cpp
chemistryModel/rhoChemistryModel/rhoChemistryModels.cpp
chemistrySolver/chemistrySolver/makeChemistrySolvers.cpp
""")

caelus_inc = [
'thermophysicalModels/specie/lnInclude',
'thermophysicalModels/basic/lnInclude',
'thermophysicalModels/reactionThermo/lnInclude',
'thermophysicalModels/thermophysicalFunctions/lnInclude',
'thermophysicalModels/functions/Polynomial/lnInclude',
'turbulenceModels/compressible/lnInclude',
'ODE/lnInclude',
]

caelus_libs = [
'core',
'basicThermophysicalModels',
'reactionThermophysicalModels',
'specie',
'thermophysicalFunctions',
'ODE'
]

build_lib(env,
          target=target,
          sources=sources,
          caelus_inc=caelus_inc,
          caelus_libs=caelus_libs)
