# -*- mode: python -*-

from build import build_lib
Import('env')

target = 'dynamicFvMesh'

sources = Split("""
dynamicFvMesh/dynamicFvMesh.cpp
dynamicFvMesh/dynamicFvMeshNew.cpp
staticFvMesh/staticFvMesh.cpp
dynamicMotionSolverFvMesh/dynamicMotionSolverFvMesh.cpp
dynamicInkJetFvMesh/dynamicInkJetFvMesh.cpp
dynamicRefineFvMesh/dynamicRefineFvMesh.cpp
dynamicRefineBalancedFvMesh/dynamicRefineBalancedFvMesh.cpp
solidBodyMotionFvMesh/solidBodyMotionFvMesh.cpp
solidBodyMotionFvMesh/multiSolidBodyMotionFvMesh.cpp
""")

caelus_inc = [
'dynamicMesh/dynamicMesh/lnInclude',
'dynamicMesh/meshMotion/solidBodyMotion/solidBodyMotionFunctions/lnInclude',
'parallel/decompose/decompositionMethods/lnInclude'
]

caelus_libs = [
'core',
'dynamicMesh',
'solidBodyMotionFunctions',
'decompositionMethods',
'ptscotchDecomp'
]

build_lib(env,
          target=target,
          sources=sources,
          caelus_inc=caelus_inc,
          caelus_libs=caelus_libs)
