# -*- mode: python -*-

from build import build_lib
Import('env')

target = 'postCalc'

sources = Split("""
postCalc.cpp
""")

caelus_inc = []

caelus_libs = [
'core'
]

build_lib(env,
          target=target,
          sources=sources,
          caelus_inc=caelus_inc,
          caelus_libs=caelus_libs,
          lib_type="object")
