# -*- mode: python -*-

import utils
from build import build_app
Import('env')

target = "simpleSolver"

sources = Split("""
simpleSolver.cpp
""")

caelus_inc = [
'turbulenceModels/',
'turbulenceModels/incompressible/turbulenceModel/lnInclude',
'turbulenceModels/incompressible/RAS/RASModel',
'turbulenceModels/incompressible/RAS/lnInclude',
'transportModels',
'transportModels/incompressible/singlePhaseTransportModel',
'transportModels/incompressible/lnInclude',
'fvOptions/lnInclude',
'sampling/lnInclude'
]

caelus_libs = [
'core',
'incompressibleTurbulenceModel',
'incompressibleRASModels',
'incompressibleTransportModels',
'turbulenceDerivedFvPatchFields',
'fvOptions',
'sampling'
]

ostype = utils.ostype()
prepend_args = {}
if ostype == 'windows':
   prepend_args = {'LINKFLAGS' :
            '-u turbulenceDerivedFvPatchFieldsLoad -u incompressibleRASModelsLoad'
}

build_app(env,
          target=target,
          sources=sources,
          caelus_inc=caelus_inc,
          caelus_libs=caelus_libs,
          prepend_args=prepend_args)
