# -*- mode: python -*-

from build import build_lib
Import('env')

target = 'radiationModels'

sources = Split("""
radiationModel/radiationModel/radiationModel.cpp
radiationModel/radiationModel/radiationModelNew.cpp
radiationModel/noRadiation/noRadiation.cpp
radiationModel/P1/P1.cpp
radiationModel/fvDOM/fvDOM/fvDOM.cpp
radiationModel/fvDOM/radiativeIntensityRay/radiativeIntensityRay.cpp
radiationModel/fvDOM/blackBodyEmission/blackBodyEmission.cpp
radiationModel/fvDOM/absorptionCoeffs/absorptionCoeffs.cpp
radiationModel/viewFactor/viewFactor.cpp
submodels/scatterModel/scatterModel/scatterModel.cpp
submodels/scatterModel/scatterModel/scatterModelNew.cpp
submodels/scatterModel/constantScatter/constantScatter.cpp
submodels/scatterModel/noScatter/noScatter.cpp
submodels/absorptionEmissionModel/absorptionEmissionModel/absorptionEmissionModel.cpp
submodels/absorptionEmissionModel/absorptionEmissionModel/absorptionEmissionModelNew.cpp
submodels/absorptionEmissionModel/noAbsorptionEmission/noAbsorptionEmission.cpp
submodels/absorptionEmissionModel/constantAbsorptionEmission/constantAbsorptionEmission.cpp
submodels/absorptionEmissionModel/binaryAbsorptionEmission/binaryAbsorptionEmission.cpp
submodels/absorptionEmissionModel/greyMeanAbsorptionEmission/greyMeanAbsorptionEmission.cpp
submodels/absorptionEmissionModel/wideBandAbsorptionEmission/wideBandAbsorptionEmission.cpp
derivedFvPatchFields/MarshakRadiation/MarshakRadiationMixedFvPatchScalarField.cpp
derivedFvPatchFields/MarshakRadiationFixedT/MarshakRadiationFixedTMixedFvPatchScalarField.cpp
derivedFvPatchFields/greyDiffusiveRadiation/greyDiffusiveRadiationMixedFvPatchScalarField.cpp
derivedFvPatchFields/wideBandDiffusiveRadiation/wideBandDiffusiveRadiationMixedFvPatchScalarField.cpp
derivedFvPatchFields/radiationCoupledBase/radiationCoupledBase.cpp
derivedFvPatchFields/greyDiffusiveViewFactor/greyDiffusiveViewFactorFixedValueFvPatchScalarField.cpp
""")

caelus_inc = [
'thermophysicalModels/basic/lnInclude',
'thermophysicalModels/specie/lnInclude',
'thermophysicalModels/basicSolidThermo/lnInclude',
'thermophysicalModels/SLGThermo/lnInclude',
'thermophysicalModels/reactionThermo/lnInclude',
'thermophysicalModels/properties/liquidProperties/lnInclude',
'thermophysicalModels/properties/liquidMixtureProperties/lnInclude',
'thermophysicalModels/properties/solidProperties/lnInclude',
'thermophysicalModels/properties/solidMixtureProperties/lnInclude',
]

caelus_libs = [
'core',
'specie',
'basicThermophysicalModels',
'basicSolidThermo',
'SLGThermo',
'solidMixtureProperties',
'liquidMixtureProperties',
'solidProperties',
'liquidProperties'
]

build_lib(env,
          target=target,
          sources=sources,
          caelus_inc=caelus_inc,
          caelus_libs=caelus_libs)
