# -*- mode: python -*-

import os
import utils
from build import build_app
Import('env')

target = 'R'

sources = Split("""
R.cpp
compatibilityFvPatchFields/turbulentIntensityKineticEnergyInlet/turbulentIntensityKineticEnergyInletFvPatchSymmTensorField.cpp
""")

caelus_inc = [
'turbulenceModels',
'turbulenceModels/incompressible/turbulenceModel/lnInclude',
'turbulenceModels/incompressible/RAS/lnInclude',  
'turbulenceModels/incompressible/RAS/RASModel',
'transportModels',
'transportModels/incompressible/lnInclude',  
'postProcessing/postCalc'
]

caelus_libs = [
'core',
'incompressibleRASModels',
'incompressibleTurbulenceModel',
'incompressibleTransportModels',
]

post_calc = [os.path.join(env['LIB_PLATFORM_INSTALL'],'postCalc.o')]
sources += post_calc

ostype = utils.ostype()
prepend_args = {}
if ostype == 'windows':
   prepend_args = {'LINKFLAGS' :
         '-u genericPatchFieldsLoad -u incompressibleRASModelsLoad -u turbulenceDerivedFvPatchFieldsLoad'
}

build_app(env,
          target=target,
          sources=sources,
          caelus_inc=caelus_inc,
          caelus_libs=caelus_libs,
          prepend_args=prepend_args)
