#Copyright (C) 2014 Applied CCM
import subprocess
Import('globalEnv')

# Clone the global environment so changes made he are not pass onto subsequent 
# libraries
REnv = globalEnv.Clone()

# Path to source
src = REnv['LIB_SRC']

#===============================================================================
# Additions to compiler flags for this executable
#===============================================================================
REnv.Append(CCFLAGS = '')

#===============================================================================
# Additions to include directories for this executable
#===============================================================================
lib_inc = [src + '/postProcessing/postCalc',
src + '/turbulenceModels',
src + '/turbulenceModels/incompressible/turbulenceModel/lnInclude',
src + '/turbulenceModels/incompressible/RAS/lnInclude',  
src + '/turbulenceModels/incompressible/RAS/RASModel',
src + '/transportModels',
src + '/transportModels/incompressible/lnInclude',  
]        
REnv.Prepend(CPPPATH = lib_inc)

#===============================================================================
# Additions to link library paths for this executable
#===============================================================================
lib_link_path = []
REnv.Prepend(LIBPATH = lib_link_path)

#===============================================================================
# Additions to link libraries for this executable
#===============================================================================
if REnv['WHICH_OS'] == "windows":
  REnv.Prepend(LINKFLAGS = ' -u genericPatchFieldsLoad -u incompressibleRASModelsLoad')
  lib_link = ['libcore','libincompressibleTurbulenceModel',
  'libincompressibleRASModels','libincompressibleTransportModels',
  'libgenericPatchFields']
else:
  lib_link = ['core','incompressibleTurbulenceModel','incompressibleRASModels',
  'incompressibleTransportModels','genericPatchFields']
    
REnv.Append(LIBS = lib_link)

#===============================================================================
# Sources for this executable
#===============================================================================
src_files_postCalc = [REnv['LIB_PLATFORM_INSTALL'] + '/postCalc.o']

src_files_exec = Split("""  
  R.cpp
  compatibilityFvPatchFields/turbulentIntensityKineticEnergyInlet/turbulentIntensityKineticEnergyInletFvPatchSymmTensorField.cpp
  """)

src_files = src_files_postCalc + src_files_exec
#===============================================================================
# Build this executable
#===============================================================================
binR = REnv.Program(target = 'R',
source = src_files)

#===============================================================================
# Install this executable
#===============================================================================
install_dir = REnv['BIN_PLATFORM_INSTALL']
REnv.Alias('install', install_dir)
REnv.Install(install_dir, binR)
