# -*- mode: python -*-

import utils
from build import build_app
Import('env')

# Build Fluent mesh converter
ostype = utils.ostype()

if ostype == "windows":
    src_from_flex = ['windows/fluent3DMeshToCAELUS.cpp']
else:
    src = 'fluent3DMeshToCAELUS.ll'
    tgt = 'posix/fluent3DMeshToCAELUS.cpp'
    flex_env = env.Clone()
    flex_env.CXXFile(tgt, src, LEXFLAGS='-+')
    src_from_flex = [tgt]


target = 'fluent3DMeshToCAELUS'

sources = Split("""
""") + src_from_flex

caelus_inc = [
'dynamicMesh/dynamicMesh/lnInclude'
]

caelus_libs = [
'core',
'dynamicMesh'
]

build_app(env,
          target=target,
          sources=sources,
          caelus_inc=caelus_inc,
          caelus_libs=caelus_libs)
