# -*- mode: python -*-

import os
import utils
from build import build_app
Import('env')

target = "vofDyMSolver"

sources = Split("""
vofDyMSolver.cpp
""")

caelus_inc = [
'turbulenceModels/',
'turbulenceModels/incompressible/turbulenceModel/lnInclude',
'transportModels',
'transportModels/incompressible/singlePhaseTransportModel',
'transportModels/incompressible/lnInclude',
'transportModels/interfaceProperties/lnInclude',
'fvOptions/lnInclude',
'sampling/lnInclude',
'dynamicMesh/dynamicMesh/lnInclude',
'dynamicMesh/dynamicFvMesh/lnInclude',
]

caelus_libs = [
'core',
'incompressibleTurbulenceModel',
'incompressibleRASModels',
'incompressibleLESModels',
'incompressibleVLESModels',
'incompressibleTransportModels',
'turbulenceDerivedFvPatchFields',
'interfaceProperties',
'twoPhaseInterfaceProperties',
'fvOptions',
'sampling',
'dynamicMesh',
'dynamicFvMesh',
'topoChangerFvMesh'
]

local_dir = env.Dir(".").srcnode().abspath
vof_dir = os.path.join(local_dir, '../')

append_args = {}
append_args = { 'CPPPATH' : [os.path.normpath(vof_dir)] }

ostype = utils.ostype()
prepend_args = {}
if ostype == 'windows':
   prepend_args = {'LINKFLAGS' :
            '-u incompressibleRASModelsLoad -u incompressibleLESModelsLoad -u incompressibleVLESModelsLoad -u interfacePropertiesLoad -u turbulenceDerivedFvPatchFieldsLoad'
}

build_app(env,
          target=target,
          sources=sources,
          caelus_inc=caelus_inc,
          caelus_libs=caelus_libs,
          prepend_args=prepend_args,
          append_args=append_args)
