#Copyright (C) 2014 Applied CCM
import subprocess
Import('globalEnv')

# Clone the global environment so changes made he are not pass onto subsequent 
# libraries
flattenMeshEnv = globalEnv.Clone()

# Path to source
src = flattenMeshEnv['LIB_SRC']

flattenMeshEnv.Append(CXXFLAGS = '')
#===============================================================================
# Additions to compiler flags for this executable
#===============================================================================
flattenMeshEnv.Append(CCFLAGS = '')

#===============================================================================
# Additions to include directories for this executable
#===============================================================================
lib_inc = [src + '/dynamicMesh/lnInclude'
]

flattenMeshEnv.Prepend(CPPPATH = lib_inc)

#===============================================================================
# Additions to link library paths for this executable
#===============================================================================
lib_link_path = []
flattenMeshEnv.Prepend(LIBPATH = lib_link_path)

#===============================================================================
# Additions to link libraries for this executable
#===============================================================================
if flattenMeshEnv['WHICH_OS'] == "windows":
  lib_link = ['libdynamicMesh']
else:
  lib_link = ['dynamicMesh']
  
flattenMeshEnv.Append(LIBS = lib_link)

#===============================================================================
# Sources for this executable
#===============================================================================
src_files = Split("""
  flattenMesh.cpp
  """)

#===============================================================================
# Build this executable
#===============================================================================
binflattenMesh = flattenMeshEnv.Program(target = 
'flattenMesh', source = src_files)

#===============================================================================
# Install this executable
#===============================================================================
install_dir = flattenMeshEnv['BIN_PLATFORM_INSTALL']
flattenMeshEnv.Alias('install', install_dir)
flattenMeshEnv.Install(install_dir, binflattenMesh)
