#Copyright (C) 2014 Applied CCM
import subprocess
Import('globalEnv')

# Clone the global environment so changes made he are not pass onto subsequent 
# libraries
moveMeshEnv = globalEnv.Clone()

# Path to source
src = moveMeshEnv['LIB_SRC']

moveMeshEnv.Append(CXXFLAGS = '')
#===============================================================================
# Additions to compiler flags for this executable
#===============================================================================
moveMeshEnv.Append(CCFLAGS = '')

#===============================================================================
# Additions to include directories for this executable
#===============================================================================
lib_inc = [src + '/dynamicMesh/lnInclude']
moveMeshEnv.Prepend(CPPPATH = lib_inc)

#===============================================================================
# Additions to link library paths for this executable
#===============================================================================
lib_link_path = []
moveMeshEnv.Prepend(LIBPATH = lib_link_path)

#===============================================================================
# Additions to link libraries for this executable
#===============================================================================
lib_link = ['dynamicMesh']
  
moveMeshEnv.Append(LIBS = lib_link)

#===============================================================================
# Sources for this executable
#===============================================================================
src_files = Split("""
  moveMesh.cpp
  """)

#===============================================================================
# Build this executable
#===============================================================================
binmoveMesh = moveMeshEnv.Program(target = 
'moveMesh', source = src_files)

#===============================================================================
# Install this executable
#===============================================================================
install_dir = moveMeshEnv['BIN_PLATFORM_INSTALL']
moveMeshEnv.Alias('install', install_dir)
moveMeshEnv.Install(install_dir, binmoveMesh)
