#Copyright (C) 2014 Applied CCM
import subprocess
Import('globalEnv')

# Clone the global environment so changes made he are not pass onto subsequent 
# libraries
cpbnsSIMPLEEnv = globalEnv.Clone()

# Path to source
src = cpbnsSIMPLEEnv['LIB_SRC']

#===============================================================================
# Additions to compiler flags for this executable
#===============================================================================
cpbnsSIMPLEEnv.Append(CCFLAGS = '')

#===============================================================================
# Additions to include directories for this executable
#===============================================================================
lib_inc = [cpbnsSIMPLEEnv['LIB_SRC'] +  '/turbulenceModels',
src + '/turbulenceModels/compressible/turbulenceModel/lnInclude', 
src + '/turbulenceModels/compressible/RAS/RASModel', 
src + '/turbulenceModels/compressible/RAS/lnInclude',
src + '/thermophysicalModels',
src + '/thermophysicalModels/basic/psiThermo/basicPsiThermo',
src + '/thermophysicalModels/basic/basicThermo',
src + '/transportModels/basic/lnInclude',
src + '/fvOptions/lnInclude',
src + '/sampling/lnInclude'
]
cpbnsSIMPLEEnv.Prepend(CPPPATH = lib_inc)

#===============================================================================
# Additions to link library paths for this executable
#===============================================================================
lib_link_path = []
cpbnsSIMPLEEnv.Prepend(LIBPATH = lib_link_path)

#===============================================================================
# Additions to link libraries for this executable
#===============================================================================
if cpbnsSIMPLEEnv['WHICH_OS'] == "windows":
  cpbnsSIMPLEEnv.Prepend(LINKFLAGS = ' -u compressibleRASModelsLoad')

lib_link = ['compressibleTurbulenceModel', 'compressibleRASModels',
'basicThermophysicalModels', 'fvOptions', 'sampling']
  
cpbnsSIMPLEEnv.Append(LIBS = lib_link)

#===============================================================================
# Sources for this executable
#===============================================================================
src_files = Split("""
  cpbnsSIMPLE.cpp
  """)

#===============================================================================
# Build this executable
#===============================================================================
bincpbnsSIMPLE = cpbnsSIMPLEEnv.Program(target = 'cpbnsSIMPLE',
source = src_files)

#===============================================================================
# Install this executable
#===============================================================================
install_dir = cpbnsSIMPLEEnv['BIN_PLATFORM_INSTALL']
cpbnsSIMPLEEnv.Alias('install', install_dir)
cpbnsSIMPLEEnv.Install(install_dir, bincpbnsSIMPLE)
