# -*- mode: python -*-

from build import build_lib
Import('env')

target = 'compressibleLESModels'

sources = Split("""
compressibleLESdelta/compressibleLESdelta.cpp
vanDriestDelta/vanDriestDelta.cpp
LESModel/LESModel.cpp
GenEddyVisc/GenEddyVisc.cpp
GenSGSStress/GenSGSStress.cpp
laminar/laminar.cpp
coherentStructureModel/coherentStructureModel.cpp
Smagorinsky/Smagorinsky.cpp
oneEqEddy/oneEqEddy.cpp
dynOneEqEddy/dynOneEqEddy.cpp
WALE/WALE.cpp
SpalartAllmarasDES/SpalartAllmarasDES.cpp
SpalartAllmarasDDES/SpalartAllmarasDDES.cpp
SpalartAllmarasIDDES/SpalartAllmarasIDDES.cpp
derivedFvPatchFields/wallFunctions/muSgsWFs/muSgsUSpaldingWF/muSgsUSpaldingWFFvPatchScalarField.cpp
derivedFvPatchFields/wallFunctions/alphaSgsWFs/alphaSgsWF/alphaSgsWFFvPatchScalarField.cpp
derivedFvPatchFields/wallFunctions/alphaSgsWFs/alphaSgsJayaWF/alphaSgsJayaWFFvPatchScalarField.cpp
""")

caelus_inc = [
'turbulenceModels',
'thermophysicalModels/basic/lnInclude',
'turbulenceModels/LES/LESdeltas/lnInclude',
'turbulenceModels/LES/LESfilters/lnInclude'
]

caelus_libs = [
'core',
'compressibleTurbulenceModel',
'LESfilters',
'LESdeltas'
]

build_lib(env,
          target=target,
          sources=sources,
          caelus_inc=caelus_inc,
          caelus_libs=caelus_libs)
