#Copyright (C) 2014 Applied CCM
import subprocess
Import('globalEnv')

# Clone the global environment so changes made he are not pass onto subsequent 
# libraries
createBaffles_oldEnv = globalEnv.Clone()

# Path to source
src = createBaffles_oldEnv['LIB_SRC']

#===============================================================================
# Additions to compiler flags for this executable
#===============================================================================
createBaffles_oldEnv.Append(CCFLAGS = '')

#===============================================================================
# Additions to include directories for this executable
#===============================================================================
lib_inc = [src + '/dynamicMesh/lnInclude']

createBaffles_oldEnv.Prepend(CPPPATH = lib_inc)

#===============================================================================
# Additions to link library paths for this executable
#===============================================================================
lib_link_path = []
createBaffles_oldEnv.Prepend(LIBPATH = lib_link_path)

#===============================================================================
# Additions to link libraries for this executable
#===============================================================================
if createBaffles_oldEnv['WHICH_OS'] == "windows":
  createBaffles_oldEnv.Prepend(LINKFLAGS = ' -u genericPatchFieldsLoad')

lib_link = ['dynamicMesh', 'genericPatchFields']
  
createBaffles_oldEnv.Append(LIBS = lib_link)

#===============================================================================
# Sources for this executable
#===============================================================================
src_files = Split("""
  createBaffles.cpp
  """)

#===============================================================================
# Build this executable
#===============================================================================
bincreateBaffles_old = createBaffles_oldEnv.Program(target = 
'createBaffles_old', source = src_files)

#===============================================================================
# Install this executable
#===============================================================================
install_dir = createBaffles_oldEnv['BIN_PLATFORM_INSTALL']
createBaffles_oldEnv.Alias('install', install_dir)
createBaffles_oldEnv.Install(install_dir, bincreateBaffles_old)
