#Copyright (C) 2014 Applied CCM
import subprocess
Import('globalEnv')

# Clone the global environment so changes made he are not pass onto subsequent 
# libraries
zipUpMeshEnv = globalEnv.Clone()

# Path to source
src = zipUpMeshEnv['LIB_SRC']

zipUpMeshEnv.Append(CXXFLAGS = '')
#===============================================================================
# Additions to compiler flags for this executable
#===============================================================================
zipUpMeshEnv.Append(CCFLAGS = '')

#===============================================================================
# Additions to include directories for this executable
#===============================================================================
lib_inc = []

zipUpMeshEnv.Prepend(CPPPATH = lib_inc)

#===============================================================================
# Additions to link library paths for this executable
#===============================================================================
lib_link_path = []
zipUpMeshEnv.Prepend(LIBPATH = lib_link_path)

#===============================================================================
# Additions to link libraries for this executable
#===============================================================================
lib_link = []
  
zipUpMeshEnv.Append(LIBS = lib_link)

#===============================================================================
# Sources for this executable
#===============================================================================
src_files = Split("""
  zipUpMesh.cpp
  """)

#===============================================================================
# Build this executable
#===============================================================================
binzipUpMesh = zipUpMeshEnv.Program(target = 
'zipUpMesh', source = src_files)

#===============================================================================
# Install this executable
#===============================================================================
install_dir = zipUpMeshEnv['BIN_PLATFORM_INSTALL']
zipUpMeshEnv.Alias('install', install_dir)
zipUpMeshEnv.Install(install_dir, binzipUpMesh)
