#Copyright (C) 2014 Applied CCM
import subprocess
Import('globalEnv')

# Clone the global environment so changes made he are not pass onto subsequent 
# libraries
temporalInterpolateEnv = globalEnv.Clone()

# Path to source
src = temporalInterpolateEnv['LIB_SRC']

#===============================================================================
# Additions to compiler flags for this executable
#===============================================================================
temporalInterpolateEnv.Append(CCFLAGS = '')

#===============================================================================
# Additions to include directories for this executable
#===============================================================================
lib_inc = []
temporalInterpolateEnv.Prepend(CPPPATH = lib_inc)

#===============================================================================
# Additions to link library paths for this executable
#===============================================================================
lib_link_path = []
temporalInterpolateEnv.Prepend(LIBPATH = lib_link_path)

#===============================================================================
# Additions to link libraries for this executable
#===============================================================================
if temporalInterpolateEnv['WHICH_OS'] == "windows":
  lib_link = []
else:
  lib_link = []
     

temporalInterpolateEnv.Append(LIBS = lib_link)

#===============================================================================
# Sources for this executable
#===============================================================================
src_files = Split("""
  temporalInterpolate.cpp
  """)

#===============================================================================
# Build this executable
#===============================================================================
bintemporalInterpolate = temporalInterpolateEnv.Program(target = 'temporalInterpolate', 
source = src_files)

#===============================================================================
# Install this executable
#===============================================================================
install_dir = temporalInterpolateEnv['BIN_PLATFORM_INSTALL']
temporalInterpolateEnv.Alias('install', install_dir)
temporalInterpolateEnv.Install(install_dir, bintemporalInterpolate)
