# -*- mode: python -*-

from build import build_lib
Import('env')

target = 'rigidBodyMeshMotion'

sources = Split("""
rigidBodyMeshMotion.cpp
 """)

caelus_inc = [
'dynamicMesh/dynamicMesh/lnInclude',
'dynamicMesh/meshMotion/rigidBodyDynamics/lnInclude',
'dynamicMesh/meshMotion/fvMotionSolver/lnInclude',
'postProcessing/functionObjects/forces/lnInclude'
]

caelus_libs = [
'core',
'dynamicMesh',
'fvMotionSolvers',
'rigidBodyDynamics',
'forces'
]

build_lib(env,
          target=target,
          sources=sources,
          caelus_inc=caelus_inc,
          caelus_libs=caelus_libs)
