# -*- mode: python -*-

import utils
from build import build_app
Import('env')

target = 'wallHeatFlux'

sources = Split("""
wallHeatFlux_app.cpp
""")

caelus_inc = [
'turbulenceModels',
'turbulenceModels/compressible/turbulenceModel/lnInclude',
'turbulenceModels/compressible/RAS/lnInclude',
'turbulenceModels/compressible/RAS/RASModel',
'thermophysicalModels/specie/lnInclude',
'thermophysicalModels/reactionThermo/lnInclude',
'thermophysicalModels/basic/lnInclude',
'thermophysicalModels/solidThermo/lnInclude'
]

caelus_libs = [
'core',
'compressibleRASModels',
'reactionThermophysicalModels',
'specie',
'fluidThermophysicalModels',
'compressibleTurbulenceModel',
'solidThermo'
]

ostype = utils.ostype()
prepend_args = {}
if ostype == 'windows':
   prepend_args = {'LINKFLAGS' :
         '-u genericPatchFieldsLoad -u compressibleRASModelsLoad -u turbulenceDerivedFvPatchFieldsLoad'
}

build_app(env,
          target=target,
          sources=sources,
          caelus_inc=caelus_inc,
          caelus_libs=caelus_libs,
          prepend_args=prepend_args)
