# -*- mode: python -*-

from build import build_lib
Import('env')

target = 'ptscotchDecomp'

sources = Split("""
ptscotchDecomp.cpp
""")

caelus_inc = [
"parallel/decompose/decompositionMethods/lnInclude",
env['SCOTCH_INC_PATH']
]

caelus_libs = [
'core',
'decompositionMethods',
'scotch',
'ptscotch',
'ptscotcherr',
'ptscotcherrexit',
env['MPI_LIB_NAME']
]

append_args = dict(
    LIBPATH=[
        env['SCOTCH_LIB_PATH'],
        env['MPI_LIB_PATH']
    ]
)

build_lib(env,
          target=target,
          sources=sources,
          caelus_inc=caelus_inc,
          caelus_libs=caelus_libs,
          append_args=append_args)
