# -*- mode: python -*-

from build import build_app
Import('env')

target = 'diagnosePar'

sources = Split("""
diagnosePar.cpp
""")

caelus_inc = [
'parallel/diagnose/diagnose/lnInclude',
'parallel/diagnose/decompositionMethods/lnInclude',
'lagrangian/basic/lnInclude'
]

caelus_libs = [
'core'
]

build_app(env,
          target=target,
          sources=sources,
          caelus_inc=caelus_inc,
          caelus_libs=caelus_libs)
