#Copyright (C) 2014 Applied CCM
import subprocess
Import('globalEnv')

# Clone the global environment so changes made he are not pass onto subsequent 
# libraries
patchIntegrateEnv = globalEnv.Clone()

# Path to source
src = patchIntegrateEnv['LIB_SRC']

#===============================================================================
# Additions to compiler flags for this executable
#===============================================================================
patchIntegrateEnv.Append(CCFLAGS = '')

#===============================================================================
# Additions to include directories for this executable
#===============================================================================
lib_inc = [src + '/lagrangian/basic/lnInclude']

patchIntegrateEnv.Prepend(CPPPATH = lib_inc)

#===============================================================================
# Additions to link library paths for this executable
#===============================================================================
lib_link_path = []
patchIntegrateEnv.Prepend(LIBPATH = lib_link_path)

#===============================================================================
# Additions to link libraries for this executable
#===============================================================================
if patchIntegrateEnv['WHICH_OS'] == "windows":
  patchIntegrateEnv.Prepend(LINKFLAGS = ' -u genericPatchFieldsLoad')

lib_link = ['genericPatchFields','lagrangian']
     
patchIntegrateEnv.Append(LIBS = lib_link)

#===============================================================================
# Sources for this executable
#===============================================================================
src_files = Split("""
  patchIntegrate.cpp
  """)

#===============================================================================
# Build this executable
#===============================================================================
binpatchIntegrate = patchIntegrateEnv.Program(target = 'patchIntegrate', 
source = src_files)

#===============================================================================
# Install this executable
#===============================================================================
install_dir = patchIntegrateEnv['BIN_PLATFORM_INSTALL']
patchIntegrateEnv.Alias('install', install_dir)
patchIntegrateEnv.Install(install_dir, binpatchIntegrate)
