# -*- mode: python -*-

import utils
from build import build_app
Import('env')

target = "buoyantSimpleSolver"

sources = Split("""
buoyantSimpleSolver.cpp
""")

caelus_inc = [
'turbulenceModels',
'turbulenceModels/compressible/turbulenceModel',
'turbulenceModels/compressible/turbulenceModel/lnInclude',
'turbulenceModels/compressible/RAS/lnInclude',
'thermophysicalModels/basic/lnInclude',
'thermophysicalModels/radiation/lnInclude',
'fvOptions/lnInclude',
'sampling/lnInclude'
]

caelus_libs = [
'core',
'compressibleTurbulenceModel',
'compressibleRASModels',
'fluidThermophysicalModels',
'turbulenceDerivedFvPatchFields',
'radiationModels',
'specie',
'fvOptions',
'sampling'
]

ostype = utils.ostype()
prepend_args = {}
if ostype == 'windows':
   prepend_args = {'LINKFLAGS' :
            '-u turbulenceDerivedFvPatchFieldsLoad -u compressibleRASModelsLoad'
}

build_app(env,
          target=target,
          sources=sources,
          caelus_inc=caelus_inc,
          caelus_libs=caelus_libs,
          prepend_args=prepend_args)
