#Copyright (C) 2014 Applied CCM
import subprocess
Import('globalEnv')

# Clone the global environment so changes made he are not pass onto subsequent 
# libraries
selectCellsEnv = globalEnv.Clone()

# Path to source
src = selectCellsEnv['LIB_SRC']

#===============================================================================
# Additions to compiler flags for this executable
#===============================================================================
selectCellsEnv.Append(CCFLAGS = '')

#===============================================================================
# Additions to include directories for this executable
#===============================================================================
lib_inc = [src + '/dynamicMesh/lnInclude', src + '/lagrangian/basic/lnInclude']
selectCellsEnv.Prepend(CPPPATH = lib_inc)

#===============================================================================
# Additions to link library paths for this executable
#===============================================================================
lib_link_path = []
selectCellsEnv.Prepend(LIBPATH = lib_link_path)

#===============================================================================
# Additions to link libraries for this executable
#===============================================================================
if selectCellsEnv['WHICH_OS'] == "windows":
  lib_link = ['libdynamicMesh','liblagrangian']
else:
  lib_link = ['dynamicMesh','lagrangian']
     

selectCellsEnv.Append(LIBS = lib_link)

#===============================================================================
# Sources for this executable
#===============================================================================
src_files = Split("""
  edgeStats.cpp
  selectCells.cpp
  """)

#===============================================================================
# Build this executable
#===============================================================================
binselectCells = selectCellsEnv.Program(target = 'selectCells', 
source = src_files)

#===============================================================================
# Install this executable
#===============================================================================
install_dir = selectCellsEnv['BIN_PLATFORM_INSTALL']
selectCellsEnv.Alias('install', install_dir)
selectCellsEnv.Install(install_dir, binselectCells)
