#Copyright (C) 2014 Applied CCM
import subprocess
Import('globalEnv')

# Clone the global environment so changes made he are not pass onto subsequent 
# libraries
caelusDataToFluentEnv = globalEnv.Clone()

# Path to source
src = caelusDataToFluentEnv['LIB_SRC']

#===============================================================================
# Additions to compiler flags for this executable
#===============================================================================
caelusDataToFluentEnv.Append(CCFLAGS = '')

#===============================================================================
# Additions to include directories for this executable
#===============================================================================
lib_inc = []
caelusDataToFluentEnv.Prepend(CPPPATH = lib_inc)

#===============================================================================
# Additions to link library paths for this executable
#===============================================================================
lib_link_path = []
caelusDataToFluentEnv.Prepend(LIBPATH = lib_link_path)

#===============================================================================
# Additions to link libraries for this executable
#===============================================================================
if caelusDataToFluentEnv['WHICH_OS'] == "windows":
  caelusDataToFluentEnv.Prepend(LINKFLAGS = ' -u genericPatchFieldsLoad')
  lib_link = ['libgenericPatchFields']
else:
  lib_link = ['genericPatchFields']
     

caelusDataToFluentEnv.Append(LIBS = lib_link)

#===============================================================================
# Sources for this executable
#===============================================================================
src_files = Split("""
  writeFluentScalarField.cpp
  writeFluentVectorField.cpp
  caelusDataToFluent.cpp
  """)

#===============================================================================
# Build this executable
#===============================================================================
bincaelusDataToFluent = caelusDataToFluentEnv.Program(target = 'caelusDataToFluent', 
source = src_files)

#===============================================================================
# Install this executable
#===============================================================================
install_dir = caelusDataToFluentEnv['BIN_PLATFORM_INSTALL']
caelusDataToFluentEnv.Alias('install', install_dir)
caelusDataToFluentEnv.Install(install_dir, bincaelusDataToFluent)
