#Copyright (C) 2014 Applied CCM
import subprocess
Import('globalEnv')

# Clone the global environment so changes made he are not pass onto subsequent 
# libraries
caelusToTetDualMeshEnv = globalEnv.Clone()

# Path to source
src = caelusToTetDualMeshEnv['LIB_SRC']

#===============================================================================
# Additions to compiler flags for this executable
#===============================================================================
caelusToTetDualMeshEnv.Append(CCFLAGS = '')

#===============================================================================
# Additions to include directories for this executable
#===============================================================================
lib_inc = []
caelusToTetDualMeshEnv.Prepend(CPPPATH = lib_inc)

#===============================================================================
# Additions to link library paths for this executable
#===============================================================================
lib_link_path = []
caelusToTetDualMeshEnv.Prepend(LIBPATH = lib_link_path)

#===============================================================================
# Additions to link libraries for this executable
#===============================================================================
if caelusToTetDualMeshEnv['WHICH_OS'] == "windows":
  lib_link = []
else:
  lib_link = []
     

caelusToTetDualMeshEnv.Append(LIBS = lib_link)

#===============================================================================
# Sources for this executable
#===============================================================================
src_files = Split("""
  caelusToTetDualMesh.cpp
  """)

#===============================================================================
# Build this executable
#===============================================================================
bincaelusToTetDualMesh = caelusToTetDualMeshEnv.Program(target = 'caelusToTetDualMesh', 
source = src_files)

#===============================================================================
# Install this executable
#===============================================================================
install_dir = caelusToTetDualMeshEnv['BIN_PLATFORM_INSTALL']
caelusToTetDualMeshEnv.Alias('install', install_dir)
caelusToTetDualMeshEnv.Install(install_dir, bincaelusToTetDualMesh)
