#Copyright (C) 2014 Applied CCM
import subprocess
Import('globalEnv')

# Clone the global environment so changes made he are not pass onto subsequent 
# libraries
combinePatchFacesEnv = globalEnv.Clone()

# Path to source
src = combinePatchFacesEnv['LIB_SRC']

#===============================================================================
# Additions to compiler flags for this executable
#===============================================================================
combinePatchFacesEnv.Append(CCFLAGS = '')

#===============================================================================
# Additions to include directories for this executable
#===============================================================================
lib_inc = [src + '/dynamicMesh/lnInclude']
combinePatchFacesEnv.Prepend(CPPPATH = lib_inc)

#===============================================================================
# Additions to link library paths for this executable
#===============================================================================
lib_link_path = []
combinePatchFacesEnv.Prepend(LIBPATH = lib_link_path)

#===============================================================================
# Additions to link libraries for this executable
#===============================================================================
if combinePatchFacesEnv['WHICH_OS'] == "windows":
  lib_link = ['libdynamicMesh']
else:
  lib_link = ['dynamicMesh']
     

combinePatchFacesEnv.Append(LIBS = lib_link)

#===============================================================================
# Sources for this executable
#===============================================================================
src_files = Split("""
  combinePatchFaces.cpp
  """)

#===============================================================================
# Build this executable
#===============================================================================
bincombinePatchFaces = combinePatchFacesEnv.Program(target = 'combinePatchFaces', 
source = src_files)

#===============================================================================
# Install this executable
#===============================================================================
install_dir = combinePatchFacesEnv['BIN_PLATFORM_INSTALL']
combinePatchFacesEnv.Alias('install', install_dir)
combinePatchFacesEnv.Install(install_dir, bincombinePatchFaces)
