#Copyright (C) 2014 Applied CCM
import subprocess
Import('globalEnv')

# Clone the global environment so changes made he are not pass onto subsequent 
# libraries
pimpleDyMSolEnv = globalEnv.Clone()

# Path to source
src = pimpleDyMSolEnv['LIB_SRC']

#===============================================================================
# Additions to include directories for this executable
#===============================================================================
lib_inc = ['../', src + '/turbulenceModels/incompressible/turbulenceModel',
src + '/turbulenceModels/incompressible/turbulenceModel/lnInclude', 
src + '/transportModels',
src + '/transportModels/incompressible/singlePhaseTransportModel',
src + '/transportModels/incompressible/lnInclude',
src + '/fvOptions/lnInclude',
src + '/sampling/lnInclude',
src + '/dynamicFvMesh/lnInclude',
src + '/dynamicMesh/lnInclude'
]
pimpleDyMSolEnv.Prepend(CPPPATH = lib_inc)

#===============================================================================
# Additions to link libraries for this executable
#===============================================================================
if pimpleDyMSolEnv['WHICH_OS'] == "windows":
  pimpleDyMSolEnv.Prepend(LINKFLAGS = ' -u incompressibleRASModelsLoad  -u incompressibleLESModelsLoad')

lib_link = ['libincompressibleTurbulenceModel', 'libincompressibleRASModels',
'libincompressibleLESModels','libincompressibleTransportModels', 'fvOptions', 'sampling',
'dynamicFvMesh','topoChangerFvMesh','dynamicMesh']
pimpleDyMSolEnv.Append(LIBS = lib_link)

#===============================================================================
# Sources for this executable
#===============================================================================
src_files = Split("""
  pimpleDyMSolver.cpp
  """)

#===============================================================================
# Build this executable
#===============================================================================
binpimpleDyMSol = pimpleDyMSolEnv.Program(target = 'pimpleDyMSolver',
source = src_files)

#===============================================================================
# Install this executable
#===============================================================================
install_dir = pimpleDyMSolEnv['BIN_PLATFORM_INSTALL']
pimpleDyMSolEnv.Alias('install', install_dir)
pimpleDyMSolEnv.Install(install_dir, binpimpleDyMSol)
