#Copyright (C) 2014 Applied CCM
import subprocess
Import('globalEnv')

# Clone the global environment so changes made he are not pass onto subsequent 
# libraries
caelusListTimesEnv = globalEnv.Clone()

# Path to source
src = caelusListTimesEnv['LIB_SRC']

#===============================================================================
# Additions to compiler flags for this executable
#===============================================================================
caelusListTimesEnv.Append(CCFLAGS = '')

#===============================================================================
# Additions to include directories for this executable
#===============================================================================
lib_inc = []
caelusListTimesEnv.Prepend(CPPPATH = lib_inc)

#===============================================================================
# Additions to link library paths for this executable
#===============================================================================
lib_link_path = []
caelusListTimesEnv.Prepend(LIBPATH = lib_link_path)

#===============================================================================
# Additions to link libraries for this executable
#===============================================================================
lib_link = []
     

caelusListTimesEnv.Append(LIBS = lib_link)

#===============================================================================
# Sources for this executable
#===============================================================================
src_files = Split("""
  caelusListTimes.cpp
  """)

#===============================================================================
# Build this executable
#===============================================================================
bincaelusListTimes = caelusListTimesEnv.Program(target = 'caelusListTimes', 
source = src_files)

#===============================================================================
# Install this executable
#===============================================================================
install_dir = caelusListTimesEnv['BIN_PLATFORM_INSTALL']
caelusListTimesEnv.Alias('install', install_dir)
caelusListTimesEnv.Install(install_dir, bincaelusListTimes)
