# -*- mode: python -*-

from build import build_lib
Import('env')

target = 'solidProperties'

sources = Split("""
solidProperties/solidProperties.cpp
solidProperties/solidPropertiesNew.cpp
ash/ash.cpp
C/C.cpp
CaCO3/CaCO3.cpp
""")

caelus_inc = [
'thermophysicalModels/specie/lnInclude'
]

caelus_libs = [
'core'
]

build_lib(env,
          target=target,
          sources=sources,
          caelus_inc=caelus_inc,
          caelus_libs=caelus_libs)
