#Copyright (C) 2014 Applied CCM
import subprocess
Import('globalEnv')

# Clone the global environment so changes made he are not pass onto subsequent 
# libraries
transformPointsEnv = globalEnv.Clone()

# Path to source
src = transformPointsEnv['LIB_SRC']

transformPointsEnv.Append(CXXFLAGS = '')
#===============================================================================
# Additions to compiler flags for this executable
#===============================================================================
transformPointsEnv.Append(CCFLAGS = '')

#===============================================================================
# Additions to include directories for this executable
#===============================================================================
lib_inc = []

transformPointsEnv.Prepend(CPPPATH = lib_inc)

#===============================================================================
# Additions to link library paths for this executable
#===============================================================================
lib_link_path = []
transformPointsEnv.Prepend(LIBPATH = lib_link_path)

#===============================================================================
# Additions to link libraries for this executable
#===============================================================================
if transformPointsEnv['WHICH_OS'] == "windows":
  transformPointsEnv.Prepend(LINKFLAGS = ' -u genericPatchFieldsLoad')

lib_link = ['genericPatchFields']
  
transformPointsEnv.Append(LIBS = lib_link)

#===============================================================================
# Sources for this executable
#===============================================================================
src_files = Split("""
  transformPoints.cpp
  """)

#===============================================================================
# Build this executable
#===============================================================================
bintransformPoints = transformPointsEnv.Program(target = 
'transformPoints', source = src_files)

#===============================================================================
# Install this executable
#===============================================================================
install_dir = transformPointsEnv['BIN_PLATFORM_INSTALL']
transformPointsEnv.Alias('install', install_dir)
transformPointsEnv.Install(install_dir, bintransformPoints)
