#Copyright (C) 2014 Applied CCM
import subprocess
Import('globalEnv')

# Clone the global environment so changes made he are not pass onto subsequent 
# libraries
decomposeEnv = globalEnv.Clone()

# Path to source
src = decomposeEnv['LIB_SRC']

#===============================================================================
# Additions to compiler flags for this library
#===============================================================================
decomposeEnv.Append(CXXFLAGS = '')

#===============================================================================
# Additions to include directories for this library
#===============================================================================
lib_inc = ['lnInclude', src + '/lagrangian/lnInclude']
decomposeEnv.Prepend(CPPPATH = lib_inc)

#===============================================================================
# Additions to link library paths for this library
#===============================================================================
lib_link_path = []
decomposeEnv.Prepend(LIBPATH = lib_link_path)

#===============================================================================
# Additions to link libraries for this library
#===============================================================================
lib_link = ['core', 'lagrangian']
decomposeEnv.Append(LIBS = lib_link)

#===============================================================================
# Sources for this library
#===============================================================================
src_files = Split("""
  fvFieldDecomposer.cpp
  """)

#===============================================================================
# Build this library
#===============================================================================
libdecompose = decomposeEnv.SharedLibrary(target = 'decompose', 
source = src_files)

#===============================================================================
# Install this library
#===============================================================================
install_dir = decomposeEnv['LIB_PLATFORM_INSTALL']
decomposeEnv.Alias('install', install_dir)
decomposeEnv.Install(install_dir, libdecompose)

if (decomposeEnv['WHICH_OS'] == "darwin"):

  decomposeEnv.Append(SHLINKFLAGS ='-install_name @' + decomposeEnv['LIB_PLATFORM_INSTALL'] + '/libdecompose.dylib')
