# -*- mode: python -*-

from build import build_lib
Import('env')

target = 'compressibleVLESModels'

sources = Split("""
VLESModel/compressibleVLESModel.cpp
laminar/compressibleVLESLaminar.cpp
realizableKE/compressibleVLESRealizableKE.cpp
kOmegaSST/compressibleVLESkOmegaSST.cpp
kOmegaSSTCSModel/compressibleVLESkOmegaSSTCSModel.cpp
SpalartAllmaras/compressibleVLESSpalartAllmaras.cpp
""")

caelus_inc = [
'turbulenceModels',
'thermophysicalModels/basic/lnInclude',
'thermophysicalModels/basicSolidThermo/lnInclude'
]

caelus_libs = [
'core',
'specie',
'fluidThermophysicalModels',
'compressibleTurbulenceModel'
]

build_lib(env,
          target=target,
          sources=sources,
          caelus_inc=caelus_inc,
          caelus_libs=caelus_libs)
