# -*- mode: python -*-

from build import build_lib
Import('env')

target = 'compressibleVLESModels'

sources = Split("""
VLESModel/VLESModel.cpp
laminar/laminar.cpp
realizableKE/realizableKE.cpp
kOmegaSST/kOmegaSST.cpp
kOmegaSSTCSModel/kOmegaSSTCSModel.cpp
SpalartAllmaras/SpalartAllmaras.cpp
""")

caelus_inc = [
'turbulenceModels',
'thermophysicalModels/basic/lnInclude',
'thermophysicalModels/basicSolidThermo/lnInclude'
]

caelus_libs = [
'core',
'specie',
'basicThermophysicalModels',
'compressibleTurbulenceModel'
]

build_lib(env,
          target=target,
          sources=sources,
          caelus_inc=caelus_inc,
          caelus_libs=caelus_libs)
