#Copyright (C) 2014 Applied CCM
import subprocess
Import('globalEnv')

# Clone the global environment so changes made he are not pass onto subsequent 
# libraries
writeMeshObjEnv = globalEnv.Clone()

#===============================================================================
# Additions to compiler flags for this executable
#===============================================================================
writeMeshObjEnv.Append(CCFLAGS = '')

#===============================================================================
# Additions to include directories for this executable
#===============================================================================
lib_inc = []

writeMeshObjEnv.Prepend(CPPPATH = lib_inc)

#===============================================================================
# Additions to link library paths for this executable
#===============================================================================
lib_link_path = []
writeMeshObjEnv.Prepend(LIBPATH = lib_link_path)

#===============================================================================
# Additions to link libraries for this executable
#===============================================================================
lib_link = []
  
writeMeshObjEnv.Append(LIBS = lib_link)

#===============================================================================
# Sources for this executable
#===============================================================================
src_files = Split("""
  writeMeshObj.cpp
  """)

#===============================================================================
# Build this executable
#===============================================================================
binwriteMeshObj = writeMeshObjEnv.Program(target =
 'writeMeshObj', source = src_files)

#===============================================================================
# Install this executable
#===============================================================================
install_dir = writeMeshObjEnv['BIN_PLATFORM_INSTALL']
writeMeshObjEnv.Alias('install', install_dir)
writeMeshObjEnv.Install(install_dir, binwriteMeshObj)
