# -*- mode: python -*-

from build import build_lib
Import('env')

target = 'incompressibleTurbulenceModel'

sources = Split("""
turbulenceModel.cpp
laminar/laminar.cpp
derivedFvPatchFields/wallFunctions/nutWFs/nutWF/nutWFFvPatchScalarField.cpp
derivedFvPatchFields/wallFunctions/nutWFs/nutkWF/nutkWFFvPatchScalarField.cpp
derivedFvPatchFields/wallFunctions/nutWFs/nutkRghWF/nutkRghWFFvPatchScalarField.cpp
derivedFvPatchFields/wallFunctions/nutWFs/nutkAtmRghWF/nutkAtmRghWFFvPatchScalarField.cpp
derivedFvPatchFields/wallFunctions/nutWFs/nutUWF/nutUWFFvPatchScalarField.cpp
derivedFvPatchFields/wallFunctions/nutWFs/nutUSpaldingWF/nutUSpaldingWFFvPatchScalarField.cpp
derivedFvPatchFields/wallFunctions/nutWFs/nutUTabWF/nutUTabWFFvPatchScalarField.cpp
derivedFvPatchFields/wallFunctions/nutWFs/nutLowReWF/nutLowReWFFvPatchScalarField.cpp
derivedFvPatchFields/wallFunctions/nutWFs/nutURghWF/nutURghWFFvPatchScalarField.cpp
derivedFvPatchFields/wallFunctions/epsilonWFs/epsilonWF/epsilonWFFvPatchScalarField.cpp
derivedFvPatchFields/wallFunctions/omegaWFs/omegaWF/omegaWFFvPatchScalarField.cpp
derivedFvPatchFields/wallFunctions/alphatWFs/alphatJayaWF/alphatJayaWFFvPatchScalarField.cpp
derivedFvPatchFields/turbulentHeatFluxTemperature/turbulentHeatFluxTemperatureFvPatchScalarField.cpp
derivedFvPatchFields/turbulentMixingLengthDissRateInlet/turbulentMixingLengthDissRateInletFvPatchScalarField.cpp
derivedFvPatchFields/turbulentMixingLengthFreqInlet/turbulentMixingLengthFreqInletFvPatchScalarField.cpp
derivedFvPatchFields/atmBoundaryLayerInletEpsilon/atmBoundaryLayerInletEpsilonFvPatchScalarField.cpp
derivedFvPatchFields/atmBoundaryLayerInletVelocity/atmBoundaryLayerInletVelocityFvPatchVectorField.cpp
""")

caelus_inc = [
'transportModels',
'turbulenceModels'
]

caelus_libs = [
'core'
]

build_lib(env,
          target=target,
          sources=sources,
          caelus_inc=caelus_inc,
          caelus_libs=caelus_libs)
