#Copyright (C) 2014 Applied CCM
import subprocess
Import('globalEnv')

# Clone the global environment so changes made he are not pass onto subsequent 
# libraries
patchPairEnv = globalEnv.Clone()

# Path to source
src = patchPairEnv['LIB_SRC']

#===============================================================================
# Additions to compiler flags for this library
#===============================================================================
patchPairEnv.Append(CCFLAGS = '')

#===============================================================================
# Additions to include directories for this library
#===============================================================================
lib_inc = ['lnInclude']
patchPairEnv.Prepend(CPPPATH = lib_inc)
    
#===============================================================================
# Additions to link library paths for this library
#===============================================================================
lib_link_path = []
patchPairEnv.Prepend(LIBPATH = lib_link_path)

#===============================================================================
# Additions to link libraries for this library
#===============================================================================
lib_link = ['core']
patchPairEnv.Append(LIBS = lib_link)
   
#===============================================================================
# Sources for this library
#===============================================================================
src_files = Split("""
  pairPatchAgglomeration.cpp
  """)

#===============================================================================
# Build this library
#===============================================================================
libpairPatchAgglomeration = patchPairEnv.SharedLibrary(target = 
'pairPatchAgglomeration', source = src_files)

#===============================================================================
# Install this library
#===============================================================================
install_dir = patchPairEnv['LIB_PLATFORM_INSTALL']
patchPairEnv.Alias('install', install_dir)
patchPairEnv.Install(install_dir, libpairPatchAgglomeration)

if (patchPairEnv['WHICH_OS'] == "darwin"):

  patchPairEnv.Append(SHLINKFLAGS ='-install_name @' + patchPairEnv['LIB_PLATFORM_INSTALL'] + '/libpairPatchAgglomeration.dylib')
