# -*- mode: python -*-

from build import build_lib
Import('env')

target = 'pairPatchAgglomeration'

sources = Split("""
pairPatchAgglomeration.cpp
""")

caelus_inc = []

caelus_libs = [
'core'
]

build_lib(env,
          target=target,
          sources=sources,
          caelus_inc=caelus_inc,
          caelus_libs=caelus_libs)
