# -*- mode: python -*-

from build import build_lib
Import('env')

target = 'blockMesh'

sources = Split("""
curvedEdges/BSpline.cpp
curvedEdges/CatmullRomSpline.cpp
curvedEdges/polyLine.cpp
curvedEdges/arcEdge.cpp
curvedEdges/curvedEdge.cpp
curvedEdges/lineEdge.cpp
curvedEdges/polyLineEdge.cpp
curvedEdges/lineDivide.cpp
curvedEdges/BSplineEdge.cpp
curvedEdges/splineEdge.cpp
gradingDescriptor/gradingDescriptor.cpp
gradingDescriptor/gradingDescriptors.cpp
blockDescriptor/blockDescriptor.cpp
blockDescriptor/blockDescriptorEdges.cpp
block/block.cpp
block/blockCreate.cpp
blockMesh/blockMesh.cpp
blockMesh/blockMeshCreate.cpp
blockMesh/blockMeshTopology.cpp
blockMesh/blockMeshCheck.cpp
blockMesh/blockMeshMerge.cpp
""")

caelus_inc = [
'dynamicMesh/lnInclude'
]

caelus_libs = [
'core',
'dynamicMesh'
]

build_lib(env,
          target=target,
          sources=sources,
          caelus_inc=caelus_inc,
          caelus_libs=caelus_libs)
