# -*- mode: python -*-

from build import build_lib
Import('env')

target = 'lagrangian'

sources = Split("""
particle/particle.cpp
particle/particleIO.cpp
passiveParticle/passiveParticleCloud.cpp
indexedParticle/indexedParticleCloud.cpp
InteractionLists/referredWallFace/referredWallFace.cpp
""")

caelus_inc = []

caelus_libs = [
'core'
]

build_lib(env,
          target=target,
          sources=sources,
          caelus_inc=caelus_inc,
          caelus_libs=caelus_libs)
