# -*- mode: python -*-

from build import build_lib
Import('env')

target = 'reactionThermophysicalModels'

sources = Split("""
chemistryReaders/chemistryReader/makeChemistryReaders.cpp
mixtures/basicMultiComponentMixture/basicMultiComponentMixture.cpp
combustionThermo/hCombustionThermo/hCombustionThermo.cpp
combustionThermo/hCombustionThermo/hCombustionThermoNew.cpp
combustionThermo/hCombustionThermo/hCombustionThermos.cpp
combustionThermo/hsCombustionThermo/hsCombustionThermo.cpp
combustionThermo/hsCombustionThermo/hsCombustionThermoNew.cpp
combustionThermo/hsCombustionThermo/hsCombustionThermos.cpp
combustionThermo/hhuCombustionThermo/hhuCombustionThermo.cpp
combustionThermo/hhuCombustionThermo/hhuCombustionThermoNew.cpp
combustionThermo/hhuCombustionThermo/hhuCombustionThermos.cpp
reactionThermo/hReactionThermo/hReactionThermo.cpp
reactionThermo/hReactionThermo/hReactionThermoNew.cpp
reactionThermo/hReactionThermo/hReactionThermos.cpp
reactionThermo/hsReactionThermo/hsReactionThermo.cpp
reactionThermo/hsReactionThermo/hsReactionThermoNew.cpp
reactionThermo/hsReactionThermo/hsReactionThermos.cpp
derivedFvPatchFields/fixedUnburntEnthalpy/fixedUnburntEnthalpyFvPatchScalarField.cpp
derivedFvPatchFields/gradientUnburntEnthalpy/gradientUnburntEnthalpyFvPatchScalarField.cpp
derivedFvPatchFields/mixedUnburntEnthalpy/mixedUnburntEnthalpyFvPatchScalarField.cpp
""")

caelus_inc = [
'thermophysicalModels/specie/lnInclude',
'thermophysicalModels/basic/lnInclude'
]

caelus_libs = [
'core',
'specie',
'basicThermophysicalModels'
]

build_lib(env,
          target=target,
          sources=sources,
          caelus_inc=caelus_inc,
          caelus_libs=caelus_libs)
