# -*- mode: python -*-

from build import build_lib
Import('env')

target = 'reactionThermophysicalModels'

sources = Split("""
chemistryReaders/chemistryReader/makeChemistryReaders.cpp
mixtures/basicMultiComponentMixture/basicMultiComponentMixture.cpp
mixtures/basicSpecieMixture/basicSpecieMixture.cpp
mixtures/basicCombustionMixture/basicCombustionMixture.cpp
psiReactionThermo/psiReactionThermo.cpp
psiReactionThermo/psiReactionThermos.cpp
psiuReactionThermo/psiuReactionThermo.cpp
psiuReactionThermo/psiuReactionThermos.cpp
rhoReactionThermo/rhoReactionThermo.cpp
rhoReactionThermo/rhoReactionThermos.cpp
derivedFvPatchFields/fixedUnburntEnthalpy/fixedUnburntEnthalpyFvPatchScalarField.cpp
derivedFvPatchFields/gradientUnburntEnthalpy/gradientUnburntEnthalpyFvPatchScalarField.cpp
derivedFvPatchFields/mixedUnburntEnthalpy/mixedUnburntEnthalpyFvPatchScalarField.cpp
""")

caelus_inc = [
'thermophysicalModels/specie/lnInclude',
'thermophysicalModels/basic/lnInclude',
'thermophysicalModels/solidSpecie/lnInclude'
]

caelus_libs = [
'core',
'specie',
'solidSpecie',
'fluidThermophysicalModels'
]

build_lib(env,
          target=target,
          sources=sources,
          caelus_inc=caelus_inc,
          caelus_libs=caelus_libs)
