# -*- mode: python -*-

from build import build_app
Import('env')

target = 'caelusToSurface'

sources = Split("""
caelusToSurface.cpp
""")

caelus_inc = [
'surfMesh/lnInclude'
]

caelus_libs = [
'core',
'surfMesh'
]

build_app(env,
          target=target,
          sources=sources,
          caelus_inc=caelus_inc,
          caelus_libs=caelus_libs)
