# -*- mode: python -*-

import os
import utils
from build import build_app
Import('env')

target = 'enstrophy'

sources = Split("""
enstrophy_app.cpp
""")

caelus_inc = [
'postProcessing/postCalc'
]

caelus_libs = [
'core'
]

post_calc = [os.path.join(env['LIB_PLATFORM_INSTALL'],'postCalc.o')]
sources += post_calc

ostype = utils.ostype()
prepend_args = {}
if ostype == 'windows':
   prepend_args = {'LINKFLAGS' :
         '-u genericPatchFieldsLoad'
}

build_app(env,
          target=target,
          sources=sources,
          caelus_inc=caelus_inc,
          caelus_libs=caelus_libs,
          prepend_args=prepend_args)
