#Copyright (C) 2014 Applied CCM
import subprocess
Import('globalEnv')

# Clone the global environment so changes made he are not pass onto subsequent 
# libraries
enstrophyEnv = globalEnv.Clone()

# Path to source
src = enstrophyEnv['LIB_SRC']

#===============================================================================
# Additions to compiler flags for this executable
#===============================================================================
enstrophyEnv.Append(CCFLAGS = '')

#===============================================================================
# Additions to include directories for this executable
#===============================================================================
lib_inc = [src + '/postProcessing/postCalc'  
]        

enstrophyEnv.Prepend(CPPPATH = lib_inc)

#===============================================================================
# Additions to link library paths for this executable
#===============================================================================
lib_link_path = []
enstrophyEnv.Prepend(LIBPATH = lib_link_path)

#===============================================================================
# Additions to link libraries for this executable
#===============================================================================
if enstrophyEnv['WHICH_OS'] == "windows":
  enstrophyEnv.Prepend(LINKFLAGS = ' -u genericPatchFieldsLoad')
  lib_link = ['libcore','libgenericPatchFields']
else:
  lib_link = ['core','genericPatchFields']
    
enstrophyEnv.Append(LIBS = lib_link)

#===============================================================================
# Sources for this executable
#===============================================================================
src_files_postCalc = [enstrophyEnv['LIB_PLATFORM_INSTALL'] + '/postCalc.o']

src_files_exec = Split("""  
  enstrophy.cpp
  """)

src_files = src_files_postCalc + src_files_exec
#===============================================================================
# Build this executable
#===============================================================================
binenstrophy = enstrophyEnv.Program(target = 'enstrophy',
source = src_files)

#===============================================================================
# Install this executable
#===============================================================================
install_dir = enstrophyEnv['BIN_PLATFORM_INSTALL']
enstrophyEnv.Alias('install', install_dir)
enstrophyEnv.Install(install_dir, binenstrophy)
