PROJECT_NAME = 'caelus'
PROJECT_VER = '4.10'
PRECISION_OPTION = 'DP'
COMPILER_ARCH = '64'
BUILD_TYPE = 'Opt'
FLEXXX = 'flex'

# Windows setup
#PROJECT_DIR = 'C:\\Program Files\\caelus'
#COMPILER = 'mingw'
#MPI_BIN = 'C:\\Program Files\\MPICH2\\bin'
#MPI_INC = 'C:\\Program Files\\MPICH2\\include'
#MPI_LIB = 'C:\\wondows\\system32'
#MPI_LIB_NAME = 'mpich2'
#SCOTCH_PATH = 'C:\\Program Files\\caelus\\caelus-4.10\\external\\scotch-5.1.12'
#ZLIB_PATH = 'C:\\Program Files\\caelus\\caelus-4.10\\external\\windows\\zlib-1.2.7'
#FLEXXX_PATH = 'C:\\Program Files\\caelus\\caelus-4.10\\external\\windows\\flex-2.5.4a-1'
#COLOUR_BUILD = '0'

#Linux setup
#PROJECT_DIR = '/opt/caelus'
#MPI_BIN = '/opt/caelus/caelus-4.10/external/linux/openmpi-1.6.5/bin'
#MPI_INC = '/opt/caelus/caelus-4.10/external/linux/openmpi-1.6.5/include'
#MPI_LIB = '/opt/caelus/caelus-4.10/external/linux/openmpi-1.6.5/lib'
#MPI_LIB_NAME = 'mpi'
#SCOTCH_PATH = '/opt/caelus/caelus-4.10/external/scotch-5.1.12'
#METIS_PATH = '$/opt/caelus/caelus-4.10/external/metis-5.1.0'
#COLOUR_BUILD = '$0'