#Copyright (C) 2016 Applied CCM
import subprocess
Import('globalEnv')

# Clone the global environment so changes made he are not pass onto subsequent 
# libraries
gmshToCaelusEnv = globalEnv.Clone()

# Path to source
src = gmshToCaelusEnv['LIB_SRC']

#===============================================================================
# Additions to compiler flags for this executable
#===============================================================================
gmshToCaelusEnv.Append(CCFLAGS = '')

#===============================================================================
# Additions to include directories for this executable
#===============================================================================
lib_inc = [src + '/dynamicMesh/lnInclude']
gmshToCaelusEnv.Prepend(CPPPATH = lib_inc)

#===============================================================================
# Additions to link library paths for this executable
#===============================================================================
lib_link_path = []
gmshToCaelusEnv.Prepend(LIBPATH = lib_link_path)

#===============================================================================
# Additions to link libraries for this executable
#===============================================================================
lib_link = ['dynamicMesh']

gmshToCaelusEnv.Append(LIBS = lib_link)

#===============================================================================
# Sources for this executable
#===============================================================================
src_files = Split("""
  gmshToCAELUS.cpp
  """)

#===============================================================================
# Build this executable
#===============================================================================
bingmshToCaelus = gmshToCaelusEnv.Program(target = 
'gmshToCAELUS', source = src_files)

#===============================================================================
# Install this executable
#===============================================================================
install_dir = gmshToCaelusEnv['BIN_PLATFORM_INSTALL']
gmshToCaelusEnv.Alias('install', install_dir)
gmshToCaelusEnv.Install(install_dir, bingmshToCaelus)
