#Copyright (C) 2014 Applied CCM
import subprocess
Import('globalEnv')

# Clone the global environment so changes made he are not pass onto subsequent 
# libraries
stitchMeshEnv = globalEnv.Clone()

# Path to source
src = stitchMeshEnv['LIB_SRC']

stitchMeshEnv.Append(CXXFLAGS = '')
#===============================================================================
# Additions to compiler flags for this executable
#===============================================================================
stitchMeshEnv.Append(CCFLAGS = '')

#===============================================================================
# Additions to include directories for this executable
#===============================================================================
lib_inc = [src + '/dynamicMesh/lnInclude']
stitchMeshEnv.Prepend(CPPPATH = lib_inc)

#===============================================================================
# Additions to link library paths for this executable
#===============================================================================
lib_link_path = []
stitchMeshEnv.Prepend(LIBPATH = lib_link_path)

#===============================================================================
# Additions to link libraries for this executable
#===============================================================================
if stitchMeshEnv['WHICH_OS'] == "windows":
  stitchMeshEnv.Prepend(LINKFLAGS = ' -u genericPatchFieldsLoad')

lib_link = ['dynamicMesh','genericPatchFields']
  
stitchMeshEnv.Append(LIBS = lib_link)

#===============================================================================
# Sources for this executable
#===============================================================================
src_files = Split("""
  stitchMesh.cpp
  """)

#===============================================================================
# Build this executable
#===============================================================================
binstitchMesh = stitchMeshEnv.Program(target = 
'stitchMesh', source = src_files)

#===============================================================================
# Install this executable
#===============================================================================
install_dir = stitchMeshEnv['BIN_PLATFORM_INSTALL']
stitchMeshEnv.Alias('install', install_dir)
stitchMeshEnv.Install(install_dir, binstitchMesh)
