#Copyright (C) 2014 Applied CCM
import subprocess
Import('globalEnv')

# Clone the global environment so changes made he are not pass onto subsequent 
# libraries
yPlusRASEnv = globalEnv.Clone()

# Path to source
src = yPlusRASEnv['LIB_SRC']

#===============================================================================
# Additions to compiler flags for this executable
#===============================================================================
yPlusRASEnv.Append(CCFLAGS = '')

#===============================================================================
# Additions to include directories for this executable
#===============================================================================
lib_inc = [
src + '/turbulenceModels',
src + '/turbulenceModels/incompressible/turbulenceModel/lnInclude',
src + '/turbulenceModels/incompressible/RAS/lnInclude',
src + '/turbulenceModels/incompressible/RAS/derivedFvPatchFields/wallFunctions' + 
'/nutWallFunctions',
src + '/turbulenceModels/compressible/turbulenceModel/lnInclude',
src + '/turbulenceModels/compressible/RAS/lnInclude',
src + '/turbulenceModels/compressible/RAS/derivedFvPatchFields/wallFunctions' + 
'/mutWallFunctions',
src + '/transportModels',
src + '/transportModels/incompressible/lnInclude',
src + '/thermophysicalModels/basic/lnInclude',
]
yPlusRASEnv.Prepend(CPPPATH = lib_inc)

#===============================================================================
# Additions to link library paths for this executable
#===============================================================================
lib_link_path = []
yPlusRASEnv.Prepend(LIBPATH = lib_link_path)

#===============================================================================
# Additions to link libraries for this executable
#===============================================================================
if yPlusRASEnv['WHICH_OS'] == "windows":
  yPlusRASEnv.Prepend(LINKFLAGS = ' -u genericPatchFieldsLoad -u incompressibleRASModelsLoad -u compressibleRASModelsLoad')
  lib_link = ['libgenericPatchFields','libcompressibleRASModels',
  'libspecie','libbasicThermophysicalModels','libsampling',
  'libcompressibleTurbulenceModel','libincompressibleRASModels',
  'libincompressibleTransportModels','libincompressibleTurbulenceModel']
else:
  lib_link = ['genericPatchFields','compressibleRASModels',
  'specie','basicThermophysicalModels','sampling',
  'compressibleTurbulenceModel','incompressibleRASModels',
  'incompressibleTransportModels','incompressibleTurbulenceModel']

yPlusRASEnv.Append(LIBS = lib_link)

#===============================================================================
# Sources for this executable
#===============================================================================
src_files = Split("""
 yPlusRAS.cpp
  """)

#===============================================================================
# Build this executable
#===============================================================================
binyPlusRAS=yPlusRASEnv.Program(target = 'yPlusRAS', 
source = src_files)

#===============================================================================
# Install this executable
#===============================================================================
install_dir =yPlusRASEnv['BIN_PLATFORM_INSTALL']
yPlusRASEnv.Alias('install', install_dir)
yPlusRASEnv.Install(install_dir, binyPlusRAS)
