#Copyright (C) 2014 Applied CCM
import subprocess
Import('globalEnv')

# Clone the global environment so changes made he are not pass onto subsequent 
# libraries
pisoSolEnv = globalEnv.Clone()

# Path to source
src = pisoSolEnv['LIB_SRC']

#===============================================================================
# Additions to compiler flags for this executable
#===============================================================================
pisoSolEnv.Append(CCFLAGS = '')

#===============================================================================
# Additions to include directories for this executable
#===============================================================================
lib_inc = [pisoSolEnv['LIB_SRC'] +  '/turbulenceModels',
src + '/turbulenceModels/incompressible/turbulenceModel/lnInclude', 
src + '/transportModels',
src + '/transportModels/incompressible/singlePhaseTransportModel',
src + '/transportModels/incompressible/lnInclude'
]
pisoSolEnv.Prepend(CPPPATH = lib_inc)

#===============================================================================
# Additions to link library paths for this executable
#===============================================================================
lib_link_path = []
pisoSolEnv.Prepend(LIBPATH = lib_link_path)

#===============================================================================
# Additions to link libraries for this executable
#===============================================================================
if pisoSolEnv['WHICH_OS'] == "windows":
  pisoSolEnv.Prepend(LINKFLAGS = ' -u incompressibleRASModelsLoad  -u incompressibleLESModelsLoad  -u incompressibleVLESModelsLoad')

lib_link = ['incompressibleTurbulenceModel', 'incompressibleRASModels', 'incompressibleLESModels', 'incompressibleVLESModels', 'incompressibleTransportModels']
  
pisoSolEnv.Append(LIBS = lib_link)

#===============================================================================
# Sources for this executable
#===============================================================================
src_files = Split("""
  pisoSolver.cpp
  """)

#===============================================================================
# Build this executable
#===============================================================================
binpisoSol = pisoSolEnv.Program(target = 'pisoSolver', source = src_files)

#===============================================================================
# Install this executable
#===============================================================================
install_dir = pisoSolEnv['BIN_PLATFORM_INSTALL']
pisoSolEnv.Alias('install', install_dir)
pisoSolEnv.Install(install_dir, binpisoSol)
